// R39: passive-tree jewel guide, separate from skill gems. No changes to builds.
function j39Stage(){return D.jewelGuide.stages[state.stage]||D.jewelGuide.stages.e01;}
function j39Sources(ids){return `<div class="jewel-sources">${ids.map(id=>{const s=D.jewelGuide.sources.find(s=>s.id===id);return s?safeLink(s.url,s.title):''}).join(' · ')}</div>`;}
function j39Tabs(special=false){return `<div class="actions jewel-tabs">${routeLink('jewels','人物天赋珠宝清单','btn'+(!special?' primary':''),{stage:state.stage})}${routeLink('special-jewels','特殊人物珠宝','btn'+(special?' primary':''),{stage:state.stage})}${routeLink('character','返回人物天赋','btn',{stage:state.stage})}<a class="btn" href="R39_人物天赋珠宝清单.md" download>保存珠宝清单</a></div>`;}
function j39PlanText(p){return p.items.map(i=>`${i.qty}颗${esc(D.jewelGuide.catalog[i.id].zh)}`).join(' ＋ ');}
function j39Bridge(){const s=j39Stage();return `<div class="jewel-bridge" data-jewel-bridge><div><span class="tag">人物天赋树镶嵌</span><h3>这里要装的是珠宝，不是技能宝石</h3><p>回蓝蓝玉、普通输出珠宝，以及泉井之心／抗衡黑暗分别看。<b>本原件记录${s.uniqueCount}个不同珠宝槽</b>，未记录每孔实装${s.readonly?'；06仅只读对照':''}。</p></div><div class="actions">${routeLink('jewels','需要哪些珠宝','btn primary',{stage:state.stage})}${routeLink('special-jewels','特殊珠宝单独看','btn',{stage:state.stage})}</div></div>`;}
function j39Summary(){const s=j39Stage();return `<div class="jewel-summary"><div><b>${s.uniqueCount}</b><span>个不同珠宝槽 · 原件ID去重</span></div><div><b>${s.recordCount}</b><span>条珠宝槽记录 · 含武器组记录</span></div><div><b>未导出</b><span>逐孔已装珠宝及其词缀</span></div></div>`;}
function j39CatalogTable(){return `<div class="panel table-scroll"><table class="jewel-table jewel-overview"><thead><tr><th>要准备什么</th><th>数量怎样算</th><th>看哪类属性</th></tr></thead><tbody>${Object.values(D.jewelGuide.catalog).map(x=>`<tr data-jewel-id="${x.id}"><td><strong>${esc(x.zh)}</strong><div class="sub">${esc(x.en)}</div><span class="tag ${x.special?'gold':'gray'}">${esc(x.kind)}</span></td><td>${esc(x.qty)}</td><td>${esc(x.goal)}${j39Sources(['fubgun'])}</td></tr>`).join('')}</tbody></table></div>`;}
function j39Plans(){const s=j39Stage();if(s.readonly)return note('<b>06仅保留原始记录：</b>不把5个不同节点ID转换成已验证的采购表或转型指令。',true);
 return `<p class="jewel-intro">${esc(s.focus)}</p><div class="jewel-plans">${s.plans.map(p=>`<article class="panel jewel-plan" data-jewel-plan-total="${p.total}"><div class="split"><h3>${esc(p.title)}</h3><span class="tag gray">${p.total} / ${s.uniqueCount} 孔</span></div><p>${j39PlanText(p)}</p><div class="small muted">${esc(p.provenance)}</div></article>`).join('')}</div><p class="jewel-capacity"><b>每张卡是一套选择，不要叠加。</b>${esc(s.next)}</p>`;
}
function j39Card(id){const x=D.jewelGuide.catalog[id];return `<article class="panel jewel-detail" data-jewel-detail="${x.id}"><header><div><span class="tag ${x.special?'gold':'gray'}">${esc(x.kind)}</span><h3>${esc(x.zh)}</h3><p class="sub">${esc(x.en)}</p></div><span class="jewel-limit">${x.special?'限定 1 颗':'按现有槽位'}</span></header><div class="jewel-goal"><b>目标词缀</b><p>${esc(x.goal)}</p>${x.mods.map(m=>`<p class="small">${esc(m)}</p>`).join('')}</div><dl class="jewel-facts">${[['when','什么时候准备'],['qty','准备数量'],['get','怎样取得'],['socket','怎么镶嵌'],['fallback','暂时没有'],['limits','避免误用']].map(([k,t])=>`<div><dt>${t}</dt><dd>${esc(x[k])}</dd></div>`).join('')}</dl>${j39Sources(x.sourceIds)}</article>`;}
function j39SocketEvidence(){const s=j39Stage();return `<p class="jewel-intro">只能据此确认快照里有哪些珠宝槽节点；不能据此知道每孔装了哪颗。编号是导出记录，不是人物等级或加点顺序。</p><div class="panel table-scroll"><table class="jewel-table jewel-sockets"><thead><tr><th>原件珠宝槽ID</th><th>记录序号</th><th>所属记录</th><th>实装与位置证据</th></tr></thead><tbody>${s.rows.map(r=>`<tr data-jewel-socket="${esc(r.id)}" data-jewel-scope="${r.weaponSet||0}"><td><code>${esc(r.id)}</code></td><td>${r.exportIndex}</td><td>${esc(r.scope)}</td><td>珠宝未导出；未核实圈定位置</td></tr>`).join('')}</tbody></table></div>${s.readonly?note('<b>不要重复采购：</b>jewel_slot1960在公共和武器组2各记录一次；6条记录只对应5个不同ID。仍不能据此证明5颗同时生效。',true):''}<div class="jewel-proof"><p>原件：<a href="${esc(s.sourceFile)}" download>${esc(s.sourceFile.split('/').pop())}</a></p><p class="mono">SHA-256：${esc(s.sha256)}</p><p>未取得完整人物树坐标和逐槽绑定，不画假位置、不编种子，也不宣称某个ID一定是抗衡黑暗最佳孔。</p></div>`;}
function j39StageTable(){return `<div class="panel table-scroll"><table class="jewel-table jewel-stage-table"><thead><tr><th>阶段</th><th>不同孔位／记录</th><th>准备重点</th></tr></thead><tbody>${Object.values(D.jewelGuide.stages).map(s=>`<tr class="${s.id===state.stage?'jewel-current-stage':''}"><td>${routeLink('jewels',esc(s.label),'text-link',{stage:s.id})}${s.readonly?'<div class="tag gold">只读</div>':''}</td><td>${s.uniqueCount} / ${s.recordCount}</td><td>${esc(s.focus)}</td></tr>`).join('')}</tbody></table></div>`;}
function j39Range(){return `<div class="panel panel-inner jewel-range"><h3>先看实物词缀，再看实际覆盖</h3><p>抗衡黑暗的额外伤害目标作用于范围内的<b>核心天赋</b>。把珠宝放到已分配槽位预览半径，只数符合那条描述、且已经分配的核心节点；不要把附近所有小点都算进去。</p><p>例子：一条“每个核心提供额外冰霜3%”覆盖3个合格已分配核心，这条带来的额外冰霜比例为 <b>3% × 3 = 9%</b>。这是解释用情景，不是作者插装，也不等于角色实际DPS一定提高9%。</p><p><b>泉井之心不是这套算法。</b>它所述的双额外伤害属于珠宝自身属性，不再乘周围节点个数。</p><p class="small muted">按实物半径和具体词缀复查；范围或词缀可能有版本差异。缺少逐孔截图，本页不会把任何原件节点ID标为确定最佳位置。</p></div>${j39Sources(['well','darkness'])}`;}
function j39Checks(){return `<div class="panel jewel-checklist">${[
 ['看槽位','打开人物天赋树并分配珠宝槽，不是技能界面、装备增幅孔或异界树。'],
 ['看对象','蓝玉是基底；血脉辅助、未切割宝石、符文、深渊之眼不放进这张采购清单。'],
 ['看条件','回蓝词缀需击杀；抗衡黑暗要核对核心／小型节点、实际半径与分配状态。'],
 ['看数量','两颗特殊珠宝各限定1颗、各占一槽。别把阶段替换清单当额外新增槽。'],
 ['看切换','先保留旧珠宝，在双武器组分别确认生效；清图和无小怪首领分别验证供蓝。'],
 ['看投入','不把普通珠宝套成防具六词缀，也不要求所有珠宝20品质；已有只读高级工艺仍只读。']
 ].map(([a,b])=>`<div><b>${a}</b><p>${b}</p></div>`).join('')}</div>`;}
function j39Evidence(){return expand('出处、原件与本次核对范围',`<p>${esc(D.jewelGuide.basis)}</p><p>${esc(D.jewelGuide.boundary)}</p><p>外部资料核对：${esc(D.jewelGuide.checked)}；页面内阶段组合为本站容量检查后的准备示例，不代表作者逐孔佩戴。程序验证不代替国服客户端和游戏实测。</p>${D.jewelGuide.sources.map(s=>`<div class="jewel-source-row"><b>${esc(s.kind)}</b><div>${safeLink(s.url,s.title)}<p class="small muted">${esc(s.use)}</p></div></div>`).join('')}`);}
function jewelsPage(){const s=j39Stage();let h=heading('人物与技能 / 人物天赋珠宝','人物天赋，要装哪些珠宝？','先看本阶段准备，再区分普通珠宝与两颗特殊珠宝。',true)+phaseNote(true)+j39Tabs()+j39Summary();
 h+=note('<b>这些才是放进人物天赋树的珠宝。</b>下表是作者建议涉及的种类，不代表每类在当前阶段都必须再买一颗；技能／辅助宝石清单已另列。');
 let main=sec('jewel-list','01','要找哪几类珠宝',j39CatalogTable(),'',true);
 main+=sec('jewel-plan','02','当前阶段怎样准备',j39Plans());
 main+=sec('jewel-ordinary','03','普通珠宝：先把词缀选对',`<div class="jewel-detail-grid">${j39Card('mana')}${j39Card('ordinary')}</div><div class="actions jewel-links">${routeLink('item/jewels','普通珠宝原有获取与加工说明','btn',{stage:state.stage})}${routeLink('special-jewels','泉井之心、抗衡黑暗单独看','btn primary',{stage:state.stage})}</div>`);
 main+=sec('jewel-sockets','04','本原件有哪些珠宝槽',j39SocketEvidence());
 main+=sec('jewel-stages','05','六阶段对照',j39StageTable());
 main+=sec('jewel-check','06','镶嵌后怎样检查',j39Checks());main+=j39Evidence();
 return h+`<div class="content-with-toc"><div>${main}</div>${toc([['jewel-list','01','珠宝种类'],['jewel-plan','02','本阶段准备'],['jewel-ordinary','03','普通词缀'],['jewel-sockets','04','原件孔位'],['jewel-stages','05','阶段对照'],['jewel-check','06','镶嵌验收']])}</div>`+footer();
}
function specialJewelsPage(){const s=j39Stage();let h=heading('人物与技能 / 特殊人物珠宝','泉井之心与抗衡黑暗','同样放进人物天赋树，但词缀生效方式不同。',true)+phaseNote(true)+j39Tabs(true);
 h+=note('<b>每种限定1颗，各占一个槽。</b>作者正文明确提到这两颗，但六份原件未记录逐孔实装。不是买到名字相同的珠宝，就等于拿到作者要的效果。');
 let main=sec('jewel-specials','01','两颗特殊珠宝，分别看清',`<div class="jewel-detail-grid special-jewel-grid">${D.jewelGuide.specialIds.map(j39Card).join('')}</div>`,'',true);
 main+=sec('jewel-radius','02','抗衡黑暗：孔位与范围怎么判断',j39Range());
 main+=sec('jewel-fit','03','放进当前阶段，要替换哪一颗',j39Plans()+`<div class="actions jewel-links">${routeLink('jewels','查看本阶段孔位和完整清单','btn',{stage:state.stage})}</div>`);
 main+=sec('jewel-keep','04','没有合适的，不先拆掉过渡珠宝',`<div class="panel panel-inner"><p>普通输出珠宝可以先留着；需要击杀回蓝时保留蓝玉。已有两颗特殊珠宝，也不能忽略三孔上限、覆盖条件或供蓝缺口。</p><p>本版不把血脉辅助当人物珠宝；不把作者没有明确提及的其他暗金珠宝加进必需清单。</p></div>`+j39Checks());main+=j39Evidence();
 return h+`<div class="content-with-toc"><div>${main}</div>${toc([['jewel-specials','01','两颗特殊珠宝'],['jewel-radius','02','范围与位置'],['jewel-fit','03','本阶段替换'],['jewel-keep','04','保留过渡']])}</div>`+footer();
}
function j39SearchEntries(){return [{title:'人物天赋需要哪些珠宝',text:'回蓝蓝玉、普通输出珠宝、六阶段孔位与准备',route:'jewels',params:{stage:state.stage},query:'宝石 人物 天赋 珠宝 孔位 要哪些 数量 镶嵌'}, {title:'特殊人物珠宝：泉井之心、抗衡黑暗',text:'目标词缀、限定数量、作用范围、取得与过渡',route:'special-jewels',params:{stage:state.stage},query:'特殊 人物 天赋 宝石 珠宝 暗金 范围'},...Object.values(D.jewelGuide.catalog).map(x=>({title:x.zh+' · 人物天赋珠宝',text:x.en+' / '+x.kind,route:x.special?'special-jewels':'jewels',params:{stage:state.stage},query:x.goal+' '+x.qty+' '+x.socket})),...j39Stage().uniqueIds.map(id=>({title:id+' · 原件珠宝槽',text:'节点证据，不代表已插某颗珠宝',route:'jewels',params:{stage:state.stage},query:id+' 位置 孔位'}))];}
