// R43: verified capture is a separate, immutable evidence layer.
const C43=window.FUBGUN_CAPTURE43;
const _r42search=searchData,_r42gear=gear,_r42item=itemPage,_r42character=character,_r42jewels=jewelsPage,_r42specialJewels=specialJewelsPage,_r42atlas=atlasPage,_r42choices=atlasChoices,_r42tools=tools,_r42coverage=coverage,_r42guide=guide;
const R43_MAIN=['bow','quiver','helmet','body','gloves','boots','amulet','belt','ring1','ring2'];
const R43_STAT={'Critical Hit Chance':'暴击率','Physical Damage':'物理伤害','Cold Damage':'冰霜伤害','Fire Damage':'火焰伤害','Lightning Damage':'闪电伤害','Energy Shield':'能量护盾','Evasion Rating':'闪避值','Armour':'护甲','Item Level':'物品等级','Quality':'品质','Attack Speed':'攻击速度','Attacks per Second':'每秒攻击次数','Spirit':'精魂'};
function r43Build(){return q42CP()?null:C43.builds.find(b=>b.stage===state.stage);}
function r43Evidence(p){return '采集证据_20261005/'+p.split('/').map(encodeURIComponent).join('/');}
function r43EvidenceLink(p,text='原始证据'){return p?`<a class="text-link" href="${esc(r43Evidence(p))}" target="_blank" rel="noopener">${text} ↗</a>`:'';}
function r43ButtonImage(p,label){return p?`<button class="btn small" type="button" data-r43-image="${esc(r43Evidence(p))}" data-r43-title="${esc(label)}">查看截图</button>`:'';}
function r43List(xs){return `<ul class="r43-prose-list">${xs.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`;}
function r43BuildTabs(route='gear',extra={}){return `<nav class="r43-builds" aria-label="Build 原名称">${C43.builds.map(b=>routeLink(route,esc(b.name)+(b.stage==='e06'?'<small>只读</small>':''),'r43-build '+(state.stage===b.stage?'is-active':'')+(b.stage==='e06'?' separate':''),{stage:b.stage,...extra})).join('')}</nav>`;}
labelStage=function(p){return C43.builds.find(b=>b.stage===p.id)?.name||p.label;};
footer=function(){return `<footer class="footer"><span>Fubgun · R43 / 2026-10-05 采集核对版</span><div>${q42Link('tools/capture-audit','来源与差异')} · ${q42Link('tools/filters','未修改的原版过滤器')}</div></footer>`;};
function r43Head(title,desc='',route='gear',extra={}){const b=r43Build();return heading('FUBGUN / 原页数据核对',title,desc,true)+(b?r43BuildTabs(route,extra):'');}
function r43Meta(b){return `<div class="r43-context"><div><b>${esc(b.name)}</b><span>${esc(b.notes.brief)}</span></div><div><span class="r43-label">${b.notes.referenceLevel?'参考树 '+b.notes.referenceLevel+' 级':'独立快照 · 非必经升级'}</span>${q42Link('character','何时换天赋 →','text-link',{tab:'tree'})}</div></div>`;}
function r43Kind(m){return m.tier_label||(m.kind==='implicit_styled'?'固有样式':m.text.startsWith('Allocates ')?'涂膏／授予':'面板');}
function r43Panel(panel,css=''){return `<ul class="r43-mods ${css}">${panel.modifiers.map((m,i)=>`<li data-r43-mod="${i}"><span class="r43-mod-kind">${esc(r43Kind(m))}</span><span title="${esc(m.text)}">${esc(m.zh||m.text)}</span></li>`).join('')}</ul>`;}
function r43RuneEffect(s,it){const list=s.panel.modifiers;let prefixes=it.slot==='mainHand'?['Martial Weapon:','Bow:','All:']:it.slot==='body'?['Armour:','Body Armour:','All:']:it.slot==='helmet'?['Armour:','Helmet:','All:']:it.slot==='gloves'?['Armour:','Gloves:','All:']:it.slot==='boots'?['Armour:','Boots:','All:']:['All:'];const matches=list.filter(m=>prefixes.some(p=>m.text.startsWith(p)));return (matches.length?matches:list).map(m=>esc(m.zh||m.text)).join('；');}
function r43RuneLines(it){if(!it.socketed_items?.length)return '<div class="r43-quiet">镶嵌：本次保存配置未设置。</div>';return `<div class="r43-runes"><b>页面实际镶嵌 · ${it.socketed_items.length} 孔关联</b>${it.socketed_items.map(s=>`<div class="r43-rune" data-socket="${s.socket_index}"><span>孔 ${s.socket_index}</span><div><strong>${esc(s.name)}</strong><small>${r43RuneEffect(s,it)}</small></div></div>`).join('')}</div>`;}
function r43Originals(it){return `<details class="r43-proof"><summary>英文原面板、保存描述与证据</summary><pre>${esc(it.panel.raw_text)}</pre>${it.storedDescriptions?.length?`<h4>网页保存描述（不覆盖面板范围）</h4><pre>${esc(it.storedDescriptions.join('\n'))}</pre>`:''}${it.oldRecord?.old_descriptions?.length?`<h4>旧 .build 原始记录（历史对照）</h4><pre>${esc(it.oldRecord.old_descriptions.join('\n'))}</pre>`:''}<details><summary>网页保存字段（品质、需求等；不覆盖实际面板）</summary><pre>${esc(JSON.stringify(it.source_configuration.commonItem,null,2))}</pre></details><div class="r43-proof-links">${r43ButtonImage(it.imageEvidence,it.name)}${r43EvidenceLink(it.textEvidence,'完整面板原文')}${r43EvidenceLink('builds.json','采集结构化记录')}</div>${it.socketed_items?.length?`<details><summary>镶嵌物全部部位效果（不相加）</summary>${it.socketed_items.map(s=>`<h4>孔 ${s.socket_index} · ${esc(s.name)}</h4><pre>${esc(s.panel.raw_text)}</pre>`).join('')}</details>`:''}</details>`;}
function r43Card(it,b,isolated=false){const stat=it.panel.top_stats||[],req=it.panel.requirements||[],warn=it.sourcePanelCaution||[],title=D.slots.find(s=>s.id===it.uid)?.name||it.slot_label;const changed=it.diffFromPrevious;let quality=it.quality===null?'品质：面板未写':`品质：${esc(it.quality)}`;let badge=changed?`<span class="r43-diff ${changed}">${changed==='same'?'沿用相同面板':'与上一 build 不同'}</span>`:'';
return `<article class="r43-equip ${it.source_is_unique?'r43-unique':''}" id="r43-item-${it.uid}" data-capture-item="${esc(it.id)}"><header><div class="r43-slot">${esc(title)} <small>${it.weapon_group==='Shared'?'两组共用':esc(it.weapon_group)}</small></div>${badge}<h2>${esc(it.name)}</h2>${it.zhName&&it.zhName!==it.name?`<p class="r43-zhname">${esc(it.zhName)}</p>`:''}</header>${warn.length?`<div class="r43-warning">${warn.map(x=>`<p>${esc(x)}</p>`).join('')}</div>`:''}${stat.length?`<div class="r43-stats" aria-label="网页顶部显示值">${stat.map(s=>`<div><small>${esc(R43_STAT[s.label]||s.label)}</small><b>${esc(s.value)}</b></div>`).join('')}</div>`:''}${it.panel.modifiers.length?r43Panel(it.panel):'<p class="r43-missing">本次悬浮面板未显示显性词缀。下方保留保存字段，不能据此宣称成品属性已核验。</p>'}${r43RuneLines(it)}<div class="r43-requirements">${req.length?'佩戴：'+req.map(x=>esc(({Level:'等级',Strength:'力量',Dexterity:'敏捷',Intelligence:'智慧'}[x.label]||x.label)+' '+x.value)).join(' / '):'佩戴：以面板实际提示为准'}<span>${quality}</span></div>${it.anointment?`<p class="r43-quiet">已保存涂膏：${esc(it.panel.modifiers.find(m=>m.text.startsWith('Allocates '))?.text.replace('Allocates ','')||it.anointment.slug)}</p>`:''}${b.stage==='e05'&&it.uid==='helmet'?'<p class="r43-prose-hint">正文备选：Thin Ice 头盔涂膏；未写入这件的涂膏字段，不冒充已镶配。</p>':''}${b.stage==='e06'&&it.uid==='helmet'?'<p class="r43-prose-hint">正文另写 Zarokh’s Gift。新增孔的合法分配仍待核，不因有涂膏说明就把 7 颗都判为生效。</p>':''}${r43Originals(it)}${b.stage!=='e06'?`<div class="r43-card-action">${q42Link('item/'+it.uid,'这件怎么取得／打造 →','text-link',{tab:'craft'})}<span>步骤在独立页</span></div>`:'<div class="r43-card-action"><span>Live Gear 只读，不套用通用制作建议</span></div>'}</article>`;}
function r43JewelCard(j,b){const warn=j.node_in_explicit_selected_lists===false;return `<article class="r43-equip r43-jewel" data-capture-jewel="${esc(j.id)}"><header><div class="r43-slot">人物天赋珠宝 · 展示 ${j.display_order}<small>${j.source_is_unique?'特殊珠宝':'普通珠宝'}</small></div><h2>${esc(j.name)}</h2>${j.zhName&&j.zhName!==j.name?`<p class="r43-zhname">${esc(j.zhName)}</p>`:''}</header>${r43Panel(j.panel)}<div class="r43-binding ${warn?'r43-warning':''}"><b>绑定 ${esc(j.node_id)}</b><span>${warn?'未在显式已选节点列表中找到；额外孔位和生效未核实。':'保存绑定与显式已选节点匹配；不据此验证全部连线路径。'}</span>${j.radius?`<span>半径：${esc(j.radius)}</span>`:''}</div><details class="r43-proof"><summary>英文原文与证据</summary><pre>${esc(j.panel.raw_text)}</pre><div class="r43-proof-links">${r43ButtonImage(j.imageEvidence,j.name+' · '+j.node_id)}${r43EvidenceLink('builds.json','绑定及原始记录')}</div></details></article>`;}
function r43Jewels(b,specialOnly=false){const js=b.jewels.filter(j=>!specialOnly||j.source_is_unique);return `<section class="r43-section" id="r43-jewels"><div class="r43-section-title"><h2>人物天赋珠宝</h2><span>${js.length} 颗可见记录</span></div><p class="r43-description">${esc(b.notes.jewelProse)}</p>${js.length?`<div class="r43-grid">${js.map(j=>r43JewelCard(j,b)).join('')}</div>`:note('当前页没有明确的珠宝物品配置，不是还需你逐颗截图。作者正文建议与已镶嵌记录分开显示。')}${b.saved_not_displayed_jewels.length?`<details class="r43-proof"><summary>另有 ${b.saved_not_displayed_jewels.length} 条保存但未展示的绑定</summary>${b.saved_not_displayed_jewels.map(j=>`<p>${esc(j.node_id)}：未显示属性面板，未计入上方可见珠宝数，不用词缀池或交易筛选值补成实际范围。</p>`).join('')}</details>`:''}</section>`;}
gear=function(){const b=r43Build();if(!b)return _r42gear();const items=b.equipment,main=R43_MAIN.map(u=>items.find(x=>x.uid===u)).filter(Boolean),utility=items.filter(x=>!R43_MAIN.includes(x.uid)&&x.uid!=='weapon2');let out=r43Head('全身装备，一页看清','每件的属性、镶嵌和人物珠宝都直接展开；天赋、异界和制作步骤分别阅读。')+r43Meta(b)+`<div class="r43-reading"><b>范围不是实装掷值。</b> 主栏照录实际悬浮面板并翻译；顶部伤害与防御不再重复叠加下方词缀或符文。保存描述与旧导出另列，未给词缀不强行补满六条。<div class="r43-jumps"><a href="#" data-scroll="r43-main">主装备</a><a href="#" data-scroll="r43-utility">药剂与咒符</a><a href="#" data-scroll="r43-set2">Set 2</a><a href="#" data-scroll="r43-jewels">人物珠宝</a></div></div>`;
if(b.stage==='e06')out+=note('<b>Live Gear 只读：</b>弓保存值与面板不一致，部分珠宝孔的实际分配未核验。下方完整列出已取得内容，不把它当已通过实战的配装。',true);
out+=`<section class="r43-section" id="r43-main"><div class="r43-section-title"><h2>Set 1 · 十件主装备</h2><span>完整面板 · 可向下滚动</span></div><div class="r43-grid">${main.map(i=>r43Card(i,b)).join('')}</div></section><section class="r43-section" id="r43-utility"><div class="r43-section-title"><h2>药剂与咒符</h2><span>两组共用，不遗漏辅助栏</span></div><div class="r43-grid utility">${utility.map(i=>r43Card(i,b)).join('')}</div></section><section class="r43-section" id="r43-set2"><div class="r43-section-title"><h2>Set 2 · 独立武器</h2></div>${items.some(x=>x.uid==='weapon2')?`<div class="r43-grid">${items.filter(x=>x.uid==='weapon2').map(i=>r43Card(i,b)).join('')}</div><p class="r43-description">副手按双手物品占位阻止；重复图标不多算一件装备。</p>`:'<p class="r43-description">当前作者保存配置未给 Set 2 独立主手／副手；其他装备共用。技能的 Set 2 绑定不等于这里另有一整套装备。</p>'}</section>`+r43Jewels(b)+`<section class="r43-next"><b>装备看完，再去下一页</b><div>${q42Link('character','人物天赋与切换条件','btn',{tab:'tree'})}${q42Link('character','技能与武器组','btn',{tab:'skills'})}${routeLink('atlas/'+state.variant,'异界方案','btn')}${q42Link('early-craft','单件逐步打造','btn')}</div></section>`+footer();return out;};
itemPage=function(slot,params){const b=r43Build();if(!b)return _r42item(slot,params);if(slot==='jewels')return jewelsPage();const it=b.equipment.find(x=>x.uid===slot),tab=params.get('tab')||'target';if(it&&(tab==='target'||b.stage==='e06'))return r43Head(it.name,'本页目标与全身页共用同一份采集数据。','item/'+slot,{tab:'target'})+`<div class="r43-links">${q42Link('gear','← 返回全身装备','btn')}${b.stage!=='e06'?q42Link('item/'+slot,'进入一步步做','btn primary',{tab:'craft'}):'<span class="r43-label">只读参考</span>'}</div>`+r43Card(it,b,true)+footer();let html=_r42item(slot,params);if(!it)return html;const t=document.createElement('template');t.innerHTML=html;const tabbar=t.content.querySelector('.q42-tabs');const block=document.createElement('section');block.className='r43-craft-reference';block.innerHTML=`<div class="r43-context"><b>目标：${esc(it.name)} · ${esc(b.name)}</b>${q42Link('gear','查看这套全部装备 →')}</div>`+(tab==='finish'?`<div class="r43-panel"><h2>先对照作者已镶嵌内容</h2>${r43RuneLines(it)}<p>本页面板品质：${it.quality===null?'未写，不自动填 20%':esc(it.quality)}。下面是普通加工方法；方法建议不是作者这件装备的品质实装证明。</p></div>`:`<p class="r43-description">制作方法与装备面板分开：范围是展示档位，不是每一步必出上限；旧导出示例数值不是本次网页实装掷值。</p>`);if(tabbar)tabbar.after(block);else t.content.prepend(block);return t.innerHTML;};
jewelsPage=function(){const b=r43Build();return b?r43Head('人物天赋珠宝','逐颗面板与绑定独立保存；不是同图标就同属性。','jewels')+r43Jewels(b)+q42Link('gear','← 回到整套装备','btn')+footer():_r42jewels();};
specialJewelsPage=function(){const b=r43Build();return b?r43Head('特殊人物珠宝','只列该 build 当前可见的特殊珠宝；其他 build 不自动复用。','special-jewels')+r43Jewels(b,true)+q42Link('jewels','查看全部人物珠宝','btn')+footer():_r42specialJewels();};
function r43Prose(b,section){const s=b.author_text.find(x=>x.section===section);return s?`<details class="r43-proof"><summary>该分支作者 ${esc(section)} 原文与来源</summary>${s.blocks.map(p=>`<p class="r43-rawparagraph">${esc(p.text||'')}</p>`).join('')}${r43EvidenceLink('builds.json','采集字段')}${safeLink(b.source_url,'该分支原页')}</details>`:'';}
function r43GemName(n){return C43.skillTranslations[n]?C43.skillTranslations[n]+' · '+n:n;}
function r43Skills(b){return `<section class="r43-section"><p class="r43-description">下面是当前网页实际保存的默认连接；临时替换在后面另列。没有明确等级／品质的，不自动填满。</p><div class="r43-skill-groups">${b.skill_gems.groups.map(g=>`<article class="r43-skill" data-skill-captured="${esc(r43GemName(g.active_skill.name))}"><header><b>${esc(r43GemName(g.active_skill.name))}</b><span>${g.active_skill.level?'Lv '+esc(g.active_skill.level):'等级未设置'} · ${esc(g.weapon_set||'未绑定武器组')}</span></header><div class="r43-skill-chain">${g.connected_gems.map(s=>`<span class="${s.gem_type==='SUPPORT'?'':'embedded'}"><small>${s.socket_index}${s.gem_type==='SUPPORT'?' 辅助':' 内嵌主动'}</small>${esc(r43GemName(s.name))}${s.level?' · Lv '+esc(s.level):''}${s.quality?' · '+esc(s.quality)+'%品质':''}</span>`).join('')}</div>${g.configured_quality!==null?`<p>已设品质：${esc(g.configured_quality)}</p>`:''}</article>`).join('')}</div><h2>作者条件与可选替换</h2>${r43List(b.notes.skillNotes)}${r43Prose(b,'Skill Gems')}</section>`;}
function r43Tree(b){const al=b.passive_tree.allocations;return `<section class="r43-section"><div class="r43-panel"><h2>什么时候换到这套？</h2><p>${esc(b.notes.transition)}</p><p>${['e02','e03','e04','e05'].includes(b.stage)?'属性先满足实际装备和技能；作者 161 敏捷后偏力量的建议，不覆盖你实际需要的 163 或更高需求。':'参考树等级不等于必须等到此等级才能用；缺点时按实际需求补强，不从节点记录数量反推等级。'}</p></div><figure class="r43-tree"><img src="${esc(r43Evidence(b.treeImage))}" alt="${esc(b.name)} 本次采集的完整人物天赋截图"><figcaption>${r43ButtonImage(b.treeImage,b.name+' · 人物天赋全图')}<span>图像连线已取得；机器连线、坐标和合法逐级点序仍未取得。</span></figcaption></figure>${b.treePriorities.length?`<h2>作者保存的大点优先列表</h2><p class="r43-description">以下是源中的优先列表，不是逐级、逐点路线；不据编号直接洗点。</p><div class="r43-priorities">${b.treePriorities.map((n,i)=>`<span><small>${i+1}</small>${esc(n.name)}</span>`).join('')}</div>`:''}<details class="r43-proof"><summary>Main / Set 1 / Set 2 / 升华的原始节点记录</summary>${Object.entries(al).map(([k,v])=>`<h4>${esc(k)} · ${v.selected_node_ids?.length||0} 条源记录</h4><p class="r43-node-ids">${esc((v.selected_node_ids||[]).join(', '))}</p>`).join('')}<p>这些不是可用天赋点数。旧 build 的语义ID与当前 node-ID 不直接按字符串相等比较。</p></details>${r43Prose(b,'Passive Tree')}<div class="r43-links">${q42Link('jewels','配套人物珠宝','btn')}${q42Link('gear','回全身装备','btn')}${q42Link('learn/ascendancy','升华获取流程','btn')}</div></section>`;}
character=function(){const b=r43Build();if(!b)return _r42character();const tab=current.params.get('tab')||'skills';if(!['skills','tree'].includes(tab)){const raw=_r42character();return raw.replace('<footer',`<section class="r43-section"><h2>本次原页核对补充</h2>${r43List(b.notes.skillNotes)}</section><footer`);}return r43Head(tab==='tree'?'人物天赋与切换条件':'技能连接与武器组','实际配置、作者可选调整和未核实项分别显示。','character',{tab})+r43Meta(b)+q42Tabs('character',[['skills','默认技能连接'],['tree','天赋与何时切换'],['play','操作与首领'],['check','属性与资源']],tab)+(tab==='tree'?r43Tree(b):r43Skills(b))+footer();};
guide=function(){const b=r43Build();if(!b)return _r42guide();const raw=_r42guide();return `<div class="r43-panel"><b>${esc(b.name)} · ${b.notes.referenceLevel?'作者参考树 '+b.notes.referenceLevel+' 级':'独立只读实装'}</b><p>${esc(b.notes.transition)}</p>${q42Link('character','查看原图、优先列表和切换条件 →','text-link',{tab:'tree'})}</div>`+raw;};
function r43Atlas(id){return C43.atlas.find(v=>v.id===id)||C43.atlas[0];}
function r43Choices(v){const groups=[...new Set(v.keystone_selections.flatMap(x=>x.groups))];return `<div class="r43-panel"><h2>${esc(v.name)} · 作者保存的已选项</h2><p>${v.keystone_selections.length} 条已选绑定；不是旧版的备料建议，也不是候选全集。英文选项原名直接保留，旁边给中文解释。</p><p>采集确认所选值；父节点的完整效果、全部其他候选及解锁条件没有同时取得，不能把下列短描述当作整个节点的全部规则。</p></div><label class="r43-search">查节点或选项<input id="r43-node-query" type="search" placeholder="如 Forest、森林、预兆、Essence…"></label><div class="r43-atlas-rows">${v.keystone_selections.map(x=>`<article class="r43-node" data-r43-node="${esc((x.node_name+' '+x.zhName+' '+x.author_selected.name+' '+x.zhChoice+' '+x.groups.join(' ')).toLowerCase())}"><div><small>${esc(x.groups.join(' / ')||'源记录')}</small><h3>${esc(x.node_name)}</h3>${x.zhName?`<p>${esc(x.zhName)}</p>`:''}<code>${esc(x.node_id)}</code></div><div><span class="r43-label">作者已选</span><b>${esc(x.author_selected.name)}</b><p>${esc(x.zhChoice)}</p><small>${esc(x.author_selected.selection_description)}</small></div></article>`).join('')}</div><p class="r43-no-matches" hidden>没有匹配项。清空搜索可显示该方案所有已选节点。</p>${r43EvidenceLink('atlas.json','全部节点ID与原始绑定')}`;}
function r43Masters(v){return `<div class="r43-panel"><p>只将实际已选图标与保存列表一致的项标为“作者已选”。每位大师的 12 条候选另列，不把候选全部算作生效。</p></div>${v.masters.map(m=>`<section class="r43-section"><h2>${esc(m.name)} · 已选 ${m.selected_count} 项</h2>${m.selected_count===3?'<p class="r43-description">本次实际只有 3 项；没有虚构第 4 项。</p>':''}<div class="r43-grid">${m.candidate_options.filter(x=>x.author_selected).map(o=>`<article class="r43-panel"><span class="r43-label">作者已选</span><h3>${esc(o.name)}</h3>${r43List(o.zhEffects||o.effects)}${r43ButtonImage(o.evidence.find(e=>e.file.endsWith('.jpg'))?.file,m.name+' · '+o.name)}</article>`).join('')}</div><details class="r43-proof"><summary>${m.name} 全部候选（未选的不生效）</summary>${m.candidate_options.map(o=>`<h4>${o.author_selected?'✓ ':''}${esc(o.name)}</h4>${r43List(o.zhEffects||o.effects)}`).join('')}</details></section>`).join('')}`;}
atlasPage=function(id){const v=r43Atlas(id),tab=current.params.get('tab')||'tree';state.variant=v.id;setStore('variant',v.id);if(!['tree','choices','masters'].includes(tab))return _r42atlas(v.id);const tabs=[['tree','加点原图'],['choices','作者大节点选项'],['masters','大师已选与候选'],['setup','地图与碑牌'],['play','操作与减配'],['source','来源记录']];return heading('ATLAS / 作者配置',v.name,'七套是独立刷法，不是人物 build 的升级顺序。')+`<nav class="r43-builds" aria-label="异界方案">${C43.atlas.map(a=>routeLink('atlas/'+a.id,esc(a.name),'r43-build '+(a.id===v.id?'is-active':''),{tab})).join('')}</nav><nav class="c41-tabs">${tabs.map(([t,l])=>routeLink('atlas/'+v.id,l,'c41-tab '+(tab===t?'active':''),{tab:t})).join('')}</nav>`+(tab==='choices'?r43Choices(v):tab==='masters'?r43Masters(v):`<figure class="r43-tree"><img src="${esc(r43Evidence(v.treeImage))}" alt="${esc(v.name)} 本次完整异界树截图"><figcaption>${r43ButtonImage(v.treeImage,v.name+' · 异界树')}<span>保存的图像是视觉证据；不会据其猜测机器连线或逐级点序。</span></figcaption></figure><div class="r43-links">${routeLink('atlas/'+v.id,'直接看大节点选哪项','btn primary',{tab:'choices'})}${routeLink('atlas/'+v.id,'查看大师已选配置','btn',{tab:'masters'})}</div>`)+footer();};
atlasChoices=function(){const p=current.params.get('profile');if(p&&['starter','phys','crit','hybrid','life'].includes(p))return note('<b>以下仍是本站备料建议，不是作者当前方案。</b>作者的实际选择请在各方案“作者大节点选项”查看。',true)+_r42choices();const v=r43Atlas(p||state.variant);const old=current.params.get('tab');current.params.set('tab','choices');const h=atlasPage(v.id);if(old)current.params.set('tab',old);else current.params.delete('tab');return h;};
function r43Audit(){const rows=C43.rawCompare.filter(x=>!x.stored_desc_equal);return heading('核对 / 证据与差异','从原页采集到当前攻略','本次先验证数据与截图，再与 R42 和旧 build 比对；没有修改原文件或过滤器。')+`<div class="r43-kpis"><div><b>91</b><span>装备记录</span></div><div><b>11</b><span>可见珠宝</span></div><div><b>36</b><span>镶嵌孔关联</span></div><div><b>221</b><span>异界已选绑定</span></div></div><section class="r43-section"><h2>哪六件保存描述变了？</h2><p>全部在 Live Gear。其余 85 件保存描述与旧 .build 一致；“保存描述一致”不等于页面全部数值已证明为作者实装。</p>${q42Rows(rows.map(x=>[esc(x.build),esc(x.item),esc(x.old_descriptions.join('；')||'旧文件只保存名称'),esc(x.captured_saved_descriptions.join('；')||'无描述')]),['Build','物品','旧 .build','当前网页保存字段'])}</section><section class="r43-section"><h2>不能静默合并的冲突</h2>${r43List(['Live Gear 弓面板只显示基础伤害，保存字段另有 7 条词缀：分开保留，不自动重算成品。','Live Gear 魔力药剂与第二组武器需求等级的保存值和面板值不同：显示差异，不选择一方抹掉另一方。','Live Gear 第 1、6 颗珠宝有绑定但不在显式已选列表；另有一条未展示绑定。不能把图标数当合法孔数。','装备面板中若出现不符当前部位的 Body Armour / Boots / Gloves 等前缀标签，按原文保留并标记，不据此改装备类别。','机器可读连线、坐标、完整逐级点序、全部 Atlas 候选和父节点完整效果仍未取得。','当前采集属于 2026-10-05 页面快照。参考树等级、保存值、范围、本文翻译与普通工艺建议分层，不覆盖原 build。'])}</section><section class="r43-section"><h2>直接查原始文件</h2><div class="r43-links">${r43EvidenceLink('README.md','采集说明')}${r43EvidenceLink('装备面板全表.md','所有英文面板')}${r43EvidenceLink('缺失与冲突.md','采集缺口')}${r43EvidenceLink('builds.json','人物采集JSON')}${r43EvidenceLink('atlas.json','Atlas采集JSON')}<a class="btn" href="R43_比对与修订说明.md">本轮完整比对与修改说明</a></div></section>`+footer();}
tools=function(kind,params){return kind==='capture-audit'?r43Audit():_r42tools(kind,params);};
coverage=function(){return r43Audit();};
nav=function(group){const sec=current.section;const craft=['early-craft','craft-timing','supplies'].includes(sec)||(sec==='item'&&current.params.get('tab')!=='target'&&current.params.get('tab'));
if(craft)group='craft';else if(['guide','learn','troubleshoot','reference','tools','coverage','filter-guide','filter-check'].includes(sec))group='tools';
const entries=[['gear','gear','装备总览','gear',{},[['gear','全身装备 · 一页看全',{}],['jewels','人物珠宝面板',{}]]],['character','person','人物配置','character',{tab:'tree'},[['character','天赋与何时切换',{tab:'tree'}],['character','默认技能连接',{tab:'skills'}],['character','实战操作',{tab:'play'}],['gems','技能宝石清单',{}],['special-jewels','特殊人物珠宝',{}]]],['atlas','atlas','异界攻略','atlas-choose',{},[['atlas-starter','初入异界',{}],['atlas-choose','七套方案',{}],['atlas/'+state.variant,'作者大节点选项',{tab:'choices'}],['atlas/'+state.variant,'大师配置',{tab:'masters'}]]],['craft','tools','装备打造','early-craft',{},[['early-craft','手里这件，下一步',{}],['craft-timing','什么时候值得做',{}],['item/bow','作者专用弓工艺',{tab:'craft'}],['supplies','材料获取与预留',{}]]],['tools','book','剧情与资料','guide',{},[['guide','本阶段成长任务',{}],['troubleshoot','卡关排查',{}],['learn/permanent','永久奖励',{}],['learn/ascendancy','升华获取',{}],['tools/filters','四份原版过滤器',{}],['tools/capture-audit','本次来源与比对',{}]]]];
$('#main-nav').innerHTML=entries.map(([id,ic,n,r,p,sub])=>q42Link(r,`${icon(ic)}<span>${n}</span>`,'nav-item '+(id===group?'active':''),p)+(id===group?`<div class="subnav">${sub.map(([rr,nn,pp])=>q42Link(rr,nn,(rr===sec+(current.slot?'/'+current.slot:'')?'on':''),pp)).join('')}</div>`:'')).join('');};
// One image control only; never simulate or annotate the original tree.
document.addEventListener('click',e=>{const t=e.target.closest('[data-r43-image]');if(!t)return;const d=$('#image-dialog'),img=$('#modal-image');img.src=t.dataset.r43Image;img.alt=t.dataset.r43Title;$('#image-title').textContent=t.dataset.r43Title;img.style.width='100%';d.showModal();});
document.addEventListener('input',e=>{if(e.target.id!=='r43-node-query')return;const q=e.target.value.toLowerCase().trim();let n=0;$$('[data-r43-node]').forEach(row=>{row.hidden=!row.dataset.r43Node.includes(q);if(!row.hidden)n++;});const hint=$('.r43-no-matches');if(hint)hint.hidden=n>0;});

searchData=function(q){
 const rows=[];
 for(const b of C43.builds){
  rows.push({title:b.name,text:'当前原页整套装备',route:'gear',params:{stage:b.stage},query:b.notes.brief});
  for(const it of b.equipment)rows.push({title:it.name+(it.zhName?' · '+it.zhName:''),text:b.name+' · 完整面板与镶嵌',route:'item/'+it.uid,params:{stage:b.stage,tab:'target'},query:it.panel.modifiers.map(m=>m.text+' '+m.zh).join(' ')+' '+it.socketed_items.map(r=>r.name).join(' ')});
  for(const j of b.jewels)rows.push({title:j.name+(j.zhName?' · '+j.zhName:''),text:b.name+' · 珠宝展示 '+j.display_order,route:'jewels',params:{stage:b.stage},query:j.panel.modifiers.map(m=>m.text+' '+m.zh).join(' ')});
 }
 for(const v of C43.atlas)for(const n of v.keystone_selections)rows.push({title:n.node_name+(n.zhName?' · '+n.zhName:''),text:v.name+' · '+n.zhChoice,route:'atlas/'+v.id,params:{tab:'choices'},query:n.author_selected.name+' '+n.author_selected.selection_description});
 if(!q?.trim())return rows.filter(x=>x.params?.stage===state.stage).slice(0,6);
 const words=q.toLowerCase().trim().split(/\s+/),matched=rows.filter(x=>words.every(w=>(x.title+' '+x.text+' '+(x.query||'')).toLowerCase().includes(w)));
 matched.sort((a,b)=>(b.params?.stage===state.stage?1:0)-(a.params?.stage===state.stage?1:0));
 return [...matched,..._r42search(q)].filter((x,i,a)=>a.findIndex(y=>y.title===x.title&&y.text===x.text&&y.route===x.route)===i).slice(0,24);
};

// Export evidence-layer helpers for deterministic rendering tests.
window.R43={build:r43Build,card:r43Card,capture:C43,search:searchData};
