// R41: explicit crafting states and Atlas selectable bonuses. Original data stays untouched.
const C41=D.craftGuide41,A41=D.atlasChoices41;
function c41Key(s){return ({ring1:'rings',ring2:'rings'})[s]||s;}
function c41Name(s){return D.slots.find(x=>x.id===s)?.name||s;}
function c41Params(extra={}){return {...Object.fromEntries(current.params||[]),...extra};}
function c41Link(label,extra={},cls='btn'){const root=current.section==='early-craft'?'early-craft':'item/'+current.slot;return routeLink(root,label,cls,c41Params({tab:'craft',...extra}));}
function c41Kinds(){return [['unknown','还没选好候选'],['white','白装'],['magic1','蓝装 · 1条词缀'],['magic2','蓝装 · 2条词缀'],['rare2','黄装 · 2条词缀'],['rare3','黄装 · 3条词缀'],['rare4','黄装 · 4条词缀'],['rare5','黄装 · 5条词缀'],['rare6','黄装 · 6条词缀'],['blocked','暗金／腐化／镜像／不明特殊状态']];}
function c41Example(slot,open=false){const x=C41.examples[c41Key(slot)];return x?`<details class="c41-example" ${open?'open':''}><summary>什么时候值得做？${esc(x.title)}</summary><div><p>${esc(x.example)}</p><p>${esc(x.caution)}</p><small>${esc(x.source)}</small></div></details>`:'';}
function c41StageTips(slot,period){const x=C41.examples[c41Key(slot)];let stageTip=period==='pre31'?'剧情31级前：先比较掉落与商店。有用的蓝装可以直接穿；材料没拿到就不为照攻略强行买齐。':period==='post31'?'剧情转冰射后：先把实际技能、属性与供蓝接好。候选能改善当前缺口再加工，不直接套异界高投入配方。':'初入异界与日常补装：先做够用的过渡件。作者进阶弓物等75、护盾头物等78，不是所有精华加工的通用开工门槛。';return `<div class="c41-intro"><b>${esc(x?.next||'按物品类别处理，不套普通装备流程。')}</b><p>${esc(stageTip)}</p></div>`;}
function c41ToolBox(title,tool,doit,result,risk){return `<article class="c41-step"><div class="c41-step-head"><span>这一步</span><h3>${esc(title)}</h3></div><dl><dt>现在用什么</dt><dd class="c41-tool">${esc(tool)}</dd><dt>怎么操作</dt><dd>${esc(doit)}</dd><dt>点完看什么</dt><dd>${esc(result)}</dd><dt>哪里必须停</dt><dd class="c41-risk">${esc(risk)}</dd></dl></article>`;}
function c41Catalog(){return {...D.essenceGuide.catalog,...C41.extraEssences};}
function c41GoalOf(id){if(id.startsWith('damage-'))return id.includes('cold')?'damage-cold':id.includes('fire')?'damage-fire':'damage-lightning';if(id.startsWith('body'))return 'life';if(id.startsWith('enhancement'))return 'defence';if(id.startsWith('abrasion'))return 'physical';if(id.startsWith('haste'))return 'speed';if(id.startsWith('infinite'))return 'attribute';if(id.startsWith('battle'))return 'accuracy';if(id==='seeking')return 'crit';if(id.startsWith('lightning'))return 'lightning';if(id.startsWith('cold'))return 'cold';if(id.startsWith('fire'))return 'fire';if(id.startsWith('chaos'))return 'chaos';return 'other';}
const C41Goals={life:'补生命',physical:'补物理点伤',speed:'补弓攻速',defence:'补本地防御百分比',fire:'补火抗',cold:'补冰抗',lightning:'补电抗',chaos:'补混沌抗性',attribute:'随机补一种属性（不能定向）',accuracy:'补命中',crit:'补本地暴击率','damage-fire':'补火焰点伤（剧情过渡）','damage-cold':'补冰霜点伤（剧情过渡）','damage-lightning':'补闪电点伤（剧情过渡）'};
function c41EssenceChoices(slot,params,kind){const key=c41Key(slot),all=Object.values(c41Catalog()).filter(e=>e.effect?.[key]),groups=[...new Set(all.map(e=>c41GoalOf(e.id)))];const preferred=key==='bow'?'physical':['body','helmet','gloves','boots','amulet','rings','belt'].includes(key)?'life':groups[0];const selected=c41Catalog()[params.get('essence')];let goal=params.get('goal')||(selected&&selected.effect[key]?c41GoalOf(selected.id):preferred);if(!groups.includes(goal))goal=preferred;const es=all.filter(e=>c41GoalOf(e.id)===goal).sort((a,b)=>({lesser:0,normal:1,greater:2}[a.tier]??2)-({lesser:0,normal:1,greater:2}[b.tier]??2));
 const controls=`<div class="c41-goal-select"><label for="c41-goal">这件蓝装缺什么？</label><select class="select" id="c41-goal">${groups.map(g=>`<option value="${g}" ${g===goal?'selected':''}>${esc(C41Goals[g]||g)}</option>`).join('')}</select><span>这是补一条的不同选择，不是要全部使用。</span></div>`;
 return controls+`<div class="c41-essences">${es.map(e=>`<article><div><span class="tag gray">${esc(({lesser:'次级',normal:'普通',greater:'强效'})[e.tier]||'强效')} · ${esc(e.side)}</span><h4>${esc(e.zh)}</h4><p>${esc(e.effect[key])}</p><p class="c41-tier-use"><b>什么时候用：</b>${esc(c41TierUse(e))}</p><small>${esc(c41Limit(e,slot))}</small></div><div class="actions">${c41Link('用这颗：看本次操作',{kind,goal,action:'essence',essence:e.id},'btn primary small')}${safeLink(e.url,'效果依据','text-link')}</div></article>`).join('')}</div><p class="c41-muted">先看手中哪一档能解决缺口，再决定是否花材料。不自动合成最高档；同组词缀冲突、物品不适用或成品穿不了，就不要用。魔法装备的普通容量与特殊例外先看游戏提示。</p>`;}
function c41Generic(slot,params){const key=c41Key(slot),valid=c41Kinds().map(x=>x[0]);let kind=params.get('kind')||'unknown';if(!valid.includes(kind))kind='unknown';const period=params.get('period')||'entry';const n=Number(kind.replace('rare','')),action=params.get('action')||'',e=c41Catalog()[params.get('essence')];let content=c41StageTips(slot,period)+c41Example(slot)+`<div class="c41-state"><label for="c41-kind">手里这件现在是什么状态？</label><select class="select" id="c41-kind">${c41Kinds().map(([id,name])=>`<option value="${id}" ${kind===id?'selected':''}>${name}</option>`).join('')}</select><small>按鉴定后的显性词缀分组计数，不数说明行，不含固有、品质、符文。这里只切换阅读，不读取游戏。</small></div>`;
 const link=(t,q,c)=>c41Link(t,{action:'',essence:'',...q},c);
 const done=link('够用了，查看换上前检查',{action:'done'},'btn');
 if(action==='done'){return content+c41ToolBox('这轮先结束','不再使用加词缀材料','保留旧装，比较新装，再检查实际佩戴需求、抗性、技能与资源。','能解决当前短板才换上；不用为了凑满6条继续投入。','属性或抗性失效就换回旧装。品质、开孔及镶嵌按本部位单独处理。')+`<div class="actions">${current.section==='item'?c41Link('查看本部位品质与镶嵌',{tab:'finish'},'btn primary'):routeLink('item/'+slot,'查看本部位收尾说明（异界快照，需按当前装备判断）','btn',{stage:'e01',tab:'finish'})}${link('返回当前物品状态',{})}</div>`;}
 if(kind==='blocked')return content+note('<b>这里停止。</b>普通蜕变、增幅、富豪和精华升黄流程不适用于此状态。先识别物品；不要用同名部位的普通配方试暗金、腐化、镜像或不明半成品。',true);
 if(kind==='unknown')return content+c41ToolBox('先选候选，不急着花材料','先不使用材料','先比较可以穿的掉落、商店和已有装备；有合格蓝装／黄装就从其当前状态开始，不必重做白装。',C41.examples[key]?.next||'先核对对应物品目标。','候选底材方向不对、失去关键移速／抗性、或唯一现用品不能承担失败，就先不做。')+`<div class="actions">${link('找到白装候选',{kind:'white'})}${link('找到一词好蓝装',{kind:'magic1'},'btn primary')}${link('找到两词好蓝装',{kind:'magic2'})}</div>`;
 if(kind==='white')return content+c41ToolBox('白装先试一次蜕变','普通蜕变石 ×1','确认是备用、已核对佩戴需求的普通装备。右键蜕变石，再左键候选一次。','变成蓝装后读取实际词缀；有用再继续，无用先换候选。','蜕变不保证有用词缀；白装不能直接按此流程使用升黄精华。不因已经花过一颗就继续追。')+`<div class="actions">${link('得到1条有用词缀',{kind:'magic1'},'btn primary')}${link('结果不好，重新找候选',{kind:'unknown'})}${done}</div>`;
 if(kind==='magic1'||kind==='magic2'){
  const count=kind==='magic1'?1:2;
  if(action==='aug'&&count===1)return content+c41ToolBox('可选：先随机补蓝装第二条','普通增幅石 ×1','只有原来一条值得保留、且接受随机第二条时才用。右键增幅，再点备用蓝装一次。','仍是蓝装，重新看两条是否值得保留。','增幅不是精华的必要前置；新增不合用就停，不自动用混沌或剥离。')+`<div class="actions">${link('现在是2条蓝装，检查下一步',{kind:'magic2'},'btn primary')}${done}</div>`;
  if(action==='regal')return content+c41ToolBox('明确不走精华：富豪升黄一次','普通富豪石 ×1','保留这件蓝装现有词缀，接受随机新增一条。右键富豪，再左键备用蓝装一次。',`${count}条蓝装变为${count+1}条普通黄装；新增词缀随机，原有词缀保留。`,'富豪与升黄精华二选一；升黄之后，不再点次级、普通、强效升黄精华。')+`<div class="actions">${link(`现在黄装${count+1}条，先看是否够用`,{kind:'rare'+(count+1)},'btn primary')}${done}</div>`;
  if(action==='essence'){
   if(!e?.effect?.[key])return content+note('所选精华不适用于当前部位；没有生成使用步骤。请重新按缺口选择。',true)+c41EssenceChoices(slot,params,kind);
   return content+c41ToolBox('使用选定精华，只升黄一次',e.zh+' ×1',`先核对${e.side}空位、没有同组冲突、成品能穿与游戏使用提示。右键【${e.zh}】，再左键备用蓝装一次；不要先点富豪。`,`${e.effect[key]}。正常新增这一条，${count}条蓝装变为${count+1}条普通黄装；读实际结果再继续。`,c41Limit(e,slot)+' 已升黄就停止此精华分支，不能再接另一颗升黄精华。')+`<div class="actions">${link(`用完：黄装${count+1}条，先验收`,{kind:'rare'+(count+1)},'btn primary')}${link('先不使用，返回选择',{})}${safeLink(e.url,'核对这颗精华的效果','text-link')}</div>`;
  }
  return content+`<div class="c41-section-heading"><span>蓝装先决定一件事</span><h3>定向补缺用精华；接受随机结果才用富豪。</h3><p>原有${count}条是否有用先确认。${count===1?'可以直接比较精华，不强迫先增幅。':'两条都合适，也可以先穿，不强迫升黄。'}</p></div>`+c41EssenceChoices(slot,params,kind)+`<div class="c41-alternatives"><b>没有合适精华，不必硬用</b><div class="actions">${link('接受随机结果：用富豪',{action:'regal'},'btn')}${count===1?link('可选：先用增幅补第2条',{action:'aug'}):''}${done}</div></div>`;
 }
 if(kind.startsWith('rare')&&n>=2&&n<=6){
  if(action==='exalt'&&n<6)return content+c41ToolBox(`只补第${n+1}条，不连点`,'普通崇高石 ×1','先确认普通装备尚有合法空位、需要的属性还能生成、没有给后续精华替换／渎灵预留位置；没有激活会改变本次添加的预兆。右键普通崇高石，再左键备用黄装一次。',`正常从${n}条变${n+1}条；新增随机属性，不是提高原有数值，也不保证补到想要的属性。`,'目标侧已满、工艺还有保留条件或预算不接受时停止。新增不好不等于原有好词缀消失，不自动用混沌／剥离删改。')+`<div class="actions">${link(`点完：重新检查${n+1}条黄装`,{kind:'rare'+(n+1)},'btn primary')}${done}</div>`;
  return content+c41ToolBox(`黄装${n}条：先比较，够用就停`,'先不消耗材料',`检查${n}条实际显性词缀及前后缀分组。对照本部位要保住的属性；能解决当前短板就直接收尾。`,n===6?'普通容量已满；“6条”不代表6条都有效，更不代表毕业。':'词缀少不等于不能用；继续投入只是可选，不要求每件凑6条。',n===6?'不再用普通崇高；不要在唯一现用品上盲目删改。':'只有目标侧还有空位、没有后续预留且接受随机结果，才看一次崇高添加。')+`<div class="actions">${done}${n<6?link(`确认空位与预算，再看补第${n+1}条`,{action:'exalt'},'btn primary'):''}${link('状态不对，重新选候选',{kind:'unknown'})}</div>`;
 }
 return content;
}
function c41StepTools(r,s){
 if(s.materials?.length)return s.materials.map(materialName).join(s.materialMode==='one-of'?' 或 ':' ＋ ');
 if(s.id==='ready'&&['bow-crit','bow-noncrit'].includes(r.id))return '两词合格蓝弓：不用材料；只有一条物理提高前缀：普通增幅石 ×1（先补后缀）';
 if(s.id==='ready'&&r.id==='helmet-stable')return '已是合格两词蓝头：不用材料；只有平铺护盾一条：增幅石 ×1（先补后缀）';
 if(s.id==='ready'&&r.id==='quiver-standard')return '已有合格蓝箭袋：不用材料；自己从白底找：作者用高级／完美蜕变与增幅，按各自物品状态分别用';
 if(s.id==='ready'&&r.id.startsWith('early-'))return '先不消耗；未鉴定时先用知识卷轴，其他材料在下面对应步骤使用';
 if(s.id==='reveal')return '灵魂之井；深渊回响预兆仅可选，必须在本次显现之前准备';
 if(['finish','check'].includes(s.id))return '先不追加词缀；决定保留后，再按本部位选择品质与镶嵌材料';
 return '这一步先核对，不默认使用耗材';
}
function c41Limit(e,slot){const k=c41Key(slot),g=c41GoalOf(e.id);if(e.id.startsWith('damage-'))return '数据掉落等级25；不要求16级就有。先确认技能能利用这类伤害，且没有同组冲突。';if(g==='life')return '保留现有好词缀；已有同组生命或目标前缀没有空位时，不盲用。'+(k==='rings'?'戒指不使用强效身躯。':'');if(g==='defence')return '只提高底材已有的本地防御；不能在没有护盾基础的底材上凭空做出护盾。';if(g==='attribute')return '力量／敏捷／智慧结果不由你指定。缺指定智慧时，先找已有智慧的候选。';if(g==='physical')return '补物理点伤，不补物理伤害百分比；已有同组点伤时先检查冲突。';if(g==='crit')return '补本地暴击率。作者暴击弓还需物理提高蓝底和后续预留，不能只点这颗就当转型完成。';return '只补上面这一条效果；先检查同组冲突、前后缀空位和实际佩戴需求。';}
function c41TierUse(e){return ({lesser:'短期过渡，补这一档数值就能用时。',normal:'候选值得继续穿，但次级给的数值仍不够时。',greater:'底材值得留、确有数值需求且预算能承担时；不默认给临时件用。'})[e.tier]||'按具体配方与物品资格核对。';}
function c41Advanced(r,slot,params){let id=params.get('step')||r.steps[0]?.id;const s=r.steps.find(x=>x.id===id)||r.steps[0];if(!s)return note('这条路线没有完整步骤；不要套用其他部位材料。',true);const refs=[...new Set([...(s.refs||[]),...(C41.sources.slice(1,2))])];
 const required=c41StepTools(r,s);
 let html=`<div class="c41-recipe-intro"><span class="tag">${esc(r.sourceLabel||'既有作者路线')}</span><h3>${esc(r.title)}</h3><p><b>开工条件：</b>${esc(r.start)} ${esc(r.prerequisite||'')}</p><p><b>这条路线要做成：</b>${esc(r.goal)}</p><small>这是一条专用路线，不和临时过渡件混用。不是按材料档位从低到高依次点。</small></div>`;
 if(r.readonly)return html+note('<b>仅对照，不提供执行：</b>'+esc(r.warning||r.prerequisite||'尚缺可靠的执行前提。'),true)+expand('阅读原始步骤（不解锁为可执行）',r.steps.map(x=>`<p><b>${esc(x.title)}</b>：${esc(x.before)}</p>`).join(''));
 html+=`<div class="c41-state"><label for="c41-advanced-step">我在这条配方的哪一步？</label><select id="c41-advanced-step" class="select">${r.steps.map(x=>`<option value="${esc(x.id)}" ${x.id===s.id?'selected':''}>${esc(x.title)}</option>`).join('')}</select></div><article class="c41-step" data-recipe-id="${esc(r.id)}" data-step-id="${esc(s.id)}"><div class="c41-step-head"><span>当前操作</span><h3>${esc(s.title)}</h3></div><dl><dt>动手前</dt><dd>${esc(s.before)}</dd><dt>现在用什么</dt><dd class="c41-tool">${esc(required)}</dd><dt>怎么操作</dt><dd>${(s.action||[]).map(x=>`<p>${esc(x)}</p>`).join('')}</dd><dt>点完看什么</dt><dd>${esc(s.expect)}<p>${esc(s.good)}</p></dd><dt>不符合时</dt><dd class="c41-risk">${esc(s.bad)}</dd></dl></article>`;
 const next=s.next&&r.steps.find(x=>x.id===s.next);const choices=(s.choices||[]).filter(c=>r.steps.some(x=>x.id===c.id));html+=`<div class="c41-advance"><p>先在游戏里核对实际结果，再选择下一步。下面的按钮不代表结果已自动验收。</p><div class="actions">${next?c41Link('结果符合，查看：'+esc(next.title),{route:r.id,step:next.id,kind:'',action:'',essence:''},'btn primary'):''}${choices.map(c=>c41Link(esc(c.label),{route:r.id,step:c.id,kind:'',action:'',essence:''})).join('')}${c41Link('先停手，查看换上前检查',{tab:'finish',route:r.id},'btn')}</div></div>`;
 html+=expand('只预览这条配方的全程顺序，不一次照表连点',`<ol class="c41-roadmap">${r.steps.filter(x=>!['bad-roll','single-four','single-five','finish-perfect','suffix-double'].includes(x.id)).map(x=>`<li><b>${esc(x.title)}</b><span>${esc(x.expect)}</span></li>`).join('')}</ol>`)+expand('本步依据与补充说明',`<p>${esc(s.note||'')}</p>${refs.map((u,i)=>safeLink(u,'来源 '+(i+1),'text-link')).join('　')}`);return html;
}
function fullTargetPanel(it,slot){let raw=fullTargetPanelOld41(it,slot);return raw.replace(/<button\b[^>]*data-scroll="item-craft"[^>]*>[\s\S]*?<\/button>/g,routeLink('item/'+slot,phase().readonly?'查看只读限制':'这件怎么做 →','btn small',{stage:state.stage,tab:'craft'}));}
function c41CraftBody(slot,params){const it=findItem(slot),key=c41Key(slot),ordinary=Object.hasOwn(C41.examples,key),isUnique=uniqueTarget(it,slot),alt=params.get('alternate')==='rare',independent=params.get('independent')==='1';if(phase().readonly)return note('06只读：保留原件，不生成耗材操作，不以本页指导重做或改树。',true);
 if(isUnique&&!alt)return note('<b>目标是暗金，不是用精华把普通底材做出来。</b>'+esc(it?.acquire||'查看该物品的已核对来源；未确认来源不承诺必出。')+' '+c41Link('只看普通／稀有替代件',{alternate:'rare',route:'early-'+key,step:'',kind:'unknown'},'btn small'),true);
 if(['weapon2','quiver2'].includes(slot)&&!independent)return note('先确认该武器组是否共享主手。没有独立原件时，不复制主手目标和耗材。'+c41Link('确实另做独立副装备，再看原有说明',{independent:'1'},'text-link'));
 let rr=recipeRoute(it,slot,params.get('route'),alt,independent),options=[...rr.options];if(ordinary&&!options.some(r=>r.id==='early-'+key)){const base=D.routes.find(r=>r.id==='early-'+key);if(base)options.unshift(normalRecipe(base));}
 const selected=options.find(r=>r.id===params.get('route'))||rr.selected||options[0];
 if(!selected)return note(esc(it?.acquire||finishPlan(slot)?.why||'本类物品没有普通装备升黄配方；先核对类型。'));
 let html=`<div class="c41-route"><label for="c41-route">这次要做哪一种？</label><select class="select" id="c41-route">${options.map(r=>`<option value="${esc(r.id)}" ${r.id===selected.id?'selected':''}>${esc(r.id.startsWith('early-')?'先做能用的过渡件 · '+c41Name(slot):r.title)}${r.readonly?'（只读）':''}</option>`).join('')}</select></div>`;
 if(alt)html+=note('<b>当前做的是普通／稀有替代件，不是上方暗金目标。</b>精华不会把它变成该暗金。',true);
 if(selected.id.startsWith('early-')&&ordinary){html+=`<p class="c41-source">普通过渡流程 · 本站操作补充${['e03','e04','e05'].includes(state.stage)?'；这不是上方高配目标的完整成品配方':''}</p>`+c41Generic(slot,params);}
 else html+=c41Advanced(selected,slot,params);
 return html;
}
function itemPage(slot,params){if(!D.slots.some(x=>x.id===slot))return note('没有这个装备部位；请返回全身目标。',true)+routeLink('gear','返回全身目标','btn',{stage:state.stage});const p=phase(),it=findItem(slot),f=finishPlan(slot),ind=params.get('independent')==='1';let tab=params.get('tab')||'target';if(['plan','steps'].includes(tab))tab='craft';if(!['target','craft','finish'].includes(tab))tab='target';const opts={...Object.fromEntries(params),stage:state.stage};let html=heading('EQUIPMENT / '+esc(c41Name(slot)),esc(it?.name||c41Name(slot)),esc(labelStage(p))+' · 先看目标，再按实际状态做。',true)+`<div class="split c41-back">${routeLink('gear','← 全身装备目标','text-link',{stage:state.stage})}<div><label for="item-select">切换部位 </label><select class="select" id="item-select">${D.slots.map(s=>`<option value="${s.id}" ${s.id===slot?'selected':''}>${esc(s.name)}</option>`).join('')}</select></div></div><nav class="c41-tabs" aria-label="装备阅读步骤">${[['target','装备目标'],['craft','一步步做'],['finish','换上前检查']].map(([id,t])=>routeLink('item/'+slot,t,'c41-tab '+(id===tab?'active':''),{...opts,tab:id})).join('')}</nav><div class="c41-workspace" data-tab="${tab}">`;
 if(tab==='target'){html+=sec('item-target','01','这件装备要什么属性',fullTargetPanel(it,slot)+targetContext(it,slot),'',true);if(slot==='jewels')html+=j39Bridge();}
 else if(tab==='craft')html+=c41CraftBody(slot,params);
 else{html+=sec('item-finish','03','决定保留后，再看品质、开孔与镶嵌',finishRows(f,slot,ind));if(f?.alternatives?.length)html+=expand('首选材料没有时',f.alternatives.map(x=>`<p>${esc(x)}</p>`).join(''));html+=sec('item-check','04','换上前最后检查',checksHtml([...(it?.success?[it.success]:[]),...(f?.checks||[]),'先扣除旧装备给的属性，再确认新装备能穿、技能能用。','保留旧装；用同档低投入内容比较，不把词缀数量当伤害保证。'],state.stage+'-'+slot,p.readonly));if(f?.avoid?.length)html+=expand('本部位的特殊限制',f.avoid.map(x=>`<p>${esc(x)}</p>`).join(''));}
 return html+'</div>'+footer();}
function earlyCraft(){const p=current.params,slot=D.slots.some(s=>s.id===p.get('slot')&&s.group==='main')?p.get('slot'):'bow';let period=p.get('period')||'pre31';if(period==='campaign')period='pre31';const cp=new URLSearchParams(p);cp.set('period',period);return heading('CRAFT / 剧情与日常补装','手里这件，下一步怎么做','不要求从白装做起，也不要求每件凑满6条。精华、富豪与崇高在实际用到的步骤里出现。')+`<div class="c41-route"><label for="c41-period">当前进度</label><select class="select" id="c41-period">${[['pre31','剧情 · 31级前过渡'],['post31','剧情 · 转冰射后'],['entry','异界起步／日常补装']].map(([v,l])=>`<option value="${v}" ${v===period?'selected':''}>${l}</option>`).join('')}</select><label for="c41-slot">部位</label><select class="select" id="c41-slot">${D.slots.filter(s=>s.group==='main').map(s=>`<option value="${s.id}" ${s.id===slot?'selected':''}>${esc(s.name)}</option>`).join('')}</select></div>`+c41Generic(slot,cp)+`<div class="c41-alternatives"><b>已准备作者进阶工艺的起点？</b><p>这里是普通补一条流程，不替代暴击弓、护盾头、固定＋3项链等专用工艺。</p>${routeLink('item/'+slot,'到本部位查看当前阶段专用配方','btn',{stage:state.stage,tab:'craft'})}</div>`+footer();}
function craftTiming(){const slot=C41.examples[c41Key(current.params.get('slot'))]?current.params.get('slot'):'bow';return heading('CRAFT / 做不做，先这样比较','什么时候值得做装备','不是让你先回答“知道能提升”，而是直接用当前部位的例子判断。',true)+`<div class="c41-route"><label for="c41-example-slot">比较哪件？</label><select class="select" id="c41-example-slot">${D.slots.filter(x=>x.group==='main').map(s=>`<option value="${s.id}" ${s.id===slot?'selected':''}>${esc(s.name)}</option>`).join('')}</select></div>`+c41Example(slot,true)+`<div class="c41-decision-cases"><article><b>候选只是颜色／等级更高</b><p>先不做。先说得出它保住或改善了哪条当前有效属性；“黄装更多词”不等于更好。</p></article><article><b>保住了关键属性，只差一条</b><p>在备用件上看一次定向精华或随机补词。用完就比较，不为了已经花过材料继续追。</p></article><article><b>已经要走作者专用配方</b><p>先核对那条配方的起点、保留词缀、后续预留和配套；没有准备好就继续用上一件。</p></article></div><div class="actions">${routeLink('item/'+slot,'看本阶段完整目标与专用路线','btn primary',{stage:state.stage,tab:'craft'})}${routeLink('early-craft','剧情／普通补装，按手中状态走','btn',{slot,period:current.params.get('period')||'pre31'})}</div>`+footer();}
function r40Links(rows,cls='btn small'){return rows.map(([r,n])=>routeLink(r,esc(n),cls,n.includes('01整套')?{stage:'e01'}:['gear','character','gems','jewels','special-jewels','special-gems'].includes(r)?{stage:state.stage}:{})).join('');}
function r40AfterRender(){} // R40's removed step-table scroll no longer applies.
function a41Profile(id){return A41.profiles.find(p=>p.id===id)||A41.profiles[0];}
function a41DefaultGroup(id){return ['phys','crit','hybrid'].includes(id)?'material':id==='ritual-belts'?'ritual':id==='breach-rares'?'breach':['currency-abyss','abyss-rares','lineage-gems'].includes(id)?'abyss':id==='expedition'?'expedition':id==='deli-rush'?'delirium':'common';}
function a41Pick(n,p){return n.profiles[p]??n.pick;}
function a41Reason(n,p){const changed=Object.hasOwn(n.profiles,p);if(!changed)return n.why;
 if(n.id==='essence'&&p==='crit')return '寻觅不在这个节点里。这里先为其他普通装备补生命选择身躯；暴击弓必用的寻觅组请看下面“水晶纹样”。这不是暴击弓的第二颗升黄精华。';
 if(n.id==='essence'&&p==='hybrid')return '正在准备护盾头：改强化／增强组，配合作者护盾头所需强效增强精华；不是增加角色护盾的节点。';
 if(n.id==='crystal'&&p==='crit')return '正在准备作者暴击弓：这里选寻觅组，目标是强效寻觅。非暴击弓的磨蚀由“精华探源”选择，不在这个节点内。';
 if(n.id==='forest'&&p==='lineage-gems')return '目标是血脉辅助，明确选血脉辅助掉落几率；不要选未切割宝石或误认为人物天赋珠宝。';
 if(n.id==='abyss-treasure'&&p==='lineage-gems')return '血脉辅助策略选血脉辅助，不是预兆或深渊之眼。该项增加相应掉落几率，不保证某一颗。';
 if(n.id==='exp-expand')return '成型先祖秘藏方案有对应碑牌保证遭遇时，比较额外维金残片。没有保证遭遇条件时改先祖秘藏出现率。';
 if(n.id==='exile')return '正在找护盾头等智慧需求底材，选择智慧需求装备；不是直接给人物加智慧。';
 return '针对所选成熟刷怪目标作出的补充选择；先满足该方案配套并稳定清图，不能承受额外难度时退回起步选项。';}
function a41Body(profileId,groupId){const p=a41Profile(profileId),group=A41.groups.some(g=>g.id===groupId)?groupId:a41DefaultGroup(p.id);let nodes=A41.nodes.filter(n=>n.group===group);return `<div class="a41-heading"><span class="tag">树里的多选大节点</span><h2>点亮之后，还要选这一项</h2><p>先找到同名大节点，打开选项，再对照下面的文字选择。只看你已经解锁的节点；选项不是同时获得，也不是人物属性点。</p></div><div class="a41-boundary"><b>本表是补充选择建议，不是作者逐项实装。</b><span>${esc(A41.boundary)}</span></div><div class="a41-controls"><label for="a41-profile">现在准备什么／刷什么？</label><select class="select" id="a41-profile">${A41.profiles.map(v=>`<option value="${v.id}" ${v.id===p.id?'selected':''}>${esc(v.name)}</option>`).join('')}</select></div><nav class="c41-tabs a41-groups" aria-label="异界节点类别">${A41.groups.map(g=>routeLink('atlas-choices',g.name,'c41-tab '+(group===g.id?'active':''),{profile:p.id,group:g.id})).join('')}</nav><div class="a41-rows">${nodes.map(n=>`<article class="a41-row" data-atlas-node="${n.id}"><div class="a41-name"><h3>${esc(n.name)}</h3><small>${esc(n.gate)}</small></div><div><div class="a41-pick"><span>本页建议选</span><b>${esc(n.options[a41Pick(n,p.id)])}</b></div><p>${esc(a41Reason(n,p.id))}</p><details><summary>什么时候换另一项？其他选项是什么？</summary><p>${esc(n.change)}</p><ul>${n.options.map((o,i)=>`<li${i===a41Pick(n,p.id)?' class="a41-current"':''}>${esc(o)}${i===a41Pick(n,p.id)?' ← 当前建议':''}</li>`).join('')}</ul><p class="small">同一节点内的选项互斥；“几率提高”不是相同数值的最终掉率。</p></details></div></article>`).join('')}</div><div class="a41-foot"><p><b>先点位，后选项：</b>未解锁就继续原有任务；不是为了这张表跳过解锁或凭空多点天赋。地貌加成仅在对应地貌和要求等级生效。顶部大师仍按原方案单独配置。</p><div class="actions">${safeLink(A41.source,'节点选项与解锁条件依据','text-link')}${safeLink(A41.official,'官方多选节点说明','text-link')}${PACKAGED?'<a class="text-link" href="R41_异界大节点选择说明.md" download>下载这张选择说明</a>':''}</div><small>核对日期：${esc(A41.checked)} · ${esc(A41.scope)} · 不读游戏状态、不伪造节点坐标或作者选值。</small></div>`;}
function atlasChoices(){const p=a41Profile(current.params.get('profile'));return heading('ATLAS / 大节点选项','异界大节点：具体选什么','主树、地貌与玩法树的选项分开；不是顶部大师，也不是人物天赋珠宝。')+`<div class="actions c41-back">${routeLink('atlas-starter','← 开荒推进与原图','text-link')}${D.variants.some(v=>v.id===p.id)?routeLink('atlas/'+p.id,'← 当前成型方案原图与配套','text-link'):routeLink('atlas-choose','七套成熟刷法','text-link')}</div>`+a41Body(p.id,current.params.get('group'))+footer();}
function atlasPage(id){const raw=atlasPageR40(id),t=document.createElement('template');t.innerHTML=raw;const wrap=t.content.querySelector('.content-with-toc');if(!wrap)return raw;const profile=D.variants.some(x=>x.id===id)?id:state.variant;let tab=current.params.get('tab')||'tree';const tabs=[['tree','加点原图'],['choices','大节点选哪项'],['masters','大师配置'],['setup','地图与碑牌'],['play','操作与减配'],['source','来源记录']];if(!tabs.some(x=>x[0]===tab))tab='tree';const get=id=>wrap.querySelector('#'+id)?.outerHTML||'';let body=tab==='tree'?get('atlas-tree'):tab==='choices'?a41Body(profile,current.params.get('group')):tab==='masters'?get('atlas-masters'):tab==='setup'?get('atlas-setup'):tab==='play'?get('atlas-play')+get('atlas-budget'):get('atlas-source');if(tab==='tree')body=`<div class="a41-bridge"><b>亮点图只告诉你点哪里；多选大节点还要打开后选具体加成。</b>${routeLink('atlas/'+profile,'看这套目标下的大节点选择建议 →','btn primary',{tab:'choices'})}</div>`+body;const holder=document.createElement('div');holder.className='a41-workspace';holder.innerHTML=`<nav class="c41-tabs">${tabs.map(([v,l])=>routeLink('atlas/'+profile,l,'c41-tab '+(v===tab?'active':''),{tab:v})).join('')}</nav>`+body;wrap.replaceWith(holder);return t.innerHTML;}
function atlasStarter(){const raw=atlasStarterR40(),t=document.createElement('template');t.innerHTML=raw;const wrap=t.content.querySelector('.content-with-toc');if(!wrap)return raw;const tab=current.params.get('tab')||'route';const get=id=>wrap.querySelector('#'+id)?.outerHTML||'';const holder=document.createElement('div');holder.className='a41-workspace';holder.innerHTML=`<nav class="c41-tabs">${[['route','开荒推进'],['tree','分阶段原图'],['choices','大节点选哪项'],['rules','规则与转型']].map(([v,l])=>routeLink('atlas-starter',l,'c41-tab '+(v===tab?'active':''),{tab:v})).join('')}</nav>`+(tab==='tree'?`<div class="a41-bridge"><b>原图未展开选项，不能据此猜作者选择。</b>${routeLink('atlas-starter','查看大节点的补充选择建议','btn primary',{tab:'choices'})}</div>`+get('starter-tree'):tab==='choices'?a41Body(current.params.get('profile')||'starter',current.params.get('group')):tab==='rules'?get('starter-rules')+get('starter-next'):get('starter-route')+`<div class="actions">${routeLink('atlas-starter','下一步：看分阶段原图','btn',{tab:'tree'})}${routeLink('atlas-starter','大节点已经点亮？直接看选项','btn primary',{tab:'choices'})}</div>`);wrap.replaceWith(holder);return t.innerHTML;}
function filterDownloadPage(){return heading('FILTERS / 原版文件','只使用已保存的四份原版','保持原文件字节，不改颜色、声音、底材、碎片或金币规则。这里的原版是已保存的作者快照，不冒充当前在线最新版。')+`<div class="panel fg-downloads">${[['02','剧情','弓系剧情原版'],['01','初入异界','异界起步原版'],['03','后期刷图','准备减少普通物品拾取后按需使用'],['04','超严格','不作为新手默认；先核对所需材料是否被隐藏']].map(([k,n,d])=>`<div class="fg-download-row"><span class="fg-step">${k}</span><div><h3>${n} · 原版</h3><p>${d}</p><code>${esc(fgData().files[k].name)}</code><small class="c41-hash">SHA-256 ${esc(fgData().files[k].sha256)}</small></div><div class="fg-download-actions">${fgFileLink(k,'下载'+k+'原版')}${routeLink('filter-guide','看该原版颜色与声音','text-link',{f:k})}</div></div>`).join('')}</div>`+note('<b>一次只启用一份。</b>网站不会替你切换游戏里正在用的过滤器。请按完整文件名选择，不要选带 GoldFix、Bases_Shards 或 Materials 的旧派生版。')+expand('旧补充版与金币修正怎么处理？','<p>旧包里的派生文件只保留为历史，不再在此推荐或作为默认下载。它们不是原版。切回01原版后，部分底材、碎片和金币会恢复作者的原筛选行为；本次不会另加显示规则。</p>')+`<div class="actions">${routeLink('filter-check','按01原版查显示／隐藏','btn',{f:'01'})}${routeLink('filter-guide','按01原版查完整提示','btn',{f:'01'})}</div>`+footer();}
function fgSelect(k){return `<label>正在看哪份原版<select id="fg-file">${['02','01','03','04'].map(i=>`<option value="${i}" ${k===i?'selected':''}>${esc(fgData().files[i].title)}</option>`).join('')}</select></label>`;}
function filterGuidePage(params){const p=new URLSearchParams(params),historical=!['01','02','03','04'].includes(p.get('f')||'01');if(historical)p.set('f','01');return (historical?note('此旧链接指向派生版。按你只用原版的要求，这里明确切到01原版；原文件没有被编辑。',true):'')+filterGuidePageR40(p);}
function filterCheckPage(params){const p=new URLSearchParams(params),historical=!['01','02','03','04'].includes(p.get('f')||'01');if(historical)p.set('f','01');return (historical?note('此旧链接指向派生版；当前明确按01原版查询，不沿用其放宽规则。',true):'')+filterCheckPageR40(p);}
function nav(group){const info=[['guide','book','成长路线','guide'],['gear','gear','装备与打造','gear'],['character','person','人物配置','character'],['atlas','atlas','异界与产出','atlas-starter'],['tools','tools','查询与下载','tools']];const entries={guide:[['guide','按推进阶段阅读'],['troubleshoot','卡关与故障排查'],['learn/permanent','永久奖励与升华']],gear:[['gear','全身装备目标'],['early-craft','手里这件，下一步怎么做'],['craft-timing','值得做吗？看比较例子'],['supplies','底材与材料从哪里来']],character:[['character','技能与人物天赋'],['jewels','人物天赋珠宝'],['gems','技能／辅助宝石'],['learn/ascendancy','升华与试炼']],atlas:[['atlas-starter','开荒推进与原图'],['atlas-choices','大节点选什么'],['atlas-choose','七套成型刷法'],['learn/map-run','地图风险与推进']],tools:[['tools','资料目录与原件'],['tools/filters','四份原版过滤器'],['filter-guide','原版颜色与声音'],['filter-check','原版显示／隐藏'],['coverage','覆盖与未核实事项']]};$('#main-nav').innerHTML=info.map(([id,ic,n,r])=>routeLink(r,`${icon(ic,17)}<span>${n}</span>`,'nav-item '+(id===group?'active':''),['gear','character'].includes(r)?{stage:state.stage}:{})+(id===group?`<div class="subnav">${entries[id].map(([r,n])=>routeLink(r,n,((r===current.section||r===current.section+'/'+current.slot)?'on':''),['gear','character','jewels','gems','craft-timing'].includes(r)?{stage:state.stage}:{})).join('')}</div>`:'')).join('');}
function r40SearchEntries(){return [{title:'手里这件，下一步怎么做',text:'按白装、蓝装、黄装状态；材料只在本步出现',route:'early-craft',query:'前期 精华 次级 剧情 新手 蓝装 两条 黄装 三条 崇高 富豪 打造'}, {title:'什么时候值得做：各部位比较例子',text:'先减旧装备属性，再比较新装备；不是估价器',route:'craft-timing',params:{stage:state.stage},query:'什么时候 时机 等级 75 16 预算 停手 打造 投入 材料'}, ...A41.nodes.map(n=>({title:n.name+'：选哪一项',text:'异界大节点 · '+n.options[n.pick],route:'atlas-choices',params:{group:n.group},query:n.options.join(' ')+' 大点 属性 选项 加成'})),{title:'四份原版过滤器（不修改）',route:'tools/filters',text:'原版快照与完整哈希',query:'原版 过滤器 声音 颜色 底材 金币 修改'}];}
document.addEventListener('change',e=>{const id=e.target.id,v=e.target.value;if(id==='c41-kind')navigate(current.section==='early-craft'?'early-craft':'item/'+current.slot,c41Params({kind:v,action:'',essence:'',tab:'craft'}));else if(id==='c41-goal')navigate(current.section==='early-craft'?'early-craft':'item/'+current.slot,c41Params({goal:v,action:'',essence:'',tab:'craft'}));else if(id==='c41-route')navigate('item/'+current.slot,{stage:state.stage,tab:'craft',route:v,kind:'unknown',...(current.params.get('alternate')?{alternate:'rare'}:{}),...(current.params.get('independent')?{independent:'1'}:{})});else if(id==='c41-advanced-step')navigate('item/'+current.slot,c41Params({step:v,tab:'craft'}));else if(id==='c41-slot')navigate('early-craft',{slot:v,period:current.params.get('period')||'pre31',kind:'unknown'});else if(id==='c41-period')navigate('early-craft',c41Params({period:v,kind:'unknown',action:'',essence:'',goal:''}));else if(id==='c41-example-slot')navigate('craft-timing',{stage:state.stage,slot:v,period:current.params.get('period')||''});else if(id==='a41-profile')navigate('atlas-choices',{profile:v,group:a41DefaultGroup(v)});});
function fgFileLink(k,label='下载'){const f=fgData().files[k];if(!f)return '';if(!['01','02','03','04'].includes(k))return '<span class="small muted">历史派生版，不作为原版下载</span>';return `<a class="btn small" href="${esc('原版过滤器_从这里选/'+f.name)}" download="${esc(f.name)}">${label}</a>`;}
function coverage(){return heading('REVIEW / 当前边界','本轮改了什么，哪些仍未完成','R41：把材料放回操作步骤；补异界多选大节点。历史版本的检查数量不代表当前流程已全部验收。')+`<div class="panel panel-inner"><h3>本轮直接修复</h3><p>目标按钮切换至同部位、同阶段的“一步步做”；明确的01入口固定去01；作者专用配方与普通补装分离；蓝1→黄2→可选补第三条接齐；普通各部位添加比较示例；前期弓加入可用的元素点伤候选。</p><p>异界新增30个多选大节点的效果与目标导向选择建议，分组阅读。作者截图没展开的选值仍不能当作者实装。四份原版过滤器在独立目录提供；现有原始规则没有修改。</p><h3>仍不宣称完成</h3><p>完整人物天赋动态连线与合法逐级点序、06实装冲突、部分高风险工艺前提、所有普通辅助最低刻印Tier、全套剧情技能线的单页整合、国服逐字名称和游戏实测。三张Lazy开荒图仍依赖网络。</p><p>本轮没有作者七套方案全部大点选值的结构化原件；不能以补充建议替代它。原图、已取得的配套正文及大师配置分别保留。</p><div class="actions"><a class="btn" href="R41_修改与检查说明.md" download>本轮修改与验证记录</a>${routeLink('tools/sources','来源与原件','text-link')}</div></div>`+footer();}
function recordSourceLink(r){return routeLink('atlas/'+r.id,'原页核对 '+esc(r.filename.slice(0,2))+' · 来源与原记录 '+icon('arrow',11),'text-link',{tab:'source'});}
