// v4: navigation is always open. No completion, character-level or inventory gate.
let deskScope=stored.deskScope==='endgame'?'endgame':'level';
let attributeProfile='act2-31';
function statTriple(p){return `<div class="desk-triple">${[['str','力量'],['dex','敏捷'],['int','智慧']].map(([k,n])=>`<div><span>${n}</span><strong>${p.totals[k]}</strong></div>`).join('')}</div>`}
function profileForDesk(){return DATA.desktop.profiles.find(p=>p.scope===deskScope&&p.choice===(deskScope==='level'?state.levelStage:state.current))}
function deskSkillRows(){return deskScope==='level'?levelStage().skills.map(s=>({name:term(s.skill).zh,supports:s.supports.map(k=>term(k).zh),note:s.note||'',optional:!!s.optional,set:s.weaponSet||''})):branch().raw.skills.map(s=>({name:gem(s.id).zh,supports:s.support_skills.map(x=>(shortid(x.id).startsWith('SkillGem')?'〔主动〕':'')+gem(x.id).zh),note:'',optional:false,set:''}))}
function renderDesk(){
 const el=$('#desk-stages');if(!el)return;
 el.innerHTML=`<div class="desk-stage-band"><span>剧情</span>${DATA.leveling.stages.map(s=>`<button type="button" data-desk-level="${s.number}" aria-pressed="${deskScope==='level'&&s.number===state.levelStage}">${esc(s.label)}</button>`).join('')}</div><div class="desk-stage-band"><span>异界</span>${DATA.branches.map(b=>`<button type="button" data-desk-bd="${b.number}" aria-pressed="${deskScope==='endgame'&&b.number===state.current}">${esc(b.label)}${b.number===6?' · 只读':''}</button>`).join('')}</div>`;
 const isLevel=deskScope==='level',s=levelStage(),b=branch(),p=profileForDesk();
 const title=isLevel?s.label+' · '+s.title:b.label;
 $('#desk-summary').innerHTML=`<div class="desk-status"><div><strong>${esc(title)}</strong><p>${esc(isLevel?s.intro:b.profile.overview)}</p></div><span class="badge">${state.mode==='ssf'?'独狼':'可交易'} · 查看不受进度限制</span></div>${isLevel&&state.levelStage===3?'<div class="notice slim"><b>31级但仍在第二章、没有9级宝石：</b>继续看本配置。拿到宝石且满足需求后再实际转冰射；下一阶段内容现在也能直接查看。</div>':''}${!isLevel&&state.current===6?'<div class="notice danger slim">06有升华字段冲突，仅作原始记录对照，不提供无条件导入或属性达标结论。</div>':''}`;
 $('#desk-skills').innerHTML=`<table class="desk-skill-table"><thead><tr><th>主技能</th><th>完整辅助连接</th></tr></thead><tbody>${deskSkillRows().map(s=>`<tr><th>${esc(s.name)}${s.optional?'<small>可选工具</small>':''}${s.set?`<small>武器组${s.set}</small>`:''}</th><td>${s.supports.length?s.supports.map(x=>`<span class="support-inline">${esc(x)}</span>`).join(' '):'<span class="muted">原配置未配辅助</span>'}${s.note?`<details class="desk-inline-note"><summary>用法备注</summary><p>${esc(s.note)}</p></details>`:''}</td></tr>`).join('')}</tbody></table><div class="desk-foot"><a href="#${isLevel?'leveling?lv='+state.levelStage+'&tab=skills':'skills?bd='+state.current}">查看机制、英文与来源 →</a></div>`;
 if(p){$('#desk-attributes').innerHTML=statTriple(p)+`<p class="small"><span class="badge">指定整套配置的参考值</span><br><b>${esc(p.label)}</b><br>含整套装备＋指定等级主动宝石＋全部辅助。不是只有辅助需求。</p>${p.id==='early-target'?'<p class="notice warn slim">这行是80级展示装备目标，不是刚进异界的门槛。</p>':''}<button class="btn smallbtn" type="button" data-open-attributes="${p.id}">看每件装备 / 每颗技能怎么算</button>`}
 else{$('#desk-attributes').innerHTML=`<p>本分支的整套数值尚未逐项核算；不把“辅助宝石需求”填成总属性，也不套用另一分支的数字。</p><a class="btn smallbtn" href="#attributes">查看已核算的整套参考</a><p class="small muted">本分支技能、装备、天赋及文件仍全部可查看，不因此锁定。</p>`}
 $('#desk-combat').innerHTML=`<div class="desk-rotation">${(isLevel?s.combat:b.profile.combat).map(([t,v],i)=>`<div><b>${i+1}. ${esc(t)}</b><p>${esc(v)}</p></div>`).join('')}</div>`;
 $('#desk-gear').innerHTML=isLevel?`<table class="desk-gear-table"><tbody>${s.gear.map(x=>`<tr><th>${esc(x[0])}</th><td>${esc(x[1])}<small>${esc(x[2])}</small></td></tr>`).join('')}</tbody></table>`:`<p>${esc(state.mode==='ssf'?b.profile.ssf:b.profile.trade)}</p><table class="desk-gear-table"><tbody>${b.equipment.map(e=>`<tr><th>${esc(slotName(e))}</th><td><b>${esc(e.zh)}</b><small>${esc(e.translation)}</small></td></tr>`).join('')}</tbody></table><a href="#gear">查看来源、词条与替代 →</a>`;
 $('#desk-tree').innerHTML=isLevel?`<p>${esc(s.tree)}</p><p class="small muted">完整本地连线与合法逐级点序未取得，不能把Early原数组顺序当练级顺序。</p>${external(s.source,'查看作者本阶段树')}<br><a href="#leveling?lv=${s.number}&tab=transition">下一阶段具体改什么 →</a>`:`<p>${esc(b.profile.nextNote||b.profile.stage)}</p><p class="small muted">完整原节点仍可检索。记录数不是实际可花点数，未验证的连线不补造。</p><a href="#tree">本分支全部天赋记录 →</a><br><a href="#upgrade">与下一阶段逐项比较 →</a>`;
}
function renderAttributes(){
 const profiles=DATA.desktop.profiles,p=profiles.find(x=>x.id===attributeProfile)||profiles[0];
 $('#attribute-options').innerHTML=profiles.map(x=>`<button type="button" data-attribute-profile="${x.id}" aria-pressed="${x.id===p.id}">${esc(x.label)}</button>`).join('');
 const maxFor=(cat,k)=>Math.max(0,...p.rows.filter(r=>cat(r.category)).map(r=>r[k]));
 const categories=[['装备（含首饰与药剂）',c=>c.startsWith('装备')||c==='药剂 / 咒符'],['主动、常驻与内嵌主动',c=>c!=='辅助累计'&&!c.startsWith('装备')&&c!=='药剂 / 咒符'],['辅助累计',c=>c==='辅助累计']];
 $('#attribute-content').innerHTML=`<div class="desk-box"><div class="panel-head"><h2>${esc(p.label)}</h2><span class="badge">${p.level}级参考</span></div>${statTriple(p)}<p class="small muted">${esc(p.kind)}</p><ul>${p.notes.map(x=>`<li>${esc(x)}</li>`).join('')}</ul><div class="table-wrap"><table class="desk-calc-table"><thead><tr><th>需求来源</th><th>力量</th><th>敏捷</th><th>智慧</th></tr></thead><tbody>${categories.map(([n,f])=>`<tr><th>${n}</th>${['str','dex','int'].map(k=>`<td>${maxFor(f,k)}</td>`).join('')}</tr>`).join('')}<tr class="calc-total"><th>整套面板至少达到（各列取最大值）</th>${['str','dex','int'].map(k=>`<td>${p.totals[k]}</td>`).join('')}</tr></tbody></table></div><p class="small">${esc(DATA.desktop.rule)}</p></div><div class="desk-box"><h2>完整核算清单：没有省略装备</h2><div class="table-wrap"><table class="desk-calc-table"><thead><tr><th>项目</th><th>类别</th><th>力量</th><th>敏捷</th><th>智慧</th><th>前提 / 来源</th></tr></thead><tbody>${p.rows.map(r=>`<tr><th>${esc(r.label)}</th><td>${esc(r.category)}</td><td>${r.str}</td><td>${r.dex}</td><td>${r.int}</td><td><small>${esc(r.note)}</small>${external(r.url,'来源')}</td></tr>`).join('')}</tbody></table></div></div><div class="notice warn">这是装备与技能“能使用”的属性要求，不是伤害、生命、抗性、精魂或回蓝合格证明。相同三维不能保证通关；其他系统仍按正文核对。</div>`;
}
document.addEventListener('click',e=>{const t=e.target.closest('button');if(!t)return;
 if(t.dataset.deskLevel){deskScope='level';setLevelStage(t.dataset.deskLevel);renderDesk();save();return}
 if(t.dataset.deskBd){deskScope='endgame';setCurrent(t.dataset.deskBd);renderDesk();save();return}
 if(t.dataset.openAttributes){attributeProfile=t.dataset.openAttributes;renderAttributes();location.hash='attributes';return}
 if(t.dataset.attributeProfile){attributeProfile=t.dataset.attributeProfile;renderAttributes();return}
 if(t.id==='desk-copy'){copyPlain((deskScope==='level'?levelStage().label:branch().label)+'\n'+deskSkillRows().map(s=>s.name+' → '+(s.supports.join(' / ')||'原配置未配辅助')).join('\n'));return}
});
