// v3: campaign route, compact skills, and disclosure controls.
// This file is injected inside app.js's IIFE by build.py. No network dependencies.
function setDensity(){document.documentElement.dataset.density=state.density;const b=$('#density-toggle');b.textContent=state.density==='compact'?'紧凑':'舒适';b.setAttribute('aria-pressed',String(state.density==='compact'));b.setAttribute('aria-label',state.density==='compact'?'当前紧凑，切换舒适间距':'当前舒适，切换紧凑间距')}
function term(k){return DATA.leveling.terms[k]||{zh:k,en:k,url:'',note:''}}
function levelStage(){return DATA.leveling.stages.find(x=>x.number===state.levelStage)||DATA.leveling.stages[0]}
function syncCampaignBar(){const on=activePage==='leveling'||(activePage==='desk'&&deskScope==='level');document.body.classList.toggle('is-attributes',activePage==='attributes');document.body.classList.toggle('is-leveling',on);$('#level-stage-global').innerHTML=DATA.leveling.stages.map(s=>`<option value="${s.number}" ${s.number===state.levelStage?'selected':''}>${esc(s.label)} · ${esc(s.title)}</option>`).join('');if(activePage==='attributes')$('#global-note').textContent='整套属性参考独立查阅：各份配置的底材与宝石等级写在下面，不以当前选中的异界BD替代。';if(on)$('#global-note').textContent=`剧情阶段 · ${state.mode==='ssf'?'独狼获取':'可交易获取'} · 与异界BD选择独立；通关后再进入01。`;}
function supportChips(items){return items.map((x,i)=>`<span class="gem-chip ${x.active?'active-gem':''}" ${x.id?`data-gem-id="${esc(x.id)}"`:''}><span class="chip-index">${i+1}</span>${x.active?'<em>主动</em>':''}${esc(x.zh)}</span>`).join('')||'<span class="muted empty-chain">原页面未配辅助，可先裸技能</span>'}
function endgameRow(s){const g=gem(s.id),r=role(s);return `<details class="skill-row" data-skill-id="${esc(s.id)}"><summary class="skill-summary"><span class="skill-name"><b>${esc(g.zh)}</b>${metaIds.has(shortid(s.id))?'<small class="row-tag">元技能</small>':''}</span><span class="inline-chain">${supportChips(s.support_skills.map(x=>({id:x.id,zh:gem(x.id).zh,active:shortid(x.id).startsWith('SkillGem')})))}</span><span class="row-more" aria-label="展开详细说明">详情⌄</span></summary><div class="skill-expanded"><div class="detail-top"><b>${esc(g.zh)} / ${esc(g.en)}</b><button type="button" class="btn smallbtn" data-copy="${esc(s.id)}">复制此组</button></div><p>${esc(r[1])}</p><div class="detail-links">${s.support_skills.map((x,i)=>{const m=gem(x.id);return `<div>${i+1}. ${shortid(x.id).startsWith('SkillGem')?'〔内嵌主动〕':''}${external(m.url,m.zh+' / '+m.en)} <small>原件显示区间 ${esc(interval(x.level_interval))}</small><code>${esc(x.id)}</code></div>`}).join('')}</div><p class="source-note">主技能原件显示区间 ${esc(interval(s.level_interval))}；不是解锁或宝石等级。${external(g.url,'名称/机制来源')}</p><code>${esc(s.id)}</code></div></details>`}
function levelRow(s,i){const g=term(s.skill);return `<details class="skill-row" data-level-skill="${esc(s.skill)}"><summary class="skill-summary"><span class="skill-name"><b>${esc(g.zh)}</b>${s.optional?'<small class="row-tag">可选</small>':''}${s.weaponSet?`<small class="row-tag">组${s.weaponSet===1?'Ⅰ':'Ⅱ'}</small>`:''}</span><span class="inline-chain">${supportChips(s.supports.map(k=>({id:k,zh:term(k).zh})))}</span><span class="row-more">详情⌄</span></summary><div class="skill-expanded"><div class="detail-top"><b>${esc(g.zh)} / ${esc(g.en)}</b><button type="button" class="btn smallbtn" data-copy-level="${esc(s.skill)}">复制此组</button></div><p>${esc(s.note||'按当前阶段配置；宝石、孔位、属性未满足时逐步补齐。')}</p>${g.note?`<p class="small muted">${esc(g.note)}</p>`:''}<div class="detail-links">${s.supports.map((k,j)=>`<div>${j+1}. ${external(term(k).url,term(k).zh+' / '+term(k).en)}${term(k).note?'<small> '+esc(term(k).note)+'</small>':''}</div>`).join('')}</div><p class="source-note">${external(g.url,'主动技能中文条目')} · ${external(levelStage().source,'本阶段作者来源（国际服）')}；${esc(levelStage().sourceNote)}</p></div></details>`}
function renderLevelSkills(){$('[data-expand-list="level-skill-list"]').textContent='展开说明';const s=levelStage(),q=$('#level-filter').value.trim().toLowerCase();const rows=s.skills.filter(x=>!q||q.split(/\s+/).every(t=>[x.skill,...x.supports].map(k=>term(k).zh+' '+term(k).en).join(' ').toLowerCase().includes(t)));$('#level-skill-list').innerHTML=rows.map(levelRow).join('')||'<p class="empty">本阶段没有匹配。清除搜索或切换等级阶段。</p>';$('#level-count').textContent=`${rows.length} / ${s.skills.length} 组 · ${s.skills.reduce((n,x)=>n+x.supports.length,0)} 颗已列辅助 · 序号表示连接原顺序，不是角色等级。`;}
function setLevelStage(n){if(!validBranch(n))return;state.levelStage=Number(n);const shownLevel=Number($('#level-character-level').value),rg=levelStage().range;if(shownLevel<rg[0]||shownLevel>rg[1])$('#level-character-level').value='';$('#level-filter').value='';save();renderLeveling();renderDesk();syncCampaignBar();writeHash();notify(`剧情配置：${levelStage().label}。异界BD选择未变。`)}
function setLevelTab(tab,focus=false,updateURL=true){const valid=['skills','gear','combat','transition','tree','rewards'];if(!valid.includes(tab))return;state.levelTab=tab;valid.forEach(k=>{$('#lv-pane-'+k).hidden=k!==tab;const b=$('#lv-tab-'+k);b.setAttribute('aria-selected',String(k===tab));b.tabIndex=k===tab?0:-1});save();if(updateURL&&activePage==='leveling')writeHash();if(focus)$('#lv-tab-'+tab).focus();}
function levelGear(s){return `<div class="table-wrap"><table class="level-gear-table"><thead><tr><th>优先部位</th><th>现在做什么</th><th>别踩的坑</th></tr></thead><tbody>${s.gear.map(r=>`<tr><td><b>${esc(r[0])}</b></td><td>${esc(r[1])}</td><td>${esc(r[2])}</td></tr>`).join('')}</tbody></table></div><p class="source-note">${external(s.source,'作者对应等级正文')} · ${state.mode==='ssf'?'独狼：可用升级就停手；不以指定暗金为前置。':'可交易：先比较成品与自制成本；不硬编码材料价格。'}</p>`}
function updateLevelTasks(){const s=levelStage();$('#level-tasks').innerHTML=`<div class="panel"><h3>切换前完成这三项</h3>${s.tasks.map((t,i)=>task(`lv${s.number}-task${i}`,t)).join('')}</div>`;}
function canonicalLevelSkills(s){return s.skills.map(x=>({name:term(x.skill).zh,supports:x.supports.map(k=>term(k).zh)}))}
function canonicalEarly(){return DATA.branches[0].raw.skills.map(x=>({name:gem(x.id).zh,supports:x.support_skills.map(y=>(shortid(y.id).startsWith('SkillGem')?'〔主动〕':'')+gem(y.id).zh)}))}
function buildSkillDiff(a,b){const A=new Map(a.map(s=>[s.name,s])),B=new Map(b.map(s=>[s.name,s]));const lines=[];for(const n of [...new Set([...A.keys(),...B.keys()])]){const x=A.get(n),y=B.get(n);if(x&&y&&JSON.stringify(x.supports)===JSON.stringify(y.supports))continue;lines.push(`<tr><td><b>${esc(n)}</b><br><span class="badge">${!x?'新增':!y?'移除':'辅助改变'}</span></td><td>${x?esc(x.supports.join(' → ')||'未配辅助'):'—'}</td><td>${y?esc(y.supports.join(' → ')||'未配辅助'):'—'}</td></tr>`)}return lines.length?`<div class="table-wrap"><table class="wide-table"><thead><tr><th>技能</th><th>当前</th><th>下一步</th></tr></thead><tbody>${lines.join('')}</tbody></table></div>`:'<p class="notice slim">本地衔接计划保持全部技能连接，不安排到60级就换一套。继续升级实际装备与任务奖励。</p>'}
function renderLevelTransition(){const s=levelStage(),next=DATA.leveling.stages[s.number],end=s.number===6;let intro=end?'通关后才切换01 Early。下面是60+本地沿用配置与上传Early原件的技能差异；不是一次必须全换的清单。':`下一段：${next.label}。达到等级之外，还要有对应技能宝石、孔位、属性与资源。`;$('#level-transition').innerHTML=`<h3>${end?'剧情 → 异界01':esc(s.label+' → '+next.label)}</h3><p>${esc(intro)}</p>${s.number===2?'<div class="notice warn slim">24级转型前：至少1颗7级＋2颗5/6级未切割技能宝石，另预留4–5颗辅助；这不是整套辅助总数。</div>':''}${s.number===3?'<div class="notice slim">人物达到31级且已取得9级未切割技能宝石、满足需求后再转冰射。第二章没拿到宝石就继续本阶段；不强制按等级切换。</div>':''}${buildSkillDiff(canonicalLevelSkills(s),end?canonicalEarly():canonicalLevelSkills(next))}<p class="source-note">仅比较技能与辅助；未读取的天赋节点、装备完整词条不会被写成已验证差异。I/II等阶不同，不省略。</p><div class="actions">${end?'<button class="btn primary" type="button" data-enter-endgame>查看01 Early完整配置 →</button>':`<button class="btn primary" type="button" data-level-stage="${s.number+1}">查看下一阶段</button>`}</div>`;updateLevelTasks();}
function renderLevelTree(){const s=levelStage();$('#level-tree').innerHTML=`<div class="notice warn slim"><b>这里不把异界树当练级树。</b> 本地未取得该阶段节点/连线，不能按一份不存在的图直接照抄；用下方作者原树入口核对。</div><div class="panel"><h3>升华顺序（作者练级说明）</h3><p><b>投射物近距离专精，选零点射击 → 无限弹药 → 聚风</b></p><p>不是到某人物等级自动取得升华点。完成你当前可进入的试炼、实际拿到点数后再按顺序分配；后续蜃影神射属于异界阶段进一步配置。</p><p>普通通路属性按技能/装备缺口选：缺力量/智慧先补足；不需要时再选敏捷。不照着“所有通路全敏捷”导致技能失效。</p><p class="small muted">${esc(s.tree)}</p><div class="actions">${external(s.source,'打开 '+s.label+' 的作者天赋页（国际服）')}</div></div><p class="source-note">${s.number===6?'60+入口打开原站总页，请选择60+；本地没有冒充其原始数据。':'链接带作者阶段参数；若原站状态重置，手动选同名等级页签。'} 原站的main/set1/set2总框架数字不是当前等级可花点数。</p>`;}
function levelBudget(){const k=String(state.levelStage);let v=state.levelBudgets[k];if(!v||typeof v!=='object'||Array.isArray(v))v=state.levelBudgets[k]={total:'',other:'0',items:{}};if(!v.items||typeof v.items!=='object')v.items={};return v}
function renderLevelBudget(){const s=levelStage(),v=levelBudget();$('#level-reserve-rows').innerHTML=s.reserve.map(k=>{const x=v.items[k]||{on:true,value:''};return `<div class="reserve-row"><input id="lv-on-${k}" type="checkbox" data-lv-reserve-on="${k}" aria-label="预算中启用${esc(term(k).zh)}" ${x.on?'checked':''}><label for="lv-value-${k}">${esc(term(k).zh)}</label><input id="lv-value-${k}" type="number" min="0" max="99999" data-lv-reserve-value="${k}" value="${esc(x.value)}" placeholder="最终保留"></div>`}).join('');$('#level-spirit-total').value=v.total||'';$('#level-spirit-other').value=v.other??'0';calcLevelBudget()}
function storeLevelBudget(){const v=levelBudget();v.total=$('#level-spirit-total').value;v.other=$('#level-spirit-other').value;$$('[data-lv-reserve-value]').forEach(x=>{v.items[x.dataset.lvReserveValue]={on:$('#lv-on-'+x.dataset.lvReserveValue).checked,value:x.value}});save();calcLevelBudget()}
function calcLevelBudget(){const out=$('#level-spirit-result'),valid=x=>/^\d+$/.test(String(x))&&Number(x)<=99999;const rows=levelStage().reserve.filter(k=>$('#lv-on-'+k)?.checked);const vals=rows.map(k=>$('#lv-value-'+k)?.value),total=$('#level-spirit-total').value,other=$('#level-spirit-other').value;if(!valid(total)||!valid(other)||vals.some(x=>!valid(x))){out.textContent='请填入精魂总量、已启用技能的最终保留及其他保留；空白不当作0。';out.dataset.status='incomplete';return}const used=vals.reduce((n,x)=>n+Number(x),Number(other)),delta=Number(total)-used;out.textContent=`录入保留 ${used}，总量 ${total}：${delta>=0?'剩余 '+delta:'还缺 '+(-delta)}。这是预算，不是游戏已激活的证明。`;out.dataset.status=delta>=0?'enough':'short'}
function renderRewards(){const q=$('#reward-chapter').value;const list=DATA.leveling.rewards.map((r,i)=>({...r,index:i})).filter(r=>q==='all'||r.chapter===q);$('#level-rewards').innerHTML=`<div class="table-wrap"><table class="rewards-table"><thead><tr><th>已完成</th><th>章节 / 目标定位</th><th>作者列出的奖励与取舍</th></tr></thead><tbody>${list.map(r=>`<tr><td><input type="checkbox" data-check="reward${r.index}" ${checked('reward'+r.index)} aria-label="标记${esc(r.location)}已完成"></td><td><small>${esc(r.chapter)}</small><br>${esc(r.location)}</td><td>${esc(r.reward)}</td></tr>`).join('')}</tbody></table></div><p class="source-note">${external(DATA.leveling.stages[0].source,'作者 Quest Rewards 原清单')}；选择项以国服任务预览为准，本地不累加一个未经验证的总点数/总抗性。</p>`;}
function renderLeveling(){const s=levelStage();$('#level-stage-nav').innerHTML=DATA.leveling.stages.map(x=>`<button type="button" data-level-stage="${x.number}" aria-pressed="${x.number===s.number}"><b>${esc(x.label)}</b><small>${esc(x.title)}</small></button>`).join('');$('#level-title').textContent=s.label+' · '+s.title;$('#level-intro').textContent=s.intro;$('#level-provenance').innerHTML=`<span class="badge ${s.provenance==='author_page_verified'?'ok':'warn'}">${s.provenance==='author_page_verified'?'作者本阶段技能已核对':'60+本地通关衔接 · 非作者原导出'}</span> ${external(s.source,'原版来源')}`;renderLevelSkills();$('#level-gear').innerHTML=levelGear(s);$('#level-combat').innerHTML=`<div class="combat-compact">${s.combat.map(([t,v],i)=>`<div><b>${i+1}. ${esc(t)}</b><p>${esc(v)}</p></div>`).join('')}</div>`;renderLevelTransition();renderLevelTree();renderLevelBudget();renderRewards();
 $('#level-gem-help').innerHTML=`<p><b>先按阶段逐步取得，不是到该阶段第一级就配齐全部。</b> 没辅助不等于技能不能用；同系列高阶辅助未取得时，只有在游戏允许且机制适用时才用低阶过渡。标“可选”的工具可按按钮/属性负担不装。</p><p><b>低等工匠石顺序：</b>${DATA.leveling.priority.sockets.join(' → ')}。第一颗低等工匠石先给狙击，再留一颗给31级冰射。高等工匠石先狙击，若有第二颗再给冰射补分叉。</p><p><b>剧情品质顺序：</b>${DATA.leveling.priority.quality.join(' → ')}。不要把要很快替换的闪电之捷当长期品质投入。</p><p>剧情与异界的原文顺序不同：异界孔位建议把寒冰之捷放在印记之前。本页没有把两篇顺序混成同一条。${source(s.sourceId)}</p><p>技能宝石等级、人物等级、辅助等阶与孔位是四回事。原页面“Support Gem Requirements”不是整个角色的总属性要求；还要看主动宝石和装备。</p>`;
 setLevelTab(state.levelTab,false,false);syncCampaignBar();}
async function copyPlain(text){try{if(!navigator.clipboard)throw Error('No Clipboard API');await navigator.clipboard.writeText(text);notify('已复制')}catch(_e){$('#copy-text').value=text;$('#copy-dialog').showModal();$('#copy-text').focus();$('#copy-text').select()}}
function levelCopyText(k){const s=levelStage();return `${s.label} · ${s.title}\n${s.sourceNote}\n`+s.skills.filter(x=>!k||x.skill===k).map(x=>`${term(x.skill).zh}${x.weaponSet?'〔武器组'+x.weaponSet+'〕':''}${x.optional?'〔可选〕':''}\n${x.supports.map((v,i)=>`${i+1}. ${term(v).zh} / ${term(v).en}`).join('\n')||'原页面未配辅助'}${x.note?'\n备注：'+x.note:''}`).join('\n\n')+`\n来源：${s.source}`}
document.addEventListener('click',e=>{const t=e.target.closest('button');if(!t)return;if(t.id==='density-toggle'){state.density=state.density==='compact'?'comfortable':'compact';setDensity();save();return}if(t.dataset.levelStage){setLevelStage(t.dataset.levelStage);return}if(t.dataset.lvTab){setLevelTab(t.dataset.lvTab);return}if(t.hasAttribute('data-enter-endgame')){setCurrent(1,false);location.hash='start?bd=1';showPage('start',true);return}if(t.hasAttribute('data-copy-level-all')){copyPlain(levelCopyText());return}if(t.dataset.copyLevel){copyPlain(levelCopyText(t.dataset.copyLevel));return}if(t.hasAttribute('data-copy-endgame-all')){const b=branch();copyPlain(b.label+'\n'+b.raw.skills.map(s=>gem(s.id).zh+' → '+s.support_skills.map(x=>(shortid(x.id).startsWith('SkillGem')?'〔主动〕':'')+gem(x.id).zh).join(' / ')).join('\n'));return}if(t.dataset.expandList){const root=document.getElementById(t.dataset.expandList),rows=$$('details.skill-row',root);const expand=rows.some(x=>!x.open);rows.forEach(x=>x.open=expand);t.textContent=expand?'收起全部说明':'展开全部说明';return}});
$('#level-stage-global').addEventListener('change',e=>setLevelStage(e.target.value));$('#level-character-level').addEventListener('change',e=>{const n=Number(e.target.value);if(!Number.isInteger(n)||n<1||n>100){notify('请输入1–100的整数等级');return}notify('人物等级仅作参考；按已取得的技能选择阶段。所有阶段始终可查看。')});
$('#level-filter').addEventListener('input',renderLevelSkills);$('#reward-chapter').addEventListener('change',renderRewards);$('#lv-pane-combat').addEventListener('input',e=>{if(e.target.matches('input'))storeLevelBudget()});$('#lv-pane-combat').addEventListener('change',e=>{if(e.target.matches('input'))storeLevelBudget()});
$('.lv-tabs').addEventListener('keydown',e=>{if(!['ArrowRight','ArrowLeft','Home','End'].includes(e.key))return;const tabs=$$('[data-lv-tab]');let i=tabs.findIndex(t=>t===document.activeElement);if(i<0)return;e.preventDefault();i=e.key==='Home'?0:e.key==='End'?tabs.length-1:(i+(e.key==='ArrowRight'?1:-1)+tabs.length)%tabs.length;setLevelTab(tabs[i].dataset.lvTab,true)});
