// R45: restore selection guidance alongside the unchanged capture.
// The author panel, old records and user guidance are separate data sources.
const G45=window.FUBGUN_GUIDE45;
const old45={card:r43Card,jewels:r43Jewels,jewelCard:r43JewelCard,gear, itemPage,guide,search:searchData,atlas:atlasPage,
 targetTable:q42TargetTable,utilities:q42UtilityTargets,skillSection:q42SkillSection,transition:q42Transition,tools,render,coverage};
function e45(s){return esc(cn44(s));}
function r45Guide(b,uid){return G45.guides[b.stage]?.[uid]||null;}
function r45Wear(base){const f=base.fact,w=f||base.wear;if(!w)return '按实物核对；没有固定需求记录';return [w.level!==null&&w.level!==undefined?'等级 '+w.level:'',w.str?'力量 '+w.str:'',w.dex?'敏捷 '+w.dex:'',w.int?'智慧 '+w.int:''].filter(Boolean).join(' / ');}
function r45Sources(url=G45.source,label='作者正文与选择依据'){return `<span class="r45-source">${safeLink(url,label)}</span>`;}
function r45BaseTable(g){if(!g.bases.length)return '';return `<section id="r45-bases-${g.uid}" class="r45-base-detail"><h3>可用底材与过渡选择</h3><p>不是按名称依次购买。先看你当前能穿的成品；下表为普通未加工底材，生成词缀后的最终需求以实物为准。</p>${q42Rows(g.bases.map(x=>[
 `<b>${e45(x.name)}</b><small>${x.later?'后续候选，不是当前门槛':'本阶段可比较'} · ${e45(x.kind)}</small>`,
 e45(r45Wear(x)),
 x.fact?`${e45(x.fact.base)}${x.fact.note?`<small>${e45(x.fact.note)}</small>`:''}`:'没有新增基础数值；按实际物品核对',
 e45(x.why)+r45Sources(x.url||G45.source,x.fact?'底材数据':'方向依据')
 ]),['底材与适用范围','裸底材佩戴','基础／固有效果','为什么比较'])}</section>`;}
function r45Supplement(g){return g.supplement.length?`<div class="r45-option-list"><h3>剩余属性怎么取舍</h3><p>下面是按缺口挑选的候选，不要求同时占满，也不把描述行数当作合法前后缀数量。</p>${g.supplement.map(x=>`<p><b>${e45(x.text)}</b><small>${e45(x.kind)} · ${e45(x.detail)}</small></p>`).join('')}</div>`:'';}
function r45Example(g){const x=g.example;if(!x)return '';return `<div class="r45-example"><h3>比较例子：${e45(x.title)}</h3><p>${e45(x.example)}</p><p class="r45-caution">${e45(x.caution)}</p><small>教学示例，不是作者面板、你的角色或保证收益。</small></div>`;}
function r45LongGuide(g,b){if(g.readonly)return `<div class="r45-caution">作者实装只读：原面板、字段差异与绑定状态保留，不提供普通底材采购或可执行加工路线。</div>`;return `${r45BaseTable(g)}<section class="r45-decision"><h3>先保住什么</h3><p>${e45(g.keep)}</p>${r45Supplement(g)}<h3>什么时候换／什么时候值得做</h3><p>${e45(g.when)}</p><h3>怎样取得，不必从白装开始</h3><p>${e45(g.acquire)}</p><h3>白底和成品怎么比较</h3><p>${e45(g.compare)}</p><p class="r45-caution">${e45(G45.compareRule)} 旧导出的固定数值及旧品质情景只在证据层保留，不再充当当前成品面板。</p>${r45Example(g)}<p class="r45-stop"><b>做到这里先停：</b>${e45(g.stop)}</p>${r45Sources()}</section>`;}
function r45Unique(it){const u=G45.unique[it.name];if(!u)return '';const arrows=it.name==="Cadiro's Gambit"?`<div class="r45-arrows"><h3>六种随机箭分别做什么</h3><p>每支箭只得到其中一种；不把六种加成同时计入，也不推定它们等概率。这里解释物品引用的效果，不改原面板。</p>${q42Rows(G45.arrows.map(a=>[`<b>${e45(a.name)}</b>`,e45(a.effect),safeLink(a.url,'效果依据')]),['箭矢','作用及边界','出处'])}</div>`:'';return `<section class="r45-mechanic" data-r45-unique="${esc(it.name)}"><h3>这件暗金的用法与替代</h3><p><b>${e45(u.brief)}</b></p><p>${e45(u.why)}</p>${arrows}<p><b>未取得时：</b>${e45(u.get)}</p><p><b>换上前：</b>${e45(u.check)}</p>${r45Sources(u.url,'物品机制依据')}</section>`;}
function r45Utility(it,b){if(R43_MAIN.includes(it.uid))return '';const life=it.uid==='life_flask',mana=it.uid==='mana_flask',charm=it.uid.startsWith('charm');let p='';if(life)p='生命药剂先比较当前能用阶别、实际回复量、速度与即时回复；不要把短期过渡药剂强制做满品质。';else if(mana)p='魔力药剂按连续消耗与无小怪场景检验，不只看单次回复总量；已有好用普通药剂可继续用。';else if(charm)p='先确认对应咒符槽开放。核对触发条件、防护内容、当前充能与持续时间；短时防护不是永久免疫。';else if(it.uid==='weapon2')p='第二武器组不是另一套必购全身装备；只读原配置，共用栏位不要重复采购。';return p?`<div class="r45-utility-tip"><b>怎么判断这件：</b>${e45(p)}</div>`:'';}
r43Card=function(it,b,isolated=false){const t=document.createElement('template');t.innerHTML=old45.card(it,b,isolated);const article=t.content.querySelector('article.r43-equip');if(!article)return t.innerHTML;const g=r45Guide(b,it.uid);const header=article.querySelector('header');
 if(g){const intro=document.createElement('section');intro.className='r45-pick';intro.dataset.r45Guide=it.uid;const current=g.bases.filter(x=>x.current);intro.innerHTML=`<div class="r45-minihead">${it.source_is_unique?'普通替代与配装方向':'底材与过渡 · 先看这里'}</div><p>${e45(g.brief)}</p>${current.length?`<p class="r45-base-line"><b>可比较：</b>${current.map(x=>`<span>${e45(x.name)}${x.fact?`<small>（裸底材${x.fact.level}级）</small>`:''}</span>`).join('、')}</p>`:''}`;header.after(intro);
 const deep=document.createElement('details');deep.className='r45-details';deep.id='r45-guide-'+it.uid;deep.open=isolated;deep.innerHTML=`<summary>底材需求、替代、词缀取舍与打造时机</summary><div class="r45-detail-body">${r45LongGuide(g,b)}</div>`;article.querySelector('.r43-proof')?.before(deep);
 if(!g.readonly){const tip=document.createElement('p');tip.className='r45-stop r45-card-stop';tip.innerHTML='<b>够用就先停：</b>'+e45(g.stop);deep.after(tip);}
 }
 const marker=document.createElement('h3');marker.className='r45-panel-label';marker.textContent='作者配置 · 当前采集面板';const target=article.querySelector('.r43-stats,.r43-mods,.r43-missing');if(target)target.before(marker);
 const unique=r45Unique(it);if(unique){const d=document.createElement('details');d.className='r45-details r45-unique-details';d.open=isolated;d.innerHTML='<summary>这件暗金的效果、用法与替代</summary>'+unique;article.querySelector('.r43-proof')?.before(d);}
 const util=r45Utility(it,b);if(util){const u=document.createElement('div');u.innerHTML=util;header.after(u.firstElementChild);}
 return r44HTML(t.innerHTML);};
function r45JewelPreparation(b,specialOnly=false,compact=false){const ro=b.stage==='e06';let keys=specialOnly?['well','darkness']:['mana','ordinary','well','darkness'];const body=keys.map(k=>{const j=G45.jewels[k];return `<article class="r45-jewel-guide" id="r45-jewel-${k}"><h3>${e45(j.title)}</h3><p>${e45(j.body)}</p><p><b>取得：</b>${e45(j.get)}</p><p><b>暂时没有：</b>${e45(j.fallback)}</p><p><b>使用检查：</b>${e45(j.check)}</p>${r45Sources(j.url,'作者正文／物品依据')}${j.acquireUrl?r45Sources(j.acquireUrl,'特殊遗物来源'):''}</article>`;}).join('');return `<section class="r45-jewel-prep" id="r45-jewel-prep"><div class="r45-sectionhead"><h2>人物珠宝怎么准备、怎么替换</h2><span>指导 ≠ 已镶嵌清单</span></div><p>${ro?'作者实装的珠宝仍有孔位生效冲突；下列为通用阅读解释，不解除只读。':b.jewels.length?'上方是作者当前配置，下面说明没有配齐时怎样选择；新增珠宝在现有有效孔位内替换，不额外增加孔位。':'当前采集确实没有配置具体珠宝，但仍能按作者正文准备回蓝或输出珠宝；不因此虚构作者已插的物品。'}</p>${compact?`<div class="r45-jewel-brief"><p><b>前期：</b>先比较一颗有击杀回蓝词缀的蓝玉或合适普通输出珠宝；没有击杀时的供蓝单独处理。</p><p><b>后期：</b>泉井之心看自身词缀；抗衡黑暗看实物半径和已分配的对应节点，两者各有限定数量。</p>${q42Link('jewels','查看取得、替代与范围判断 →','text-link',{focus:'r45-jewel-prep'})}</div>`:`<div class="r45-jewel-guide-grid">${body}</div><p class="r45-caution">本页不以旧导出孔数安排固定采购数量。当前绑定记录与完整连通验证是两回事；实际装入和启用仍核对游戏内人物树。</p>`}</section>`;}
r43Jewels=function(b,specialOnly=false){return old45.jewels(b,specialOnly)+r45JewelPreparation(b,specialOnly,current.section==='gear');};
// Jewels with terse named/radius effects need guidance beside their actual panel.
r43JewelCard=function(j,b){let html=old45.jewelCard(j,b);let p='';if(j.name==='Heart of the Well')p='限定1颗；比较珠宝自身的实际词缀。没有半径节点乘算，不把后续双额外伤害目标补写成当前已经拥有。';else if(j.name==='Against the Darkness')p='限定1颗；按该物品实物半径内已分配的对应节点计算，不能只看名称或示例圈。';else if(j.name==='Voices')p='原面板显示配置2–4个特殊珠宝孔，这是范围而非已确认当前精确孔数。作者实装仍只读，不据此自动增加可用点数。';else p='当前展示的是这颗的词缀组合与范围；同图标的其他珠宝可能不同，不能直接复制成同一颗。';const t=document.createElement('template');t.innerHTML=html;const n=document.createElement('p');n.className='r45-jewel-note';n.textContent=p;t.content.querySelector('.r43-proof')?.before(n);return t.innerHTML;};
gear=function(){const b=r43Build();let h=old45.gear();if(!b)return h;const t=document.createElement('template');t.innerHTML=h;const context=t.content.querySelector('.r43-context');if(context){const p=document.createElement('div');p.className='r45-overall';p.id='r45-overall';p.innerHTML=`<b>先看整套是否能用，再追作者那件。</b><p>换装先扣旧件属性，再加新件；下方底材是可比较的候选，不是都要买齐。${q42Link('character','查看天赋切换的配套条件 →','text-link',{tab:'tree'})}</p>`;context.after(p);}return t.innerHTML;};
// All summaries of CURRENT equipment share the same capture, not the old target raw values.
q42TargetTable=function(compact=false){const b=r43Build();if(!b)return old45.targetTable(compact);const rows=R43_MAIN.map(uid=>{const it=b.equipment.find(x=>x.uid===uid);if(!it)return null;const g=r45Guide(b,uid);return [q42Link('item/'+uid,e45(D.slots.find(s=>s.id===uid)?.name||uid),'q42-item-link',{tab:'target'}),`<strong>${e45(it.name)}</strong><small>当前采集面板；括号为范围</small>${g?`<p>${e45(g.brief)}</p>`:''}`,`${it.panel.top_stats.length?`<div class="r45-inline-stats">${it.panel.top_stats.map(x=>`${e45(R43_STAT[x.label]||x.label)}：${e45(x.value)}`).join('；')}</div>`:''}${it.panel.modifiers.length?r43Panel(it.panel):'<p>面板未给完整词缀；不从旧保存值补算。</p>'}${it.sourcePanelCaution?.length?`<p class="r45-caution">${it.sourcePanelCaution.map(e45).join('；')}</p>`:''}`,q42Link('item/'+uid,'完整面板、底材与做法 →','btn small',{tab:'target'})];}).filter(Boolean);return `<section class="q42-targets r45-current-targets"><p class="r45-source-note">与装备总览使用同一份当前采集数据。旧导出示例只在单件证据中保留，不再混称“当前目标”。</p>${q42Rows(rows,['部位','当前配置与过渡方向','当前完整面板','阅读入口'])}</section>`+q42UtilityTargets();};
q42UtilityTargets=function(){const b=r43Build();if(!b)return old45.utilities();const xs=b.equipment.filter(x=>!R43_MAIN.includes(x.uid));return `<section class="q42-utility-targets r45-current-utility"><h2>药剂、咒符与第二武器组</h2><p>使用同一份当前采集，不复制另一阶段的装备，也不套普通防具加工模板。</p>${q42Rows(xs.map(it=>[e45(D.slots.find(s=>s.id===it.uid)?.name||it.slot_label),`<b>${e45(it.name)}</b>`,r43Panel(it.panel)+r45Utility(it,b),q42Link('item/'+it.uid,'面板与用法','btn small',{tab:'target'})]),['栏位','当前物品','实际属性与判断','查看'])}<div class="r45-jewel-summary"><h3>人物天赋珠宝</h3><p>当前配置展示${b.jewels.length}颗。${b.jewels.length?'每颗实际属性与绑定分开核对，不把展示数量当成全部孔都已验证生效。':'这是没有配置具体物品，不代表没有准备方法，也不默认采购某个固定孔数。'}</p>${q42Link('jewels','看当前珠宝及准备／替代说明','btn')}</div></section>`;};
q42SkillSection=function(){const b=r43Build();return b?r43Skills(b):old45.skillSection();};
q42Transition=function(){const b=r43Build();if(!b)return old45.transition();let h=old45.transition();return `<div class="r45-transition-rule"><h3>先看条件，不按编号自动洗点</h3><p>${e45(b.notes.transition)}</p><p>初期到非暴击中期可逐步补强；转混合防御或暴击需相应装备与技能配套。作者允许先转暴击再转混合，页面顺序不是唯一合法路线。</p></div>`+h;};
// Restore source figure visibility without inventing a translated dynamic graph.
r43Tree=function(b){return r44HTML(_r44tree(b),root=>{root.querySelectorAll('.r43-node-ids').forEach(x=>x.dataset.r44Original='true');const f=root.querySelector('figure');if(f)f.dataset.r45VisibleTree='true';});};
// Keep operation rules readable; only unresolved proper names get neutral identifiers.
const r45Unknown=[['Opulent','作者最高优先符文（专名待核）'],['prolif','作者未展开说明的特殊符文'],['Power','第二档符文①（专名待核）'],['Death','第二档符文②（专名待核）'],['Bond','第二档符文③（专名待核）'],['Time','第三档符文①（专名待核）'],['Oath','第三档符文②（专名待核）'],['rebirth','第三档蓝色符文（专名待核）'],['Uthred','相关首领（专名待核）'],['Stardrinker','首领传闻①'],['Origin of the fall','首领传闻②'],['The last to fall','首领传闻③'],['End of the Circle','首领传闻④'],['All that glitters','独特地图传闻①'],['reflective waters','独特地图传闻②'],['almost paradise','独特地图传闻③'],['a good fellow','独特地图传闻④'],['Fallen skies','独特地图传闻⑤'],["Runeseeker's Call",'相关任务（专名待核）']];
function r45RestoreOps(html,id){if(id!=='expedition')return html;const t=document.createElement('template');t.innerHTML=html;let replaced=new Set();const w=document.createTreeWalker(t.content,NodeFilter.SHOW_TEXT);let n;const nodes=[];while(n=w.nextNode())if(n.parentElement&&!n.parentElement.closest('[data-r44-original],pre,script,style,.r43-rawparagraph'))nodes.push(n);
 for(const x of nodes){let s=x.textContent;for(const [a,b] of r45Unknown){const re=new RegExp(escRE44(a),'gi');if(re.test(s)){re.lastIndex=0;s=s.replace(re,b);replaced.add(a);}}s=s.replace(/作者未展开说明的特殊符文\s*符文/g,'作者未展开说明的特殊符文').replace(/SS＝/g,'最高优先＝').replace(/S＝/g,'第二优先＝').replace(/A＝/g,'第三优先＝').replace(/B＝/g,'第四优先＝').replace(/C＝/g,'第五优先＝').replace(/B 档/g,'第四档');x.textContent=s;}
 if(replaced.size){const note=document.createElement('section');note.className='r45-source-ops';note.innerHTML='<p><b>规则保留，个别专名单独待核。</b>下方操作来自已保存的作者攻略；“首领传闻①”等是阅读编号，不冒称国服正式名称。历史价值数字不作当前市场价格或收益保证。</p><details class="r43-proof"><summary>未核专名的原文对应（只用于查原页）</summary><div data-r44-original>'+r45Unknown.filter(([a])=>replaced.has(a)).map(([a,b])=>'<p>'+esc(b)+'：'+esc(a)+'</p>').join('')+'</div></details>';const tabs=t.content.querySelector('.c41-tabs,.r30-tabs,.q42-tabs');if(tabs)tabs.after(note);else t.content.prepend(note);}
 return t.innerHTML;}
atlasPage=function(id){return r45RestoreOps(old45.atlas(id),id);};
// Teach at the crafting entrance without reinserting a material encyclopedia.
itemPage=function(slot,params){const b=r43Build();let h=old45.itemPage(slot,params);if(!b||b.stage==='e06'||(params.get('tab')||'target')==='target')return h;const g=r45Guide(b,slot);if(!g)return h;const t=document.createElement('template');t.innerHTML=h;const box=document.createElement('section');box.className='r45-craft-choice';box.innerHTML=`<h2>这件值不值得继续做</h2><p><b>保住：</b>${e45(g.keep)}</p><p><b>开始前：</b>${e45(g.when)}</p><p><b>停止线：</b>${e45(g.stop)}</p><details class="r45-details"><summary>当前部位的比较例子</summary>${r45Example(g)}</details>${q42Link('item/'+slot,'先选底材／替代，再回制作 →','text-link',{tab:'target',focus:'r45-guide-'+slot})}`;const marker=t.content.querySelector('.r43-craft-reference');if(marker)marker.after(box);else t.content.querySelector('.c41-tabs,.q42-tabs')?.after(box);return t.innerHTML;};
function recovery45(){return heading('配装指导 / 完整阅读','底材、面板、制作，各自回答什么','不再用作者装备展示替代新手选择指导。')+`<div class="r45-recovery"><h2>已经接回当前阅读路径</h2>${q42Rows([
 ['底材／过渡','每件装备卡直接提示候选方向；详情列需求、基础值、理由及来源。','装备总览 → 当前部位'],
 ['词缀取舍／取得／停手','功能优先与可选补位分开；不需要从白装做起，不把全部候选强凑六词。','单件目标 → 选择说明'],
 ['白底与成品','裸底材事实、当前采集面板、旧导出证据独立；不用旧计算覆盖新面板。','单件目标 → 白底和成品怎么比较'],
 ['珠宝','当前已配面板与未配齐时的准备、取得、替代、范围检查并存。','人物珠宝／特殊人物珠宝'],
 ['暗金','补回卡迪罗六种箭功能以及药剂咒符、猎首的条件性用法。','对应装备 → 暗金用法'],
 ['成长页一致性','主装备、辅助物品和技能共用当前采集；旧固定数值不再称当前目标。','剧情与资料 → 本阶段成长任务'],
 ['搜索／原图／操作','底材与回蓝等指导可搜索；天赋原图直接显示；未核专名不再把整段异界操作藏起。','搜索／人物天赋／异界操作']
 ],['内容','本版处理','在哪里看'])}<h2>仍需保留的证据限制</h2>${r43List(G45.remaining)}<p>${e45(G45.boundary)}</p><p>作者面板与全部原版文件不因恢复指导而更改。本页所述为阅读与资料整合，不是游戏实测或已经部署到你的域名。</p><div class="r43-links">${q42Link('gear','回全身装备','btn primary')}${q42Link('tools/capture-audit','原采集差异与证据','btn')}${q42Link('tools/filters','四份原版过滤器','btn')}<a class="btn" href="R45_修改与检查说明.md">本版说明</a></div></div>`+footer();}
tools=function(k,p){return k==='selection-guide'?recovery45():old45.tools(k,p);};
coverage=function(){return recovery45();};
footer=function(){return `<footer class="footer"><span>冰霜射击攻略 · R45 配装指导修复</span><div>${q42Link('tools/selection-guide','本版内容与边界')} · ${q42Link('tools/names','中文名称来源')} · ${q42Link('tools/filters','四份原版过滤器')}</div></footer>`;};
let searchIndex45=null;
function makeSearch45(){const out=[];for(const b of C43.builds){for(const g of Object.values(G45.guides[b.stage]||{})){if(g.readonly)continue;for(const x of g.bases)out.push({title:cn44(x.name),text:cn44(b.name)+' · '+g.title+' · '+(x.later?'后续候选':'当前可比较底材'),query:cn44(x.why+' '+(x.fact?.base||''))+' '+x.en,route:'item/'+g.uid,params:{stage:b.stage,tab:'target',focus:'r45-guide-'+g.uid}});out.push({title:g.title+'的替代、取舍与打造时机',text:cn44(b.name),query:cn44(g.brief+' '+g.keep+' '+g.when+' '+g.acquire+' '+g.stop),route:'item/'+g.uid,params:{stage:b.stage,tab:'target',focus:'r45-guide-'+g.uid}});}
 for(const [id,j]of Object.entries(G45.jewels))out.push({title:j.title,text:cn44(b.name)+' · 珠宝准备与使用',query:j.body+' '+j.get+' '+j.fallback+' '+j.check,route:'jewels',params:{stage:b.stage,focus:'r45-jewel-'+id}});
 for(const it of b.equipment){const u=G45.unique[it.name];if(u)out.push({title:u.zh+'的效果与替代',text:cn44(b.name),query:u.brief+' '+u.why+' '+u.get+' '+u.check+(it.name==="Cadiro's Gambit"?' '+G45.arrows.map(a=>a.name+' '+a.effect).join(' '):''),route:'item/'+it.uid,params:{stage:b.stage,tab:'target'}});}}
 return out;}
searchData=function(q){if(!searchIndex45)searchIndex45=makeSearch45();const words=String(q||'').toLowerCase().trim().split(/\s+/).filter(Boolean);const found=words.length?searchIndex45.filter(x=>words.every(w=>(x.title+' '+x.text+' '+x.query).toLowerCase().includes(w))):[];found.sort((a,b)=>(b.params?.stage===state.stage)-(a.params?.stage===state.stage));return [...found,...old45.search(q)].filter((x,i,a)=>a.findIndex(y=>y.title===x.title&&y.route===x.route&&JSON.stringify(y.params)===JSON.stringify(x.params))===i).slice(0,24);};
render=function(){const r=old45.render();const focus=current.params.get('focus');if(focus&&/^r45-[a-z0-9-]+$/.test(focus)){const el=document.getElementById(focus);if(el){let p=el;while(p){if(p.tagName==='DETAILS')p.open=true;p=p.parentElement;}el.classList.add('r45-focus');requestAnimationFrame(()=>el.scrollIntoView({block:'start'}));}}
 document.title='冰霜射击攻略 · R45';document.querySelectorAll('.side-bottom,.sidebar .version,.sidebar .sidebar-version').forEach(e=>{e.textContent='0.5.5 · R45 配装指导修复';});document.documentElement.dataset.r45Ready='true';return r;};
window.R45={guide:G45,search:()=>searchData,searchQuery:q=>searchData(q),getBuild:r43Build,render,baseTable:r45BaseTable};
