// R42: one stage context and five coherent work areas. Source data are read-only.
const G42=D.guide42;
const R42StageIds=[...G42.campaign.map(c=>c.id),...D.stages.map(c=>c.id)];
state.context42=getStore('context42',state.stage);if(!R42StageIds.includes(state.context42))state.context42='e01';
function q42CP(){return G42.campaign.find(c=>c.id===state.context42)||null;}
function q42Context(extra={}){const p=q42CP()?{cp:state.context42}:{stage:state.stage};if(extra.stage)delete p.cp;if(extra.cp)delete p.stage;return {...p,...extra};}
function q42Link(r,label,cls='text-link',extra={}){return routeLink(r,label,cls,q42Context(extra));}
function q42Label(id){const c=G42.campaign.find(c=>c.id===id);return c?c.label+' · '+c.title:labelStage(D.stages.find(s=>s.id===id)||D.stages[0]);}
function q42Period(){const c=q42CP();return c?(c.number<4?'pre31':'post31'):'entry';}
function q42Text(x){return Array.isArray(x)?x.join('；'):String(x||'');}
function q42Rows(rows,headers){return `<div class="table-scroll"><table class="q42-table"><thead><tr>${headers.map(h=>`<th>${esc(h)}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(c=>`<td>${c}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;}
function q42Tabs(route,items,selected,extra={}){const key=extra._tabKey||'tab';extra={...extra};delete extra._tabKey;return `<nav class="q42-tabs" aria-label="本页阅读内容">${items.map(([id,t])=>q42Link(route,t,'q42-tab '+(id===selected?'active':''),{...extra,[key]:id})).join('')}</nav>`;}
function q42Steps(rows){return `<div class="q42-steps">${rows.map((r,i)=>`<article><span class="stepnum">${String(i+1).padStart(2,'0')}</span><div><h3>${esc(Array.isArray(r)?r[0]:'第'+(i+1)+'步')}</h3><p>${esc(Array.isArray(r)?r[1]:r)}</p></div></article>`).join('')}</div>`;}
function q42Select(id,label,options,selected){return `<label class="q42-select" for="${id}"><span>${label}</span><select id="${id}" class="select">${options.map(([v,t])=>`<option value="${esc(v)}" ${selected===v?'selected':''}>${esc(t)}</option>`).join('')}</select></label>`;}
function stageControl(){return `<div class="stage-control"><label for="r42-stage">当前阅读阶段</label><select id="r42-stage" aria-label="当前阅读阶段"><optgroup label="剧情 · 六个进度">${G42.campaign.map(c=>`<option value="${c.id}" ${state.context42===c.id?'selected':''}>${esc(c.label+' · '+c.title)}</option>`).join('')}</optgroup><optgroup label="异界 · 六份原件">${D.stages.map(c=>`<option value="${c.id}" ${state.context42===c.id?'selected':''}>${esc(labelStage(c))}</option>`).join('')}</optgroup></select></div>`;}
function footer(){return `<footer class="footer"><span>Fubgun 冰射 / 0.5.5 快照 · R42</span><div>${q42Link('coverage','来源边界与检查记录')}<span> · </span>${q42Link('tools/filters','原版过滤器')}</div></footer>`;}
function q42PhaseStrip(){const c=q42CP(),p=c?.original||branch().profile;return `<div class="q42-phase"><span class="tag ${state.context42==='e06'?'gold':''}">${c?'剧情配置':state.context42==='e06'?'原件只读':'异界配置'}</span><p>${esc(c?p.intro:p.overview)}</p>${q42Link('guide','本阶段任务 '+icon('arrow',12),'text-link')}</div>`;}
function q42Profile(c){const wanted=current.params.get('ref');return c.profiles.find(p=>p.id===wanted)||c.profiles.find(p=>p.id==='l3-24')||c.profiles[0];}
function q42CampaignBase(c,slot){const map={bow:'弓',body:'衣服',helmet:'头盔',gloves:'手套',boots:'鞋',quiver:'箭袋',amulet:'项链',belt:'腰带',ring1:'戒指Ⅰ',ring2:'戒指Ⅱ'};return q42Profile(c)?.rows.find(r=>r.category==='装备 · '+map[slot])||null;}
function q42CampaignTarget(c,slot,detail=false){const goal=G42.slotGoals[slot],b=q42CampaignBase(c,slot);if(!goal)return note('药剂、咒符、人物珠宝分别处理，不套普通装备词缀制作。');let base=b?.label||'使用当前可穿、实际效果更好的候选';if(base.includes('：'))base=base.split('：')[0]+' · 按实物选择';
 let body=`<div class="q42-target-head"><span class="tag">剧情功能目标 · 补充整理</span><h2>${esc(goal.title)}</h2><p>参考底材：<b>${esc(base)}</b>${b?.level?' · 裸底材需求'+b.level+'级':''}。这是比较示例，不是必须买齐的套装。</p></div>`;
 body+=q42Rows(goal.goals.map((t,i)=>[String(i+1),esc(t),i===0?'先保住':'按当前缺口比较']),['顺序','这件要具备什么','如何取舍']);body+=note(esc(goal.keep));
 if(detail)body+=c41Example(slot,true)+expand('底材、需求与原阶段依据',`<p>${esc(q42Profile(c)?.label||'')}</p><p>${b?esc('参考佩戴需求：'+wearText(b)+'；'+b.note):'以实际物品的需求栏为准。'}</p>${safeLink(c.source,'作者对应等级分支')}`);
 return body;
}
function q42TargetTable(compact=false){const c=q42CP();let rows=[];for(const slot of Object.keys(G42.slotGoals)){const gn=G42.slotGoals[slot];if(c){const b=q42CampaignBase(c,slot);const name=(b?.label||'当前可用候选').split('：')[0];rows.push([q42Link('item/'+slot,esc(gn.title),'q42-item-link'),`<strong>${esc(name)}</strong><small>${b?.level?'参考裸底材需求 '+b.level+'级':'以实物需求为准'}</small>`,`<div class="q42-mods">${gn.goals.map(t=>`<div>${esc(t)}</div>`).join('')}</div>`,q42Link('item/'+slot,'目标与做法 →','btn small')]);}else{const it=findItem(slot),t=targetData(slot);if(!it||!t)continue;const mods=[...t.raw,...t.definitions];rows.push([q42Link('item/'+slot,esc(gn.title),'q42-item-link'),`<strong>${esc(it.name)}</strong><small>${esc(it.wearShort||'需求按实物核对')}</small>${it.alternative?`<small class="q42-alternative">${esc(it.alternative)}</small>`:''}`,`<div class="q42-mods">${mods.length?mods.map(r=>`<div>${esc(r.text)}</div>`).join(''):'原件未写明完整数值；看单件目标的补充依据。'}</div>${t.supplement.length?`<details class="q42-inline"><summary>补位候选 ${t.supplement.length} 项</summary>${t.supplement.map(r=>`<p>${esc(r.text)}<small>${esc(r.kind)}</small></p>`).join('')}</details>`:''}`,q42Link('item/'+slot,state.context42==='e06'?'只读详情':'目标与做法 →','btn small')]);}}
 return `<div class="q42-targets">${q42Rows(rows,['部位','底材与使用条件','完整属性目标／补位方向','具体做法'])}</div>`+q42UtilityTargets();
}
function gear(){const c=q42CP();return heading('装备与打造 / 全身目标','先看这阶段的一整套','目标先列完整；哪件有缺口，就进入哪件的做法。不要求先录入现有装备。',true)+q42PhaseStrip()+(c?note('剧情目标是按原阶段装备方向整理的功能清单。底材只是有依据的比较示例，未提供的毕业数值不编造。'):note('表中保留作者快照的全部目标属性；高等级示例不是当前阶段的入场硬门槛。原件、补位候选与暗金定义在单件页区分。'))+q42TargetTable()+`<section class="q42-next"><h2>主装备之外，也要检查</h2><div class="q42-links">${q42Link('character','技能与实际操作','btn')}${q42Link('jewels','人物天赋珠宝','btn')}${q42Link('learn/readiness','药剂、咒符与出发检查','btn')}${q42Link('guide','接回本阶段任务','btn primary')}</div></section>`+footer();}
function q42CampaignSkills(c){return q42Rows(c.skills.map(s=>[`<strong>${esc(s.zh)}</strong><small>${esc(s.en)}</small>${s.optional?'<span class="tag gray">可选，非必须</span>':''}`,s.supports.length?s.supports.map((t,i)=>`<div class="q42-support">${i+1}. ${esc(t.zh)}${t.active?'（内嵌主动）':''}</div>`).join(''):'该阶段记录未配置辅助',`<p>${esc(s.note)}</p>${safeLink(s.url,'技能定义')}`]),['技能','当前阶段完整连接','什么时候加入／生效条件']);}
function q42CampaignGemList(c){const entries=new Map();function add(id,name,en,url,kind,where,opt){const x=entries.get(id)||{name,en,url,kind,qty:0,optional:0,where:[]};x.qty++;x.optional+=opt?1:0;x.where.push(where+(opt?'（可选配置）':''));entries.set(id,x)}for(const s of c.skills){add(s.id,s.zh,s.en,s.url,(c.reserve||[]).includes(s.key)?'精魂技能':'主动技能',s.zh,!!s.optional);for(const u of s.supports)add(u.key,u.zh,u.en,u.url,u.active?'内嵌主动':'辅助',s.zh,!!s.optional)}
 return note('下表是当前阶段完整连接所需副本数，包含标出的可选配置；不是刚进这个等级范围就必须一次凑齐，也不是换阶段重买全部。')+q42Rows([...entries.values()].map(x=>[`<strong>${esc(x.name)}</strong><small>${esc(x.en)}</small>`,esc(x.kind),String(x.qty)+(x.optional?`（其中可选${x.optional}）`:''),esc(x.where.join('、')),safeLink(x.url,'条目与需求')]),['名称／阶别','类别','数量','放在哪里','核对']);}
function q42SkillNames(id){const c=G42.campaign.find(c=>c.id===id);if(c)return c.skills.map(s=>({name:s.zh,links:s.supports.map(t=>t.zh)}));const b=D.branches.find(b=>'e0'+b.number===id);return b?b.skills.map(s=>({name:skillName(s.id),links:(s.support_skills||[]).map(t=>skillName(t.id))})):[];}
function q42Diff(a,b){if(!b)return '';const aa=q42SkillNames(a),bb=q42SkillNames(b),am=new Map(aa.map(s=>[s.name,s.links])),bm=new Map(bb.map(s=>[s.name,s.links]));const added=bb.filter(s=>!am.has(s.name)).map(s=>s.name),removed=aa.filter(s=>!bm.has(s.name)).map(s=>s.name),changed=bb.filter(s=>am.has(s.name)&&JSON.stringify(am.get(s.name))!==JSON.stringify(s.links));return `<div class="q42-diff"><h3>换阶段时，连接具体变了什么</h3><p><b>新增：</b>${esc(added.join('、')||'没有新技能')}</p><p><b>移出该快照：</b>${esc(removed.join('、')||'没有移除')}</p>${changed.length?q42Rows(changed.map(s=>[esc(s.name),esc(am.get(s.name).join(' ＋ ')||'无辅助'),esc(s.links.join(' ＋ ')||'无辅助')]),['同名技能','当前阶段连接','下一阶段连接']):'<p>其余同名技能的连接没有变化。</p>'}<small>这是资料之间的差异，不是无条件删技能指令。先具备新配置，再退出旧配置。</small></div>`;}
function q42Transition(){const c=q42CP(),index=R42StageIds.indexOf(state.context42),next=state.context42==='e05'||state.context42==='e06'?null:R42StageIds[index+1],rows=c?G42.milestones[c.id].gate:branch().profile.gate;return `<div class="q42-next"><h2>${next?'满足这些条件，再看下一阶段':'没有自动升级到06的路线'}</h2>${checksHtml(rows||G42.commonChecks,'r42-gate-'+state.context42,state.context42==='e06')}${next?q42Diff(state.context42,next)+`<div class="q42-links">${routeLink('guide','查看下一阶段：'+esc(q42Label(next)),'btn primary',next.startsWith('l')?{cp:next}:{stage:next})}${q42Link('troubleshoot','条件不齐，先定位问题','btn')}</div>`:note(state.context42==='e05'?'05后继续按实际缺口优化；06是有冲突的作者实装快照，仅供对照，不作为第六步采购目标。':'06只读，不提供执行或耗材验收。',true)}</div>`;}
function guide(){const c=q42CP(),m=c?G42.milestones[c.id]:null,b=branch(),active=['overview','skills','craft','next'].includes(current.params.get('tab'))?current.params.get('tab'):'overview';let h=heading('成长路线 / 当前阶段',c?c.title:b.profile.title,c?c.original.intro:b.profile.overview,true)+`<div class="q42-stage-index"><span>直接换阶段，不锁进度</span>${R42StageIds.map(id=>routeLink('guide',esc(id.startsWith('l')?G42.campaign.find(c=>c.id===id).label:labelStage(D.stages.find(s=>s.id===id)).split(' · ')[0]),'q42-stage-pill '+(state.context42===id?'active':''),id.startsWith('l')?{cp:id}:{stage:id})).join('')}</div>`+q42Tabs('guide',[['overview','本阶段目标'],['skills','技能与操作'],['craft','装备怎么做'],['next','准备与下一步']],active);
 if(active==='overview'){h+=`<div class="q42-focus"><span>先做这件事</span><strong>${esc(c?m.now:b.profile.goal)}</strong></div>`+q42TargetTable(true);h+=sec('q42-tasks','01','当前只做这些',q42Steps((c?c.original.tasks:b.profile.tasks).map((x,i)=>['任务 '+(i+1),x])),'',true)+`<div class="q42-links">${q42Link('guide','接着配技能 →','btn primary',{tab:'skills'})}${q42Link('guide','查看材料预留与转换条件','btn',{tab:'next'})}</div>`;}
 if(active==='skills'){h+=c?q42CampaignSkills(c):q42SkillSection();h+=sec('q42-play','02','清怪与首领怎么按',q42Steps(c?c.original.combat:b.profile.combat));h+=note(esc(c?c.original.mana:D.skillSetupNotes.sustain));h+=`<div class="q42-links">${q42Link('gems','按数量准备本阶段宝石','btn')}${q42Link('character','天赋、属性和资源检查','btn')}${q42Link('guide','技能就绪，接着看装备 →','btn primary',{tab:'craft'})}</div>`;}
 if(active==='craft'){h+=`<div class="q42-focus"><span>本阶段什么时候值得做</span><strong>${esc(c?m.craft:b.profile.ssf)}</strong><p>${esc(c?m.stop:b.profile.cannot)}</p></div>`;h+=q42Rows(Object.entries(G42.slotGoals).map(([slot,g])=>[q42Link('item/'+slot,esc(g.title)),esc(C41.examples[c41Key(slot)]?.next||g.keep),q42Link('item/'+slot,'看目标 → 按状态做','btn small',{tab:'craft'})]),['哪一件','先保住什么／补哪条','具体步骤']);h+=`<div class="q42-links">${q42Link('supplies','材料与底材从哪里来','btn')}${q42Link('guide','换装完成，检查下一步 →','btn primary',{tab:'next'})}</div>`;}
 if(active==='next'){h+=`<div class="q42-focus"><span>下一阶段前先预留</span><strong>${esc(c?m.keep:b.profile.nextNote)}</strong></div>`;h+=`<div class="q42-links">${q42Link('learn/permanent','任务永久奖励','btn')}${q42Link('learn/ascendancy','升华点与试炼','btn')}${q42Link('learn/readiness','属性、精魂和药剂验收','btn')}${!c||c.id==='l06'?q42Link('atlas-starter','第一张地图怎么开始','btn'):''}</div>`+q42Transition();}
 h+=expand('当前内容依据',c?`<p>${esc(c.original.sourceNote)}${c.fallback?' 本页沿用已核对42–59配置，不冒充60+独立原件。':''}</p>${safeLink(c.source,'作者对应等级分支')}<p>已保存原详稿：${esc(c.referenceFile)}。参考底材和判断案例属于补充整理；不改原构筑。</p>`:`<p>原件：${esc(b.sourceFile)}；SHA-256 ${esc(b.sha256)}</p>${safeLink(D.skillSetupNotes.source,'作者异界正文')}`);return h+footer();}
function q42SkillSection(){const t=document.createElement('template');t.innerHTML=characterR39();return t.content.querySelector('#char-skills')?.innerHTML||'';}
function q42CharacterSection(id){const t=document.createElement('template');t.innerHTML=characterR39();return t.content.querySelector('#'+id)?.innerHTML||'';}
function character(){const c=q42CP(),tab=['skills','play','tree','check'].includes(current.params.get('tab'))?current.params.get('tab'):'skills';let h=heading('人物配置 / '+(c?'剧情':'异界'),'连法、操作、天赋，分开看','人物天赋不是异界天赋；人物珠宝不是技能／辅助宝石。',true)+q42PhaseStrip()+q42Tabs('character',[['skills','技能连接'],['play','清怪与首领'],['tree','天赋与升华'],['check','属性与资源检查']],tab);
 if(tab==='skills')h+=(c?q42CampaignSkills(c):q42SkillSection()+expand('辅助孔位、品质与升级安排',q42CharacterSection('char-upgrade')))+`<div class="q42-links">${q42Link('gems','完整宝石数量与阶段变化','btn')}${q42Link('special-gems','血脉辅助，不是人物珠宝','btn')}${q42Link('character','接着看操作 →','btn primary',{tab:'play'})}</div>`;
 if(tab==='play')h+=q42Steps(c?c.original.combat:branch().profile.combat)+note(esc(c?c.original.mana:D.skillSetupNotes.sustain))+`<div class="q42-links">${q42Link('character','检查天赋与升华','btn',{tab:'tree'})}${q42Link('guide','回到本阶段任务','btn')}</div>`;
 if(tab==='tree'){if(c)h+=`<div class="q42-focus"><span>当前属性点怎么选</span><strong>先满足正在使用的装备与技能需求；没有缺口时以敏捷为默认方向。</strong><p>${esc(c.original.tree)}</p></div>${safeLink(c.source,'打开作者对应阶段树')}<div class="q42-links">${q42Link('learn/ascendancy','四次升华：各拿2点','btn')}${q42Link('jewels','人物天赋里的珠宝','btn')}</div>`;else h+=q42CharacterSection('char-tree')+expand('原件节点完整记录（不是逐级点序）',q42Rows(branch().nodes.map(n=>[String(n.row),esc(n.zh),esc(n.scope),esc(n.status),`<code>${esc(n.id)}</code>`]),['原件序号','节点','武器组范围','来源状态','内部ID']));}
 if(tab==='check')h+=q42ResourceCheck()+`<div class="q42-links">${q42Link('learn/build-use','原件如何导入与装配','btn')}${q42Link('learn/skill-check','技能不生效，逐项排查','btn')}${q42Link('guide','接着检查换阶段条件','btn primary',{tab:'next'})}</div>`;
 return h+footer();}
function q42ResourceCheck(){const c=q42CP();let h=note('此页不会扫描角色。先在游戏内配置好辅助和装备，再读人物属性及最终预留；参考值不是入场门槛。');if(c){const p=q42Profile(c);h+=expand('本阶段已保存的完整需求参考',q42Select('q42-ref','参考配置',c.profiles.map(p=>[p.id,p.label]),p.id)+q42Rows(p.rows.map(r=>[esc(r.label),esc(r.category),String(r.str),String(r.dex),String(r.int),esc(r.note)]),['对象','类别','力量','敏捷','智慧','依据／条件'])+`<p>${esc(p.kind)}</p>`);}
 h+=`<form id="q42-resource" class="q42-resource"><h2>核对实际精魂余量</h2><p>输入游戏显示的总精魂与全部常驻的最终精魂预留合计；生命预留另算，不混在精魂里。</p><div class="q42-form-row"><label>实际总精魂<input name="total" type="number" min="0" step="any" inputmode="decimal" required></label><label>最终精魂预留合计<input name="used" type="number" min="0" step="any" inputmode="decimal" required></label><button class="btn" type="submit">核对余量</button></div><p id="q42-resource-result" role="status">尚未输入实际值，不判断是否够用。</p></form>`+checksHtml(G42.commonChecks,'r42-resource-'+state.context42,state.context42==='e06');return h;}

function c41Params(extra={}){return {...Object.fromEntries(current.params||[]),...q42Context(),period:q42Period(),...extra};}
function c41Link(label,extra={},cls='btn'){const slot=current.section==='early-craft'?(current.params.get('slot')||'bow'):(current.slot||'bow');return routeLink('item/'+slot,label,cls,c41Params({tab:'craft',...extra}));}
function c41EssenceChoices(slot,params,kind){const key=c41Key(slot),all=Object.values(c41Catalog()).filter(e=>e.effect?.[key]),groups=[...new Set(all.map(e=>c41GoalOf(e.id)))];const goal=groups.includes(params.get('goal'))?params.get('goal'):null;let html=`<section class="q42-purpose"><h3>这次只补哪一条？</h3><p>先选缺口，再比较手中材料。没有对应精华，保留蓝装或选择下方的富豪分支；不要求三档都用。</p>${q42Select('c41-goal','本次缺口',[['','请选择，不自动决定'],...groups.map(g=>[g,C41Goals[g]||g])],goal||'')}</section>`;if(!goal)return html;
 const es=all.filter(e=>c41GoalOf(e.id)===goal).sort((a,b)=>({lesser:0,normal:1,greater:2}[a.tier]??2)-({lesser:0,normal:1,greater:2}[b.tier]??2));return html+`<div class="q42-essences">${es.map(e=>`<article><header><span>${esc(({lesser:'次级',normal:'普通',greater:'强效'})[e.tier]||'专用')}</span><h4>${esc(e.zh)}</h4></header><p class="q42-effect">${esc(e.effect[key])}</p><p>${esc(c41TierUse(e))}</p><small>${esc(c41Limit(e,slot))}</small><div>${c41Link('我有这颗，核对使用步骤',{kind,action:'essence',essence:e.id,goal},'btn small')}</div></article>`).join('')}</div>`;}
function c41Generic(slot,params){const p=new URLSearchParams(params);p.set('period',q42Period());const t=document.createElement('template');t.innerHTML=_r41_c41Generic(slot,p);const c=q42CP(),action=p.get('action');const intro=t.content.querySelector('.c41-intro');if(intro){if(action)intro.remove();else{const x=C41.examples[c41Key(slot)];intro.innerHTML=`<b>${esc(c&&slot==='bow'?G42.milestones[c.id].craft:x?.next||'先确认物品类别，不套普通装备流程。')}</b><small>${c?'剧情过渡：只在备用候选上处理当前缺口，改善够用就停。':'普通过渡件：先比较实际收益，不把它当作者高配配方。'}</small>`;}}if(action)t.content.querySelector('.c41-example')?.remove();for(const a of t.content.querySelectorAll('a'))if(a.textContent.includes('收尾说明（异界快照')){a.setAttribute('href',path('item/'+slot,q42Context({tab:'finish'})));a.textContent='按当前阶段，查看品质与镶嵌';}return t.innerHTML;}
function q42Finish(slot){const c=q42CP(),p=D.finish[c?c.id:state.stage]?.[slot];if(!p)return note('此部位没有独立收尾资料，不复制别件的品质或孔位规则。',true);if(state.context42==='e06')return note('06仅阅读原件与冲突，不给品质、镶嵌或耗材操作。请主动选择01–05的可执行路线。',true)+expand('原件已有说明，仅作对照',`<p>${esc(p.why)}</p><p>${esc(p.special||'')}</p>`);let h=`<div class="q42-focus"><span>决定保留以后才做</span><strong>${esc(p.pick)}</strong><p>${esc(p.why)}</p></div>`;h+=q42Rows([[esc(p.qualityTool||'不使用普通品质材料'),esc(p.quality)],[esc(p.cap?'只补缺少的孔':'普通增幅孔不适用'),esc(p.socket)]],['材料／状态','这个部位的规则']);h+=q42Steps(p.steps.map((x,i)=>['收尾 '+(i+1),c?x.replace('开始一张低投入图验证','在当前可稳定完成的剧情内容中比较'):x]));h+=checksHtml([...p.checks,...G42.commonChecks],'r42-finish-'+state.context42+'-'+slot,state.context42==='e06');h+=expand('没有首选材料与不能做的操作',[...(p.alternatives||[]),...(p.avoid||[])].map(x=>`<p>${esc(x)}</p>`).join(''));h+=`<div class="q42-links">${q42Link('guide','回本阶段，检查下一步','btn primary',{tab:'next'})}${q42Link('supplies','查询品质、孔位与强化材料','btn',{tab:'finish'})}</div>`;return h;}
function itemPage(slot,params){if(!D.slots.some(s=>s.id===slot))return heading('装备与打造','未找到这个部位')+q42Link('gear','返回全身装备目标','btn');const c=q42CP(),name=D.slots.find(x=>x.id===slot).name;let tab=params.get('tab')||'target';if(['plan','steps'].includes(tab))tab='craft';if(!['target','craft','finish'].includes(tab))tab='target';const onlyMain=c&&!(slot in G42.slotGoals);let h=heading('装备与打造 / '+esc(q42Label(state.context42)),name,c?'先看本阶段可用目标，不把异界高阶底材当剧情入场要求。':'完整属性与来源保留；普通补装和作者专用工艺分开。',true)+`<div class="q42-links q42-itemnav">${q42Link('gear','← 全身目标')}${q42Select('q42-slot','换一件看',D.slots.map(s=>[s.id,s.name]),slot)}</div>`+q42Tabs('item/'+slot,[['target','装备目标'],['craft','一步步做'],['finish','换上前检查']],tab);
 if(c){if(tab==='target'){h+=onlyMain?note(slot==='jewels'?'人物珠宝先看实际已分配的孔；剧情没有逐孔实装记录，不在这里编固定采购数量。':'本阶段没有此栏位的独立作者装备实装。先核对实际药剂／咒符槽或武器组，不照搬后期。')+q42Link(slot==='jewels'?'jewels':'learn/readiness','查看对应使用说明','btn'):q42CampaignTarget(c,slot,true);h+=`<div class="q42-links">${q42Link('item/'+slot,'目标确认，看怎么做 →','btn primary',{tab:'craft'})}</div>`;}else if(tab==='craft'){h+=onlyMain?note('此类不是普通九类装备打造。不要套用精华升黄流程。')+q42Finish(slot):c41Generic(slot,params);}else h+=q42Finish(slot);}
 else{if(tab==='target')h+=fullTargetPanel(findItem(slot),slot)+targetContext(findItem(slot),slot);else if(tab==='craft')h+=c41CraftBody(slot,params);else h+=q42Finish(slot);}
 return h+footer();}
function earlyCraft(){if(state.context42==='e06')return heading('06 · 只读限制','这份快照不提供制作步骤','请主动选择01–05或剧情阶段；不会因为进入普通工作台就解除只读。',true)+footer();const slot=G42.slotGoals[current.params.get('slot')]?current.params.get('slot'):'bow';return heading('装备与打造','从手中这件开始','阶段、部位、物品状态保留在地址中；换路线会清除不适用的材料。',true)+q42PhaseStrip()+q42Select('q42-craft-slot','装备部位',Object.entries(G42.slotGoals).map(([k,v])=>[k,v.title]),slot)+note('先看目标，再决定补哪条。已经有好蓝装或黄装，无需从白装重做。')+`<div class="q42-links">${q42Link('item/'+slot,'先看本阶段这件的完整目标','btn')}${q42Link('item/'+slot,'进入逐步打造','btn primary',{tab:'craft',kind:current.params.get('kind')||'unknown'})}</div>`+c41Generic(slot,current.params)+footer();}
function craftTiming(){const slot=G42.slotGoals[current.params.get('slot')]?current.params.get('slot'):'bow';return heading('装备与打造','不是颜色更高就值得换','先比较这件保住的关键属性，再看一次加工能否补上缺口。',true)+q42PhaseStrip()+q42Select('q42-example-slot','比较哪件',Object.entries(G42.slotGoals).map(([k,v])=>[k,v.title]),slot)+(q42CP()?q42CampaignTarget(q42CP(),slot):c41Example(slot,true))+`<div class="q42-links">${q42Link('item/'+slot,'对照目标，进入当前状态步骤','btn primary',{tab:'craft'})}${q42Link('supplies','没有合适材料怎么办','btn')}</div>`+footer();}
function gemsPage(){const c=q42CP();if(!c)return _r41_gemsPage();return heading('人物配置 / 剧情','这一阶段需要哪些技能宝石','按原有连接统计同名副本；可选技能和未取得的孔位不作为立刻采购要求。',true)+q42PhaseStrip()+q42CampaignGemList(c)+expand('完整连法与可选说明',q42CampaignSkills(c))+q42Transition()+`<div class="q42-links">${q42Link('character','返回技能与操作','btn')}${q42Link('jewels','我要找的是天赋树珠宝','btn')}</div>`+footer();}
function specialGemsPage(){if(!q42CP())return _r41_specialGemsPage();return heading('人物配置 / 特殊辅助','当前剧情没有血脉辅助采购清单','不要把后期血脉辅助当成31级转冰射的前置。',true)+q42PhaseStrip()+q42CampaignGemList(q42CP())+`<div class="q42-links">${q42Link('gems','普通技能／辅助清单','btn primary')}${routeLink('special-gems','主动查看05后期血脉辅助','btn',{stage:'e05'})}${q42Link('special-jewels','我要找天赋树的特殊珠宝','btn')}</div>`+footer();}
function jewelsPage(){if(!q42CP())return _r41_jewelsPage();return heading('人物配置 / 天赋树','剧情珠宝：先有实际孔，再选物品','这里是人物天赋里的珠宝，不是技能辅助、装备符文或异界配置。',true)+q42PhaseStrip()+note('剧情原件没有逐孔珠宝实装。不要照着异界2孔／3孔示例，假定当前人物已经点到同样孔位。')+q42Steps([['先看实际天赋树','确认已分配人物珠宝槽。尚无孔就先沿当前加点推进，不为一颗差珠宝硬绕远。'],['已有孔再补短板','普通珠宝比较对当前攻击有效的属性；尚未转暴击，不把暴击词缀当默认最优。刷图击杀回蓝不代替无小怪时的恢复。'],['特殊珠宝等实物与范围','泉井之心看自身词缀；抗衡黑暗还要看范围内对应已分配天赋。同名不保证实际效果相同。']])+`<div class="q42-links">${routeLink('jewels','查看01已保存珠宝目标与数量依据','btn',{stage:'e01'})}${q42Link('special-jewels','特殊人物珠宝定义','btn')}${q42Link('character','回到人物天赋说明','btn primary',{tab:'tree'})}</div>`+footer();}
function specialJewelsPage(){if(!q42CP())return _r41_specialJewelsPage();return heading('人物配置 / 特殊人物珠宝','先读定义，不提前要求购买','剧情没有这两颗珠宝的固定实装；看实物词缀与实际孔位，不照搬后期点法。',true)+q42PhaseStrip()+note('特殊珠宝属于后续方向，不是本阶段的入场要求。每种的数量限制、获取方式与替代分别看。')+j39Card('well')+j39Card('darkness')+j39Range()+j39Evidence()+`<div class="q42-links">${q42Link('jewels','回到当前人物珠宝准备','btn primary')}${q42Link('character','当前人物天赋','btn',{tab:'tree'})}</div>`+footer();}
function learningPage(id){if(id==='start')return guide();if(id==='readiness')return heading('人物配置 / 换装后检查','出发之前，逐项确认','这里合并实际资源核对和完整出发清单，不要求你从旧资料拼接。',true)+q42PhaseStrip()+q42ResourceCheck()+q42LearningBody(id)+footer();if(id==='ascendancy')return ascendancyChinese();const q=D.learningPages[id]||D.learningPages.audit;return heading('说明 / '+esc(q.title),esc(q.title),esc(q.description||q.summary),true)+q42PhaseStrip()+q42LearningBody(q.id)+`<div class="q42-links">${q42Link('guide','回到本阶段任务','btn primary')}${q42Link('troubleshoot','仍有问题，按症状排查','btn')}</div>`+footer();}
function q42LearningBody(id){const q=D.learningPages[id]||D.learningPages.audit,sections=q.sections||[];let i=Number(current.params.get('part')||0);if(!Number.isInteger(i)||i<0||i>=sections.length)i=0;const s=sections[i],dest=current.section==='supplies'?'supplies':'learn/'+q.id,pp=current.section==='supplies'?{tab:'get'}:{};return `<div class="q42-reader"><nav class="q42-chapters" aria-label="阅读章节">${sections.map((s,j)=>q42Link(dest,`${String(j+1).padStart(2,'0')} ${esc(s.title)}`,j===i?'active':'',{...pp,part:j})).join('')}</nav><article class="q42-article"><h2>${esc(s?.title||'说明')}</h2>${s?.html||''}${s?.sources?.length?learnedSources(s.sources):''}<div class="q42-next">${i? q42Link(dest,'← 上一节','btn',{...pp,part:i-1}):''}${i<sections.length-1?q42Link(dest,'下一节 →','btn primary',{...pp,part:i+1}):q42Link('guide','本专题读完，回阶段任务','btn primary')}</div></article></div>`;}
function supplies(){const tab=['get','reserve','finish'].includes(current.params.get('tab'))?current.params.get('tab'):'get',c=q42CP();let h=heading('装备与打造 / 获取与预留','缺什么，就找对应获取方式','买成品、留现用品、做备用件是不同选择；没有实时价格，不承诺打造一定更便宜。',true)+q42PhaseStrip()+q42Tabs('supplies',[['get','装备与材料获取'],['reserve','这个阶段留什么'],['finish','品质与镶嵌查询']],tab);if(tab==='get')h+=q42LearningBody('acquisition');if(tab==='reserve')h+=`<div class="q42-focus"><span>先留给下一阶段</span><strong>${esc(c?G42.milestones[c.id].keep:branch().profile.nextNote)}</strong></div>`+q42Transition()+note('原版过滤器可能隐藏部分低价值材料或底材。这里只解释原规则，不为获取需求修改原文件。')+q42Link('tools/filters','选择保存的原版过滤器','btn');if(tab==='finish')h+=q42Rows(D.slots.filter(s=>s.group==='main').map(s=>[esc(s.name),esc(D.finish[state.context42]?.[s.id]?.qualityTool||'不套用普通品质材料'),esc(D.finish[state.context42]?.[s.id]?.socket||''),q42Link('item/'+s.id,'本部位完整收尾','btn small',{tab:'finish'})]),['部位','品质材料','增幅孔规则','实际步骤'])+`<div class="q42-links">${q42Link('tools/dictionary','查询具体符文、灵核、催化剂的作用','btn')}${q42Link('reference','完整强化材料与条件','btn',{doc:'runes-all.html'})}</div>`;return h+footer();}
function troubleshoot(){const cases=[['damage','打不动','先检查当前技能连法与实际生效，再比较武器。不要默认所有问题都该用崇高解决。',[['character','技能连法与实际操作',{tab:'skills'}],['learn/skill-check','辅助、武器组与生效条件',{}],['item/bow','弓的目标和比较方法',{tab:'target'}]]],['survival','容易死','先核对换下旧装后的生命抗性、药剂咒符、地图词缀。回到可稳定完成的内容再比较。',[['learn/readiness','出发前完整检查',{}],['item/life_flask','药剂条件与收尾',{tab:'finish'}],['learn/map-run','当前地图的风险',{}]]],['mana','缺蓝／常驻开不全','按游戏内最终消耗与预留检查；击杀回蓝不解决无小怪阶段。',[['character','实际精魂与属性检查',{tab:'check'}],['learn/skill-check','资源和技能失效排查',{}],['jewels','人物珠宝与回蓝边界',{}]]],['materials','材料不够','能用就先用；没有合适精华不强迫购买，也不把低阶全部合成。',[['supplies','材料获取和本阶段预留',{tab:'reserve'}],['item/bow','从现有物品状态开始',{tab:'craft'}],['tools/filters','原版过滤器到底显示什么',{}]]],['swap','换装／转型后更弱','先保留并退回可用旧配置；逐项核对新技能、属性、武器组和整套配套，不只看一件新装备。',[['guide','对照下一阶段真正的差异',{tab:'next'}],['character','武器组与资源核对',{tab:'check'}],['learn/build-use','导入和装配检查',{}]]]];const id=current.params.get('case')||'damage',v=cases.find(x=>x[0]===id)||cases[0];return heading('成长路线 / 故障排查','先定位问题，再花材料','每条排查都回到当前阶段，不跳到高配采购单。',true)+q42PhaseStrip()+q42Tabs('troubleshoot',cases.map(x=>[x[0],x[1]]),v[0],{_tabKey:'case'})+`<div class="q42-focus"><span>${esc(v[1])}</span><strong>${esc(v[2])}</strong></div>`+q42Steps(v[3].map(([r,n,p],i)=>['检查 '+(i+1),n]))+`<div class="q42-links">${v[3].map(([r,n,p])=>q42Link(r,esc(n),'btn',p)).join('')}</div>`+footer();}

const Q42FileMap={
 'equipment.html':['gear',{}],'index.html':['gear',{}],'craft.html':['early-craft',{}],
 'craft-early-all.html':['early-craft',{}],'craft-advanced.html':['item/bow',{tab:'craft'}],
 'filters.html':['tools/filters',{}],'filter-legend.html':['filter-guide',{}],
 'atlas-images.html':['atlas-choose',{}],'atlas-unlock.html':['atlas-unlock',{}],
 'roadmap.html':['guide',{}],'after-quests.html':['guide',{stage:'e01',tab:'next'}],
 'finish-check.html':['learn/readiness',{}],'coverage.html':['coverage',{}],
 'sources.html':['tools/sources',{}],'prepare.html':['supplies',{}]
};
function archive(file,label='查看完整资料'){const f=String(file).split(/[?#]/)[0].split('/').pop(),m=f.match(/^([le]0[1-6])\.html$/);if(m)return routeLink('guide',label,'text-link',m[1][0]==='l'?{cp:m[1]}:{stage:m[1]});if(Q42FileMap[f]){const [r,p]=Q42FileMap[f];return q42Link(r,label,'text-link',p);}return q42Link('reference',label,'text-link',{doc:f});}
function referencePage(params){const f=params.get('doc')||'beginner-guide.html',d=D.documents.find(d=>d.file===f),r=window.R42references?.[f];if(!d)return heading('查询与下载','没有这个资料条目')+q42Link('tools','返回资料目录','btn');if(!r){q42LoadRefs();return heading('查询与下载 / 资料阅读',esc(d.title),'正在读取包内资料，不请求外部网站。')+'<div id="q42-reference-loading" role="status">正在加载本地正文……</div>'+footer();}let i=Number(params.get('part')??r.anchorMap?.[params.get('anchor')]??0);if(!Number.isInteger(i)||i<0||i>=r.sections.length)i=0;return heading('查询与下载 / 原详稿正文',esc(r.title),'正文已放入统一阅读页；历史工具的交互功能保留在原档案，不能把静态摘录当原计算器。')+`<div class="q42-reader"><nav class="q42-chapters" aria-label="资料章节">${r.sections.map((s,j)=>q42Link('reference',String(j+1).padStart(2,'0')+' '+esc(s.title),i===j?'active':'',{doc:f,part:j})).join('')}</nav><article class="q42-article q42-reference"><h2>${esc(r.sections[i]?.title||r.title)}</h2>${r.sections[i]?.html||'<p>没有可提取的独立正文；请打开原档案。</p>'}<div class="q42-next">${i>0?q42Link('reference','← 上一节','btn',{doc:f,part:i-1}):''}${i<r.sections.length-1?q42Link('reference','下一节 →','btn primary',{doc:f,part:i+1}):''}</div></article></div>`+expand('原档案与边界',`<p>本页重排原文，不改原文件；旧版配色、工具表单及版本提示仍保留在原件。原件SHA-256：<code>${esc(r.sha256)}</code>。</p><a class="btn" href="${esc(r.path)}" target="_blank" rel="noopener">打开历史原文件／交互工具</a>`)+footer();}
let q42RefsLoading=false;
function q42LoadRefs(){if(q42RefsLoading||window.R42references)return;q42RefsLoading=true;const s=document.createElement('script');s.src=G42.referenceAsset;s.onload=()=>{q42RefsLoading=false;if(current.section==='reference')render();};s.onerror=()=>{q42RefsLoading=false;const el=$('#q42-reference-loading');if(el){el.textContent='本地正文资源未读到。请完整解压整包，保留assets文件夹，不要只复制index.html。';}};document.head.appendChild(s);}
function toolIndex(){const groups=[['按问题查询',[['tools/dictionary','材料、符文与催化剂','按名字和实际部位作用找，不把查询表当操作连招。'],['filter-guide','原版颜色与声音','逐条显示匹配条件与动作，不重新配色。'],['filter-check','为什么看不到物品','输入物品条件查看原版匹配顺序。']]],['原件与可追溯资料',[['tools/builds','六份人物原件','编号与哈希保留；06仍只读。'],['tools/filters','四份原版过滤器','当前只推荐保存的四个原版，不修改显示隐藏。'],['tools/sources','来源、版本与未核实项','作者快照与补充建议分开。']]]];return heading('查询与下载','查资料，不用再找旧版本','日常流程已放回阶段和部位；这里保留查询、原件和可追溯的深入资料。')+groups.map(([n,ls])=>`<section class="q42-library-group"><h2>${n}</h2><div class="q42-tool-grid">${ls.map(([r,t,d])=>`<article><h3>${q42Link(r,t)}</h3><p>${d}</p>${q42Link(r,'进入 →','btn small')}</article>`).join('')}</div></section>`).join('')+sec('r42-documents','03','全部深入资料',documentCatalog())+expand('导出／恢复网页中的手动勾选记录',backupPanel())+footer();}
function tools(kind,params){if(kind==='sources')return coverage();if(kind==='library')return toolIndex();if(kind==='dictionary')return heading('查询与下载 / 材料','按作用查询材料','完整材料条目保持原始来源；实际使用去对应部位的一步步做。')+`<input class="library-search" id="dictionary-query" aria-label="搜索材料" placeholder="输入材料名、符文名或作用" value="${esc(params.get('q')||'')}"><div id="dictionary-results" class="panel">${dictRows(params.get('q')||'')}</div>`+footer();return _r41_tools(kind,params);}
function coverage(){return heading('查询与下载 / 来源边界','哪些已整合，哪些不能假装确认','布局与阅读衔接可以重做；缺少作者原件或游戏内验证的事实不能靠排版补出来。')+q42Rows([
 ['全站阅读','已重新组织','五分区共用阶段；剧情目标、连法、打造、材料预留和转换条件直接阅读，不再以旧iframe承担核心教程。'],
 ['装备操作','按当前状态解释','白装、蓝1/2、黄2–6与特殊对象分别处理；作者进阶配方独立，材料跟着操作。'],
 ['人物与异界','不混系统','技能／辅助、人物珠宝、大师、异界多选节点各有明确入口。30大节点建议不是作者逐项实装。'],
 ['原版过滤器','保持原文件','当前下载只有四份保存的原版；颜色、声音、金币、底材与碎片规则没有改。'],
 ['作者原构筑','保持快照','六份原件、技能、节点记录不回写；06隔离，60+剧情是已核对42–59配置延续。'],
 ['人物完整动态树／合法逐级点序','缺可靠完整依据','原记录不等于合法点序；未画伪造连线或把节点序号当人物等级。'],
 ['高风险工艺／辅助最低刻印Tier','仅在证据充分处执行','已有只读工艺和未审定材料档位继续明确标注，不借整站改版升级成保证。'],
 ['开荒外链三图','仍需要联网','文本路线可离线看；原作者三张图仅主动联网查看，未假称缓存成功。七张用户提供的Fubgun原图仍本地保存。'],
 ['客户端／国服名称／收益／部署','不以网页检查替代','未操作游戏或用户域名，不保证掉落、打造结果和实战强度。']
 ],['项目','当前状态','说明'])+sec('r42-sources','02','原始来源与本次使用范围',q42Rows(G42.sources.map(s=>[safeLink(s.url,esc(s.title||s.name||'作者正文')),esc(s.use),esc(s.readDate||'2026-10-03')]),['来源','用途','读取日期']))+expand('原件、完整出处与旧检查记录',sourcesBody())+`<div class="q42-links"><a class="btn" href="R42_全站重整与验收说明.md" download>下载本轮实际检查说明</a>${q42Link('tools/builds','原构筑文件','btn')}${q42Link('tools/filters','原版过滤器','btn')}</div>`+footer();}
function sourcesBody(){return `<p>每条装备目标、技能、材料与异界方案保留原有出处。下列是保存的来源索引，不把所有旧来源标成今天重新验证。</p>`+q42Rows(Object.entries(D.sources).map(([k,v])=>[esc(k),esc(typeof v==='string'?v:(v.title||v.name||v.label||k)),v.url?safeLink(v.url,'原始页面'):esc(v.note||v.use||'随原档案保留')]),['标识','来源','链接／范围']);}
function atlasUnlock(){const t=window.R42references?.['atlas-unlock.html'];return heading('异界与产出 / 解锁','解锁与刷收益，分两步走','用保存的0.5.5任务规则，不混成旧版首领解锁条件。')+q42Steps(D.atlasUnlock.map(x=>[x.title,x.text]))+`<div class="q42-links">${routeLink('atlas-starter','继续开荒主树路线','btn primary')}${routeLink('atlas-choices','大节点选项','btn')}${q42Link('learn/map-run','如何准备第一张地图','btn')}${q42Link('reference','要塞与非任务首领完整规则','btn',{doc:'atlas-unlock.html'})}</div>`+footer();}
function atlasStarter(){return _r41_atlasStarter();}
function atlasPage(id){return _r41_atlasPage(id);}
function nav(group){const entries=[['guide','book','成长路线','guide',[['guide','本阶段任务'],['troubleshoot','卡关与故障排查'],['learn/permanent','永久奖励'],['guide/basics','术语与基础']]],['gear','gear','装备与打造','gear',[['gear','全身目标装备'],['early-craft','按当前物品状态做'],['craft-timing','怎样判断值得做'],['supplies','获取、预留与收尾']]],['character','person','人物配置','character',[['character','连法、操作与天赋'],['gems','技能／辅助宝石'],['jewels','人物天赋珠宝'],['learn/ascendancy','升华与试炼']]],['atlas','atlas','异界与产出','atlas-starter',[['atlas-starter','开荒路线与加点'],['atlas-choices','大节点具体选项'],['atlas-choose','七套刷法与配套'],['learn/map-run','地图准备与风险'],['learn/mechanisms','机制与材料产出']]],['tools','tools','查询与下载','tools',[['tools','资料分类目录'],['tools/filters','四份原版过滤器'],['filter-guide','原版颜色与声音'],['filter-check','原版匹配查询'],['coverage','来源与检查边界']]]];$('#main-nav').innerHTML=entries.map(([id,ic,n,r,subs])=>q42Link(r,`${icon(ic,17)}<span>${n}</span>`,'nav-item '+(id===group?'active':''))+(id===group?`<div class="subnav">${subs.map(([r,n])=>q42Link(r,n,r===current.section+'/'+current.slot||r===current.section&&!current.slot?'on':'')).join('')}</div>`:'')).join('');}
function searchData(q){const base=[...G42.campaign.map(c=>({title:c.label+' · '+c.title,text:G42.milestones[c.id].now,route:'guide',params:{cp:c.id},query:c.skills.map(s=>s.zh).join(' ')+G42.milestones[c.id].keep})),...D.stages.map(p=>({title:labelStage(p),text:p.description||'原件快照与整套目标',route:'guide',params:{stage:p.id}})),...Object.entries(G42.slotGoals).map(([s,g])=>({title:g.title+'：目标、何时做、用什么',text:q42Label(state.context42),route:'item/'+s,params:q42Context(),query:g.goals.join(' ')})),{title:'异界大节点具体选项',text:'补充建议与解锁条件',route:'atlas-choices'},{title:'人物天赋珠宝',text:'普通珠宝／泉井之心／抗衡黑暗',route:'jewels',params:q42Context()},{title:'技能与辅助宝石数量',text:'同阶段连法和准备数量',route:'gems',params:q42Context()},{title:'四份原版过滤器',text:'不修改规则、颜色和声音',route:'tools/filters'},...Object.values(D.learningPages).map(p=>({title:p.title,text:p.summary,route:'learn/'+p.id,params:q42Context(),query:p.search})),...D.variants.map(v=>({title:v.zh,text:v.name+' · 七套方案',route:'atlas/'+v.id})),...Object.values(c41Catalog()).map(e=>({title:e.zh,text:'精华作用查询，不是自动使用',route:'tools/dictionary',params:{q:e.zh},query:e.en}))];if(!q)return base.slice(0,6);const ss=q.toLowerCase().trim().split(/\s+/);return base.filter(x=>ss.every(s=>(x.title+' '+(x.text||'')+' '+(x.query||'')).toLowerCase().includes(s))).slice(0,24);}
function dictRows(q=''){const e=Object.values(c41Catalog()).filter(e=>(e.zh+' '+e.en+' '+Object.values(e.effect||{}).join(' ')).toLowerCase().includes(q.toLowerCase()));const existing=_r41_dictRows(q);return (e.length?`<div class="q42-dictionary-essences">${e.map(x=>`<article class="dictionary-row"><div><strong>${esc(x.zh)}</strong><small>${esc(x.en)}</small>${safeLink(x.url,'条目来源')}</div><div>${q42Rows(Object.entries(x.effect).map(([s,e])=>[esc(s==='rings'?'戒指':c41Name(s)),esc(e)]),['适用部位','效果'])}<p>${esc(c41TierUse(x))}</p>${q42Link('early-craft','去当前部位按步骤判断','btn small')}</div></article>`).join('')}</div>`:'')+existing;}
function q42NormalizeLinks(){const root=$('#main-content');window.q42AnchorRepairs=[];root.querySelectorAll('a').forEach(a=>{let href=a.getAttribute('href')||'';if(href.startsWith('#/')){const [r,qs]=href.slice(2).split('?'),p=new URLSearchParams(qs||'');if(!p.has('stage')&&!p.has('cp'))Object.entries(q42Context()).forEach(([k,v])=>p.set(k,v));if(r==='reference'){const f=p.get('doc'),m=f?.match(/^([le]0[1-6])\.html$/);if(m){p.delete('doc');p.delete('query');p.delete('anchor');p.delete('stage');p.delete('cp');p.set(m[1][0]==='l'?'cp':'stage',m[1]);a.setAttribute('href',path('guide',Object.fromEntries(p)));return;}if(Q42FileMap[f]&&!(f==='atlas-unlock.html'&&current.section==='reference')){const [rr,pp]=Q42FileMap[f];if(rr!=='atlas-unlock'){p.delete('doc');Object.entries(pp).forEach(([k,v])=>p.set(k,v));a.setAttribute('href',path(rr,Object.fromEntries(p)));return;}}}a.setAttribute('href',path(r,Object.fromEntries(p)));}
 else if(!a.hasAttribute('download')&&!a.target&&href&&!/^https?:|^data:|^blob:|^#/.test(href)){const f=href.split(/[?#]/)[0].split('/').pop();if(D.documents.some(d=>d.file===f))a.setAttribute('href',path('reference',q42Context({doc:f})));}});
 root.querySelectorAll('table').forEach(t=>{if(!t.parentElement.matches('.table-scroll,.q42-table-scroll,.fg-table-scroll')){const w=document.createElement('div');w.className='table-scroll';t.before(w);w.append(t);}});
 root.querySelectorAll('[data-scroll]').forEach(a=>{if(!document.getElementById(a.dataset.scroll)){window.q42AnchorRepairs.push({target:a.dataset.scroll,text:a.textContent});a.removeAttribute('data-scroll');a.setAttribute('href',path('coverage',q42Context()));a.textContent='查看相关来源与边界';}});
}
function render(){const {parts,params}=parseHash();let page=parts[0]||'gear';const cp=params.get('cp'),st=params.get('stage');if(G42.campaign.some(c=>c.id===cp))state.context42=cp;else if(D.stages.some(s=>s.id===st)){state.stage=st;state.context42=st;}else if(!R42StageIds.includes(state.context42))state.context42='e01';if(state.context42.startsWith('e'))state.stage=state.context42;setStore('context42',state.context42);setStore('stage',state.stage);current={section:page,slot:parts[1],params};let body='',group='gear',crumb='全身装备目标';
 try{switch(page){case 'gear':body=gear();break;case 'item':current.slot=current.slot||'bow';body=itemPage(current.slot,params);crumb=D.slots.find(s=>s.id===current.slot)?.name||'单件目标';break;case 'guide':group='guide';crumb='本阶段任务';body=parts[1]==='basics'?basics():guide();break;case 'early-craft':body=earlyCraft();crumb='按当前状态做';break;case 'craft-timing':body=craftTiming();crumb='判断与比较';break;case 'supplies':body=supplies();crumb='获取与预留';break;case 'character':group='character';crumb='连法、操作与天赋';body=character();break;case 'gems':group='character';crumb='技能／辅助宝石';body=gemsPage();break;case 'special-gems':group='character';crumb='血脉辅助';body=specialGemsPage();break;case 'jewels':group='character';crumb='人物天赋珠宝';body=jewelsPage();break;case 'special-jewels':group='character';crumb='特殊人物珠宝';body=specialJewelsPage();break;case 'learn':{const q=D.learningPages[parts[1]]||D.learningPages.audit;body=learningPage(parts[1]);group=q.group||'guide';if(!['guide','gear','character','atlas','tools'].includes(group))group='guide';crumb=q.title;break;}case 'troubleshoot':group='guide';crumb='故障排查';body=troubleshoot();break;case 'atlas-starter':group='atlas';crumb='开荒路线';body=atlasStarter();break;case 'atlas-choose':group='atlas';crumb='七套刷法';body=atlasChoose();break;case 'atlas':group='atlas';crumb='加点与配套';body=atlasPage(parts[1]||state.variant);break;case 'atlas-choices':group='atlas';crumb='大节点选项';body=atlasChoices();break;case 'atlas-unlock':group='atlas';crumb='解锁';body=atlasUnlock();break;case 'tools':group='tools';crumb=parts[1]||'资料目录';body=tools(parts[1],params);break;case 'reference':group='tools';crumb='原详稿正文';body=referencePage(params);break;case 'filter-guide':group='tools';crumb='原版颜色与声音';body=filterGuidePage(params);break;case 'filter-check':group='tools';crumb='原版规则匹配';body=filterCheckPage(params);break;case 'coverage':group='tools';crumb='来源与检查边界';body=coverage();break;default:body=heading('页面地址','没有这个入口','原有资料没有删除；请从五个分区重新进入。')+q42Link('gear','回到全身目标','btn primary');}
 $('#main-content').innerHTML=body;delete $('#main-content').dataset.error;updateAscendancyProgress();fgAfterRender();q42NormalizeLinks();const labels={guide:'成长路线',gear:'装备与打造',character:'人物配置',atlas:'异界与产出',tools:'查询与下载'};$('#breadcrumb').innerHTML=`<span>${labels[group]}</span><span class="crumb-sep">/</span><span>${esc(crumb)}</span>`;nav(group);document.title=crumb+' · Fubgun 冰射 · R42';document.body.classList.toggle('compact',state.density);$('#density-toggle').textContent=state.density?'标准密度':'紧凑密度';$('#main-content').dataset.page=page;$('#main-content').dataset.context=state.context42;$('#main-content').dataset.ready='true';window.scrollTo(0,0);closeNav();}
 catch(e){console.error(e);$('#main-content').innerHTML=heading('页面未正确载入','请保留错误信息并返回主页',esc(e.message))+q42Link('gear','返回全身目标','btn');$('#main-content').dataset.error=e.message;}
}
function q42Route(){return current.section+(current.slot?'/'+current.slot:'');}
function q42Go(extra={},route=q42Route(),reset=false){navigate(route,{...(reset?{}:Object.fromEntries(current.params)),...q42Context(),...extra});}
document.addEventListener('change',e=>{const id=e.target.id,v=e.target.value;if(!['r42-stage','q42-slot','q42-craft-slot','q42-example-slot','q42-ref','c41-kind','c41-route','c41-advanced-step','c41-goal'].includes(id))return;e.stopImmediatePropagation();if(id==='r42-stage'){state.context42=v;if(v[0]==='e')state.stage=v;const p=q42Context();const tab=current.params.get('tab');if(['gear','guide','character','item'].includes(current.section)&&tab)p.tab=tab;let r=q42Route();if(current.section==='item'&&q42CP()&&!G42.slotGoals[current.slot])r='gear';navigate(r,p);return;}if(id==='q42-slot'||id==='q42-craft-slot'){q42Go({tab:current.params.get('tab')||'target'},'item/'+v,true);return;}if(id==='q42-example-slot'){q42Go({slot:v},'craft-timing',true);return;}if(id==='q42-ref'){q42Go({ref:v});return;}if(id==='c41-kind'){q42Go({kind:v,action:'',essence:'',goal:'',step:''});return;}if(id==='c41-route'){q42Go({route:v,kind:'unknown',action:'',essence:'',goal:'',step:''});return;}if(id==='c41-advanced-step'){q42Go({step:v,kind:'',action:'',essence:''});return;}if(id==='c41-goal')q42Go({goal:v,action:'',essence:''});},true);
document.addEventListener('submit',e=>{if(e.target.id!=='q42-resource')return;e.preventDefault();const f=new FormData(e.target),a=Number(f.get('total')),b=Number(f.get('used')),r=$('#q42-resource-result');if(f.get('total')===''||f.get('used')===''||!Number.isFinite(a)||!Number.isFinite(b)||a<0||b<0){r.textContent='请输入非负的实际数值，不能据空白推断够用。';return;}const n=Math.round((a-b)*100)/100;r.textContent=n>=0?`当前输入余量 ${n} 精魂。仍需检查额外生命预留、武器组和每项技能条件；这不代表所有技能自动生效。`:`当前输入不足 ${-n} 精魂。先减少或调整实际常驻，再重新核对；不要把基础值合计当最终预留。`;});
function exportSettings(){const data={schema:'fubgun-local-settings-v1',version:'R42',created:new Date().toISOString(),entries:{}};try{for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i);if(acceptLocalKey(k))data.entries[k]=localStorage.getItem(k)}}catch{}for(const[k,v]of transientStore){const full='fubgun-layout-'+k;if(acceptLocalKey(full))data.entries[full]=String(v)}const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='Fubgun_网页准备记录_R42.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),3000);toast('已导出网页中的手动记录，不包含游戏角色数据。');}
async function importSettings(file){if(!file)return;try{if(file.size>5*1024*1024)throw new Error('文件超过5MB，请使用本站导出的记录');const d=JSON.parse(await file.text());if(d.schema!=='fubgun-local-settings-v1'||!d.entries||typeof d.entries!=='object'||Array.isArray(d.entries))throw new Error('不是有效的本站记录');const pairs=Object.entries(d.entries).filter(([k,v])=>acceptLocalKey(k)&&typeof v==='string');for(const[k,v]of pairs){if(k.startsWith('fubgun-layout-'))setStore(k.slice(14),v);else try{localStorage.setItem(k,v)}catch{}}let ctx=getStore('context42',getStore('stage','e01'));if(!R42StageIds.includes(ctx))ctx='e01';state.context42=ctx;if(ctx[0]==='e')state.stage=ctx;state.variant=getStore('variant','expedition');if(!D.variants.some(s=>s.id===state.variant))state.variant='expedition';state.density=getStore('compact','no')==='yes';navigate('gear',q42Context());render();toast('已合并 '+pairs.length+' 项网页记录；未包含的项目保留。');}catch(e){toast('导入失败：'+e.message);}}
function q42UtilityTargets(){const c=q42CP();return `<section class="q42-utility-targets"><h2>药剂、咒符、人物珠宝与第二武器组</h2><p>和上面的十件主装备一起核对；这些栏位不套普通装备精华模板。</p>${q42Rows(D.slots.filter(s=>s.group!=='main').map(s=>{const f=D.finish[state.context42]?.[s.id];if(c){let n=s.name,goal='';if(s.group==='swap')goal='本阶段没有独立作者实装；先确认是否需要切换及哪些装备共享，不另造一份假目标。';else if(s.id==='jewels')goal='先看人物树实际已分配的孔；普通珠宝按当前短板选，剧情未提供逐孔实装或固定采购数量。';else if(s.id.startsWith('charm'))goal='对应槽位已开放才装备。核对触发、防护、充能与持续效果；没有开放的槽不采购占位。';else goal=(s.id==='life_flask'?'先比较实际生命回复量、回复速度和即时回复；':'先确认持续消耗与无小怪时的魔力回复；')+'优先使用当前可装备的合适药剂阶别，再看词缀与充能，不为短期过渡强制20品质。';return [esc(n),esc(s.group==='swap'?'无独立固定目标':'以当前已取得且可用的物品为准'),esc(goal),q42Link(s.id==='jewels'?'jewels':'item/'+s.id,'逐项核对','btn small',s.id==='jewels'?{}:{tab:'finish'})];}const t=targetData(s.id),raw=[...(t?.raw||[]),...(t?.definitions||[])];let desc=raw.map(r=>esc(r.text)).join('<br>');if(s.id==='jewels'){const j=D.jewelGuide.stages[state.stage];desc=esc(j.focus)+`<small>原件${j.uniqueCount}个不同孔位，未导出逐孔实物；不是保证已装${j.uniqueCount}颗。</small>`;}else if(!desc)desc=esc(f?.why||'没有独立原件属性，不复制另一件。');return [esc(s.name),esc(t?.title||s.name),desc+(t?.supplement?.length?`<details class="q42-inline"><summary>补充候选与限制</summary>${t.supplement.map(r=>`<p>${esc(r.text)}</p>`).join('')}</details>`:''),q42Link(s.id==='jewels'?'jewels':'item/'+s.id,'完整目标与条件','btn small')];}),['栏位','原件目标／当前条件','完整属性或使用要求','细节'])}</section>`;}
