// R47: current/future CHARACTER scope, with independent, complete ATLAS learning.
// Source files and game/filter rules are not rewritten.
const P47=window.GHOSTLINESS47;
const S47=['e04','e05','e06'];
const Labels47={e04:'暴击混合防御',e05:'高配冰射',e06:'作者实装'};
const Role47={e04:'当前配装目标',e05:'后续准备',e06:'仅供参考 · 只读'};
const Prev47={render,path,parseHash,search:searchData,tools,gear,item:itemPage,atlas:atlasPage,starter:atlasStarter,unlock:atlasUnlock,choices:atlasChoices,normalize:q42NormalizeLinks};
function goodStage47(s){return S47.includes(s)?s:'e04';}
state.stage=goodStage47(getStore('r47-stage','e04'));state.context42=state.stage;
function clean47(p={}){p={...p};delete p.cp;if(p.stage)p.stage=goodStage47(p.stage);return p;}
path=function(route,params={}){return Prev47.path(route,clean47(params));};
q42Context=function(extra={}){return clean47({stage:goodStage47(state.stage),...extra});};
parseHash=function(){const r=Prev47.parseHash();if(!location.hash||location.hash==='#/'||location.hash==='#')r.parts=['home'];if(r.params.has('stage'))r.params.set('stage',goodStage47(r.params.get('stage')));r.params.delete('cp');if(['my-gear','my-skills'].includes(r.parts[0]))r.params.set('stage','e04');if(['filter-guide','filter-check'].includes(r.parts[0])&&r.params.has('file')&&!['01','02','03','04'].includes(r.params.get('file')))r.params.set('file','01');
 if(r.parts[0]==='reference'&&/^(?:e0[123]|l0[1-6]|all|index)\.html$/.test(r.params.get('doc')||'')){r.parts=['guide'];r.params=new URLSearchParams({stage:'e04'});}
 return r;};
labelStage=function(p){return Labels47[p.id]||p.label;};
stageControl=function(){return `<div class="stage-control"><label for="r42-stage">人物构筑 · 当前与后续</label><select id="r42-stage" aria-label="人物构筑"><option value="e04" ${state.stage==='e04'?'selected':''}>暴击混合防御 · 当前</option><option value="e05" ${state.stage==='e05'?'selected':''}>高配冰射 · 后续</option><option value="e06" ${state.stage==='e06'?'selected':''}>作者实装 · 只读参考</option></select></div>`;};
r43BuildTabs=function(route='gear',extra={}){return `<nav class="r43-builds r47-builds" aria-label="当前与后续人物构筑">${S47.map(id=>routeLink(route,Labels47[id]+`<small>${Role47[id]}</small>`,'r43-build '+(state.stage===id?'is-active':'')+(id==='e06'?' separate':''),{stage:id,...extra})).join('')}</nav>`;};
r43Meta=function(b){return `<div class="r43-context r47-context"><div><b>${Labels47[b.stage]} · ${Role47[b.stage]}</b><span>${b.stage==='e04'?'已有暴击输出基础，混合防御仍在补齐；这是目标，不是已完成认证。':b.stage==='e05'?'未来配置可以提前看，材料与条件不齐时不拆掉当前能用的配置。':'仅作来源对照，原数据冲突与只读限制保留。'}</span></div><div>${q42Link('character','天赋与配置条件 →','text-link',{tab:'tree'})}${routeLink('atlas-starter','异界从入门继续 →','text-link')}</div></div>`;};
function link47(r,text,cls='btn',params={}){return routeLink(r,text,cls,params);}
function home47(){const p=P47.panels;return heading('Ghostliness · 84级锐眼','人物有进度，异界从入门继续','只移除已经越过的三套人物攻略，当前与后续、全套异界学习内容都保留。')+
`<div class="r47-track-grid"><section class="r47-track"><span class="r47-eyebrow">人物 · 根据已复核快照</span><h2>当前：暴击混合防御</h2><p>保住现有暴击输出，先补生存和防御配套。不按等级整树洗点，不要求重新做一套装备。</p><div class="actions">${link47('my-gear','我的装备与目标','btn primary')}${link47('gear','当前作者整套装备','btn',{stage:'e04'})}</div><div class="r47-follow">后续仍可看：${link47('gear','高配冰射','text-link',{stage:'e05'})} · ${link47('gear','作者实装（只读）','text-link',{stage:'e06'})}</div></section>
<section class="r47-track r47-atlas-track"><span class="r47-eyebrow">异界 · 按你说的“刚开始”</span><h2>从开荒、解锁和起步加点学起</h2><p>人物已转暴击，不等于你熟悉异界。第一张地图、大节点选项、大师、碑牌与后续七套刷法都在。</p><div class="actions">${link47('atlas-starter','进入异界入门','btn primary')}${link47('atlas-unlock','解锁与点数','btn')}${link47('atlas-choose','七套后续刷法','btn')}</div></section></div>
<section class="r47-current-filter"><div><strong>现在用：01 异界起步原版过滤器</strong><p>按当前拾取材料的需求选择，不跟人物构筑阶段自动升级。原版颜色、声音和显示规则不改。</p></div>${link47('tools/filters','在网站里看用法与选择 →','btn')}</section>
<section class="section first"><div class="section-title"><h2>本轮优先处理三件事</h2><p>这是优先顺序，不是只剩这三项内容</p></div><div class="r47-three"><article><small>1</small><h3>补冷抗、闪电抗</h3><p>快照冷抗30%、闪电抗53%。先比较左戒指；右戒会映射，火抗与魔力损失也要一起算。</p>${link47('my-gear','看我的左戒与目标','text-link',{focus:'r47-own-ring1'})}${link47('item/ring1','底材、替代与做法','text-link',{stage:'e04',tab:'target'})}</article><article><small>2</small><h3>准备应急回复</h3><p>按上一轮行动单，准备可主动使用的生命药剂；原“机遇”保留。蓝药替代也要维持恢复，不只去掉代价。</p>${link47('my-gear','看当前两瓶药剂','text-link',{focus:'r47-own-life_flask'})}</article><article><small>3</small><h3>补混合防御配套</h3><p>先核对技能、实际精魂和智慧，再准备护盾头。胸甲承担大量抗性，不先裸换。</p>${link47('my-skills','看技能差异与限制','text-link')}${link47('item/helmet','护盾头目标与制作','text-link',{stage:'e04',tab:'target'})}</article></div></section>
<section class="r43-panel r47-snapshot"><h2>当前资料是什么</h2><p>以下沿用2026年10月6日的官方角色快照，不是游戏现场，也没有重新读取你的角色。</p><div class="r43-kpis"><div><b>${p.life}</b><span>生命</span></div><div><b>${p.energy_shield}</b><span>能量护盾</span></div><div><b>${p.spirit}</b><span>精魂</span></div><div><b>${p.evasion}</b><span>闪避</span></div></div><p>完整个人天赋、技能品质与实际启用、个人异界树仍未取得。网页的选择不会替你洗点、换装、花材料或换过滤器。</p><a class="text-link" href="资料/Ghostliness_当前阶段与三步调整_20261006.md">查看原复核行动单</a></section>`+footer();}
function myCard47(it){return `<article class="r47-own-card"><header><span class="tag">我的快照 · ${esc(it.label)}</span><h3>${esc(it.player.name)}</h3></header><div class="r47-status"><b>${esc(it.status)}</b><p>${esc(it.advice)}</p></div><div class="r47-player-lines">${it.player.lines.map(s=>`<div>${esc(s)}</div>`).join('')}</div>${it.player.sockets.length?`<section class="r47-own-sockets"><h4>当前镶嵌</h4>${it.player.sockets.map(s=>`<details><summary>孔${s.index}：${esc(s.name)}</summary><p>${esc(s.text).replace(/\n/g,'<br>')}</p></details>`).join('')}</section>`:''}<a class="text-link" href="${esc(it.player.image)}" target="_blank" rel="noopener">查看角色原截图 ↗</a></article>`;}
function myGear47(){const b=C43.builds.find(b=>b.stage==='e04');let h=heading('Ghostliness · 角色快照对照','我的全身装备与当前目标','左侧是你的真实快照，右侧是作者目标；范围不是必需满值，先保留不是毕业认证。');h+=note('当前人物只以暴击混合防御为目标。作者的两枚普通戒指是参考配置，你的映射戒指组合必须成对比较净得失，不要求先换成两枚同款。');h+=`<nav class="r47-slot-nav" aria-label="按部位定位">${P47.items.map(it=>`<a href="#" data-scroll="r47-own-${it.id}">${esc(it.label)}</a>`).join('')}</nav>`;h+=P47.items.map(it=>`<section class="r47-item-pair-section" id="r47-own-${it.id}"><h2>${esc(it.label)} <span>${esc(it.status)}</span></h2><div class="r47-item-pair">${myCard47(it)}${r43Card(b.equipment.find(x=>x.uid===it.id),b,false)}</div></section>`).join('');h+=`<section class="r43-panel"><h2>天赋珠宝与下一步</h2><p>你的完整人物珠宝配置尚未取得，不能把作者珠宝当成你已经装备的物品。</p><div class="actions">${link47('jewels','看当前目标珠宝与准备方法','btn',{stage:'e04'})}${link47('my-skills','检查我的技能与目标差异','btn')}${link47('early-craft','完整打造工作台','btn',{stage:'e04'})}</div></section>`;return h+footer();}
function mySkills47(){return heading('Ghostliness · 技能对照','先核对配套，不直接整树洗点','按已取得的角色快照与对应作者连接对照；没有取得实际品质、启用和完整天赋。')+note('快照164精魂只是账面数值。按行动单检查实际预留、武器组和幽灵舞步品质；不能把战斗狂怒和新常驻无条件全部叠加。')+q42Rows(P47.skills.map(s=>[esc(s.name),s.player?`<p>${esc(s.player.name)} · ${s.player.level?'等级'+s.player.level:'等级未取得'}</p><p>${esc(s.player.gems.join(' ＋ '))}</p>`:'角色快照未列出',s.gems.map(g=>esc(g.name)).join(' ＋ '),esc(s.weapon_group)]),['技能','我的快照连接','作者目标连接','目标武器组'])+`<section class="r43-panel"><h2>防御与盲点仍需确认</h2><p>角色列表没有取得幽灵舞步和风舞者的实际启用。狙击“盲点”要求敌人被致盲；自身头盔的致盲不替代敌人致盲。完整天赋未知，不能断言绝无其他来源。</p><div class="actions">${link47('character','作者完整技能、天赋与条件','btn primary',{stage:'e04',tab:'skills'})}${link47('character','天赋原图（不是自动洗点）','btn',{stage:'e04',tab:'tree'})}${link47('atlas-starter','异界从入门继续','btn')}</div></section>`+footer();}
function atlasStrip47(){return `<section class="r47-atlas-strip"><div><span class="tag">异界与人物分开推进</span><p><b>你刚开始异界。</b>保留开荒、解锁、起步加点、所有大节点和后续刷法；浏览某套刷法不代表当前就要采用。</p></div><div class="actions">${link47('atlas-starter','异界入门','btn small')}${link47('atlas-unlock','解锁与点数','btn small')}${link47('atlas-choose','七套后续方案','btn small')}${link47('tools/filters','当前过滤器：01原版','btn small')}</div></section>`;}
atlasStarter=function(){return atlasStrip47()+Prev47.starter();};
atlasUnlock=function(){return atlasStrip47()+Prev47.unlock();};
atlasPage=function(id){return atlasStrip47()+Prev47.atlas(id);};
atlasChoices=function(){return Prev47.choices();};
atlasChoose=function(){return heading('异界攻略 / 后续方案','起步完整保留，后续方案也可查','以下是不同刷法，不是人物构筑的前后阶段；先从入门和当前任务推进。')+atlasStrip47()+`<div class="r47-atlas-grid">${C43.atlas.map(v=>`<article class="r43-panel"><span class="tag">后续查阅 · 不代表当前必用</span><h2>${esc(cn44(v.name))}</h2><p>保留完整原图、${v.keystone_selections.length}条作者已选绑定、大师、地图碑牌与操作说明。</p><div class="actions">${link47('atlas/'+v.id,'加点与完整方案','btn',{tab:'tree'})}${link47('atlas/'+v.id,'大节点选什么','btn',{tab:'choices'})}${link47('atlas/'+v.id,'大师与候选','btn',{tab:'masters'})}</div></article>`).join('')}</div>`+footer();};
function filters47(){return heading('必要资料 / 原版过滤器','现在用01异界起步原版','选择按你当前需要捡什么，不跟人物BD阶段同步。过滤器本身没有改动。')+`<section class="r47-current-filter"><div><strong>当前选择：01 · 异界起步原版</strong><p>你刚开始异界，还在补装与积累材料。先按这份保存的原版使用；它仍保留作者原有筛选，不承诺所有底材或小堆金币都会显示。</p></div><a class="btn primary" href="原版过滤器_从这里选/01_Fubgun_Early_Mapping.filter" download>下载当前原版</a></section><div class="r47-three">${[['03','后续：稳定刷图后按拾取需要比较'],['04','后续：超严格，不作为现在默认'],['02','备用：剧情过滤器，不是当前异界默认']].map(([id,desc])=>{const f=D.filterGuide.files[id];return `<article><h3>${esc(f.title)}</h3><p>${desc}</p><a class="btn small" href="原版过滤器_从这里选/${esc(f.name)}" download>查看并下载该原版</a></article>`}).join('')}</div><section class="r43-panel"><h2>放进游戏前只核对这几件事</h2><p>完整文件名应为 <code data-r44-original>01_Fubgun_Early_Mapping.filter</code>；不要选金币修正、底材补充或补材料派生版。当前页面只提供四份保存的原版。</p><p>放到游戏实际使用的过滤器目录后，在游戏的物品过滤器设置中手动选中并刷新。本网站不知道你的实际安装路径，也不会自动切换。</p><p>原版某些底材白边白字、没有额外声音，就保持原样。颜色、声音、显示／隐藏、碎片和金币规则全部不改。</p><div class="actions">${link47('filter-guide','原版颜色与声音完整说明','btn',{file:'01'})}${link47('filter-check','查物品实际命中规则','btn',{file:'01'})}${link47('atlas-starter','回异界入门','btn')}</div></section><details class="r43-proof"><summary>四份原文件名与校验值</summary>${['01','03','04','02'].map(id=>{const f=D.filterGuide.files[id];return `<p data-r44-original><code>${esc(f.name)}</code><br>${esc(f.sha256)}</p>`}).join('')}</details>`+footer();}
r38GemTabs=function(special=false){return `<div class="actions gem-tabs">${q42Link('gems','本阶段技能／辅助宝石','btn'+(!special?' primary':''))}${q42Link('special-gems','血脉辅助单独看','btn'+(special?' primary':''))}${q42Link('character','回到当前人物配置','btn')}<a class="btn" href="资料/当前与后续技能宝石清单.md" download>保存当前与后续清单</a></div>`;};
function buildFiles47(){return heading('原件 / 当前与后续','只保留当前及后续三份构筑','前三套不再出现在使用入口；作者实装仍只读，不作为必须升级的下一阶段。')+`<div class="r43-grid">${D.branches.map(b=>{const id='e0'+b.number;return `<section class="r43-panel"><span class="tag">${Role47[id]}</span><h2>${Labels47[id]}</h2><p>${id==='e06'?'源冲突保留，只供核对，不要当成已验证可直接使用的配置。':'原始构筑文件字节不变，使用前核对可用点数和配套。'}</p><a class="btn" href="${esc(b.download)}" download>${id==='e06'?'保存只读原件':'下载这套原件'}</a></section>`}).join('')}</div>`+footer();}
function scope47(){return heading('本版说明 / R47','人物删早期，异界不删起步','这次改变的是网站的实际内容范围与入口，不是单独发一份过滤器。')+q42Rows([['当前人物','暴击混合防御','按已有角色快照，防御仍在配套中'],['后续人物','高配冰射、作者实装','前者后续准备；后者只读对照'],['已移除使用入口','初入异界、非暴击中期、非暴击混合防御','不再出现在构筑选择、搜索或原件下载'],['异界内容','开荒、解锁、起步树、大节点、材料、大师、碑牌、七套刷法','完整保留，默认从入门开始'],['装备指导','底材、替代、完整属性、取得、工艺、品质与收尾','当前及后续完整保留，不只剩三项任务'],['过滤器','当前01，另留03／04后续及02备用','四份原文件字节不变'] ],['范围','实际保留或移除','说明'])+`<section class="r43-panel"><h2>资料与边界</h2><p>现装依据已上传的官方角色快照与原复核行动单；作者配置依据已取得的采集和R45。没有重新采集游戏，也没有改变你角色的技能、天赋和装备。</p><p>旧版本压缩包没有删除。原始证据可能记录过往构筑，但不再作为当前使用入口；不能因删除早期人物攻略而删除异界入门知识。</p><div class="actions">${link47('tools/builds','三份原始构筑','btn')}${link47('tools/names','名称来源','btn')}${link47('tools/capture-audit','采集差异与已知缺口','btn')}<a class="btn" href="00_打开网站.md">使用说明</a></div></section>`+footer();}
tools=function(k,p){if(k==='filters')return filters47();if(k==='builds')return buildFiles47();if(['selection-guide','sources'].includes(k))return scope47();if(k==='library')return scope47()+`<div class="actions">${link47('tools/dictionary','材料查询','btn')}${link47('supplies','材料与底材获取','btn')}${link47('learn/readiness','出发检查','btn')}</div>`;return Prev47.tools(k,p);};
coverage=function(){return scope47();};
footer=function(){return `<footer class="footer"><span>Ghostliness · R47 网站修正版</span><div>${link47('tools/selection-guide','本版保留范围','text-link')} · ${link47('tools/filters','当前过滤器选择','text-link')}</div></footer>`;};
q42Transition=function(){const b=r43Build();if(!b)return '';const next=b.stage==='e04'?'e05':null;return `<section class="r43-panel"><h2>${next?'什么时候再看高配冰射':'保留后续参考，不强制切换'}</h2><p>${esc(cn44(b.notes.transition))}</p>${next?r43List(branch().profile.gate):note(b.stage==='e06'?'此配置仅供原始证据对照，不提供当前执行指令。':'作者实装属于独立只读快照，不是必须进入的下一站。')}<div class="actions">${next?link47('gear','查看后续高配装备','btn',{stage:next}):link47('gear','返回当前人物目标','btn',{stage:'e04'})}${link47('atlas-starter','继续我的异界入门','btn')}</div></section>`;};
nav=function(group){const sec=current.section;let g=['home','my-gear','gear','item','jewels','special-jewels'].includes(sec)?'gear':['character','my-skills','gems','special-gems'].includes(sec)?'character':sec.startsWith('atlas')?'atlas':['early-craft','craft-timing','supplies'].includes(sec)||(sec==='item'&&current.params.get('tab')!=='target'&&current.params.get('tab'))?'craft':'tools';if(sec==='item'&&['craft','finish','steps','plan'].includes(current.params.get('tab')))g='craft';const entries=[
 ['gear','gear','我的装备与后续','home',{},[['home','当前该做什么',{}],['my-gear','我的现装与当前目标',{}],['gear','当前整套装备',{stage:'e04'}],['gear','后续高配装备',{stage:'e05'}],['gear','作者实装（只读）',{stage:'e06'}]]],
 ['character','person','人物配置','character',{stage:state.stage,tab:'tree'},[['my-skills','我的技能与目标差异',{}],['character','天赋与切换条件',{stage:state.stage,tab:'tree'}],['character','技能连接与操作',{stage:state.stage,tab:'skills'}],['jewels','人物珠宝与准备',{stage:state.stage}],['gems','技能宝石清单',{stage:state.stage}]]],
 ['atlas','atlas','异界：从入门继续','atlas-starter',{},[['atlas-starter','开荒与起步加点',{}],['atlas-unlock','解锁与天赋点获取',{}],['learn/map-run','第一张图与地图循环',{}],['atlas-starter','起步大节点选项',{tab:'choices'}],['atlas-choose','七套后续刷法',{}],['atlas/'+state.variant,'大师与候选',{tab:'masters'}],['atlas/'+state.variant,'地图与碑牌配套',{tab:'setup'}]]],
 ['craft','tools','装备打造','early-craft',{stage:state.stage},[['early-craft','手里这件下一步',{stage:state.stage}],['craft-timing','什么时候值得加工',{stage:state.stage}],['item/bow','当前配方与后续打造',{stage:state.stage,tab:'craft'}],['supplies','材料、底材与获取',{stage:state.stage}]]],
 ['tools','book','必要资料与下载','tools/filters',{},[['tools/filters','当前过滤器怎么选',{}],['guide','当前与后续配装任务',{stage:state.stage}],['learn/permanent','永久奖励核对',{}],['learn/ascendancy','升华与试炼',{}],['troubleshoot','卡关排查',{stage:state.stage}],['tools/builds','当前与后续构筑原件',{}],['tools/selection-guide','本版范围与来源',{}]]]
 ];$('#main-nav').innerHTML=entries.map(([id,ic,name,r,p,sub])=>routeLink(r,icon(ic)+`<span>${name}</span>`,'nav-item '+(id===g?'active':''),p)+(id===g?`<div class="subnav">${sub.map(([rr,nn,pp])=>routeLink(rr,nn,'',pp)).join('')}</div>`:'')).join('');};
searchData=function(q){const extras=[{title:'异界入门与第一张地图',text:'人物是暴击混合防御，异界仍从起步学',route:'atlas-starter',params:{},query:'异界 开荒 新手 起步 点数 地图'}, {title:'当前过滤器：01异界起步原版',text:'在网站里选择与下载，规则不改',route:'tools/filters',params:{},query:'过滤器 原版 声音 颜色 金币'},...P47.items.map(it=>({title:'我的'+it.label+'：'+it.player.name,text:it.status+' · '+it.advice,route:'my-gear',params:{focus:'r47-own-'+it.id},query:it.player.raw_tooltip}))];const words=String(q||'').trim().toLowerCase().split(/\s+/).filter(Boolean);const ex=words.length?extras.filter(x=>words.every(w=>(x.title+' '+x.text+' '+x.query).toLowerCase().includes(w))):extras.slice(0,3);const results=Prev47.search(q).filter(x=>!x.params?.cp&&(!x.params?.stage||S47.includes(x.params.stage))&&!(x.route==='reference'&&/^(?:e0[123]|l0[1-6]|all|index)\.html$/.test(x.params?.doc||'')));return [...ex,...results].slice(0,26);};
render=function(){state.stage=goodStage47(state.stage);state.context42=goodStage47(state.context42);const r=Prev47.render();document.title='Ghostliness · 当前与后续攻略 R47';setStore('r47-stage',state.stage);document.querySelectorAll('.side-bottom').forEach(e=>e.textContent='R47 · 人物当前与后续 · 异界完整');
 document.querySelectorAll('a[href]').forEach(a=>{const href=a.getAttribute('href');if(!href?.startsWith('#/'))return;const i=href.indexOf('?');if(i<0)return;const q=new URLSearchParams(href.slice(i+1));let dirty=false;if(q.has('cp')){q.delete('cp');dirty=true;}if(q.has('stage')&&!S47.includes(q.get('stage'))){q.set('stage','e04');dirty=true;}if(dirty)a.setAttribute('href',href.slice(0,i)+(q.size?'?'+q:''));});
 const f=current.params.get('focus');if(f&&/^r47-own-[a-z0-9_]+$/.test(f)){const e=document.getElementById(f);if(e)requestAnimationFrame(()=>e.scrollIntoView({block:'start'}));}
 document.documentElement.dataset.r47Ready='true';return r;};
window.R47={render,scope:S47,capture:C43,personal:P47,search:q=>searchData(q),state,getCurrent:()=>current};
