// R38: presentation additions. Original build connections and filter data remain unchanged.
function r38Slot(slot){return ({ring1:'rings',ring2:'rings'})[slot]||slot;}
function r38CraftParams(step,extra={}){const p=current.params||new URLSearchParams();return {stage:state.stage,route:p.get('route')||$('#recipe-select')?.value,step,...(p.get('alternate')?{alternate:p.get('alternate')}:{}),...(p.get('independent')?{independent:p.get('independent')}:{}),...extra};}
function r38EssencePanel(slot,r,isAlternate=false){const key=r38Slot(slot),g=D.essenceGuide.slots[key];if(!g||phase().readonly)return '';
 const selected=current.params?.get('essence');const early=r.id===g.route;
 const rows=g.options.map(id=>{const m=D.essenceGuide.catalog[id];const active=selected===id&&early;
 const targetParams=r38CraftParams('essence',{route:g.route,essence:id});
 return `<tr class="${active?'ess-selected':''}" data-essence-option="${esc(id)}"><td><strong>${esc(m.zh)}</strong><div class="sub">${esc(m.en)}</div><span class="tag gray">${esc(m.side)}</span></td><td><strong>${esc(m.effect[key])}</strong><p class="small muted">${esc(m.why)}</p></td><td><p>${esc(m.limit)}</p><div class="ess-row-actions">${routeLink('item/'+slot,active?'已选 · 查看使用前提':'选择这颗的升黄步骤','btn small'+(active?' primary':''),targetParams)}${safeLink(m.url,'数据来源')}</div></td></tr>`;
 }).join('');
 let body=`<div class="panel essence-panel" id="item-essences"><div class="panel-inner"><div class="split"><h3>这件${esc(g.name)}，精华怎么选？</h3><span class="tag">先选材料 · 再升黄</span></div><p class="small" style="margin-top:8px">${esc(g.choice)}</p><p class="small muted">${esc(g.start)}</p>${isAlternate?'<p class="risk-inline"><b>仅用于普通／稀有替代品，绝不点在上方暗金上。</b></p>':''}${!early?'<p class="risk-inline"><b>当前是作者专用工艺：</b>下表按钮会切换到普通起步分支，不能把两条路线接在一起。需要渎灵、显现或特定前缀预留时，继续使用当前专用路线。</p>':''}</div><div class="table-scroll"><table class="essence-table"><thead><tr><th>可选精华</th><th>在本部位的确定效果／时机</th><th>限制与选择</th></tr></thead><tbody>${rows}</tbody></table></div><div class="panel-inner essence-stop"><p><b>停手条件：</b>${esc(g.stop)}</p><p><b>还没有适合精华：</b>可保留蓝装先用，或 ${routeLink('item/'+slot,'选择富豪随机升黄','text-link',r38CraftParams('regal',{route:g.route}))}。先富豪、再普通升黄精华，不是合法连招。</p></div></div>`;
 if(g.advanced.length)body+=`<div class="ess-advanced">${g.advanced.map(([id,label])=>routeLink('item/'+slot,esc(label),'text-link',r38CraftParams('ready',{route:id}))).join('')}</div>`;
 body+=expand('精华阶级、前后缀与来源怎么核对',`<div class="target-points">${D.essenceGuide.rules.map((s,i)=>`<div><b>0${i+1}</b><span>${esc(s)}</span></div>`).join('')}</div><p class="small">${esc(D.essenceGuide.scope)}</p><p class="small muted">核对日期：${esc(D.essenceGuide.checked)}；数据区间不等于最小物等或佩戴等级。本次不改写原始配方记录，蓝装能否使用最终看客户端提示。</p>${safeLink(D.essenceGuide.ruleSource,'官方精华规则')}　${safeLink(D.essenceGuide.source,'作者完整工艺')}`);
 return body;
}
function r38PrepareRecipe(r){if(!r?.essenceSlot)return r;const key=r.essenceSlot,g=D.essenceGuide.slots[key],selected=current.params?.get('essence'),m=g.options.includes(selected)?D.essenceGuide.catalog[selected]:null;
 return {...r,steps:r.steps.map(s=>{if(s.id!=='essence')return s;if(!m)return {...s,title:'尚未选择具体精华：不要点材料',action:['先从上方表格选择一颗明确适用于本部位、解决当前缺口的精华。','尚未选择时，不提供默认自动用料；箭袋尤其不默认强塞命中词缀。'],expect:'保持蓝装，不执行升黄。',good:'选择后重新核对具体效果和前提。',bad:'没有相符缺口就回到富豪分支或直接停手。',materials:[],next:null};
 return {...s,title:'只使用一次：'+m.zh,before:s.before+' '+g.start,materials:['r38-'+selected],action:['当前选择【'+m.zh+'】；应新增'+m.side+'：'+m.effect[key]+'。',m.limit,'确认仍为魔法蓝装、材料适用且词缀组不冲突：右键【'+m.zh+'】→左键备用'+g.name+'一次。不得先富豪或接第二颗升黄精华。'],expect:'黄装保留原有词缀，新增'+m.effect[key]+'；检查实际数值和分组，不保证上限。',note:m.why+' '+g.stop,refs:[m.url,D.essenceGuide.ruleSource]};})};
}
function r38RecipeChoices(r,s){if(!r.essenceSlot||!s.choices?.length)return '';return `<div class="actions recipe-choices" aria-label="下一步选择">${s.choices.map(c=>routeLink('item/'+current.slot,esc(c.label),'btn small',r38CraftParams(c.id,{route:r.id,...(current.params?.get('essence')?{essence:current.params.get('essence')}:{})}))).join('')}</div>`;}
function r38GemRowInfo(id){return D.gemGuide.info[id];}
function r38GemTabs(special=false){return `<div class="actions gem-tabs">${routeLink('gems','本阶段需要哪些宝石','btn'+(!special?' primary':''),{stage:state.stage})}${routeLink('special-gems','特殊宝石单独看','btn'+(special?' primary':''),{stage:state.stage})}${routeLink('character','回到人物与完整连法','btn',{stage:state.stage})}<a class="btn" href="R38_六阶段宝石准备清单.md" download>保存六阶段清单</a></div>`;}
function r38GemGroup(rows,kind){const info=D.gemGuide.info;const selected=rows.filter(r=>info[r.id].kind===kind);if(!selected.length)return '';
 return `<div class="panel gem-group"><div class="gem-group-head"><h3>${esc(D.gemGuide.kinds[kind])}</h3><span class="small muted">${selected.length}种${kind==='granted'?' · 不计入宝石采购':' · '+selected.reduce((n,r)=>n+r.qty,0)+'颗'}</span></div><div class="table-scroll"><table class="gem-table"><thead><tr><th>宝石与准确阶别</th><th>需要数量</th><th>镶嵌在哪些位置</th><th>获取与启用检查</th></tr></thead><tbody>${selected.map(r=>{const g=info[r.id];return `<tr data-gem-id="${esc(r.id)}" data-gem-qty="${r.qty}"><td><strong>${esc(g.zh)}</strong><div class="sub">${esc(g.en)}</div>${g.kind==='lineage'?'<span class="tag gold">血脉辅助 · 非普通刻印</span>':''}${g.spirit!==null?`<span class="tag gray">基础精魂 ${g.spirit}</span>`:''}${safeLink(g.url,'原名／数据')}</td><td class="gem-quantity">${g.kind==='granted'?'不买':r.qty+'颗'}</td><td>${r.uses.map(u=>`<div class="gem-use">${esc(u)}</div>`).join('')}</td><td><p>${esc(kind==='support'&&g.cutTier===null?'未切割辅助宝石 → 选择同名、同阶；材料要求以刻印菜单为准。':g.get)}</p>${kind!=='support'||g.condition!=='在本页列出的技能位置镶嵌，并检查该技能标签、属性需求与实际孔位。'?`<p class="small muted">${esc(g.condition)}</p>`:''}</td></tr>`}).join('')}</tbody></table></div></div>`;
}
function r38GemChains(s){return `<div class="panel"><div class="table-scroll"><table class="gem-chain-table"><thead><tr><th>技能／元技能</th><th>当前阶段完整连接 · 保留原顺序</th></tr></thead><tbody>${s.chains.map(c=>`<tr><td><strong>${esc(c.zh)}</strong><div class="sub">${r38GemRowInfo(c.id).kind==='granted'?'升华给予技能本身':r38GemRowInfo(c.id).kind==='meta'?'精魂元技能':'按原件使用'}</div></td><td>${c.parts.map(p=>`<span class="skill-support ${p.embedded?'meta':''} ${p.special?'gem-lineage':''}">${p.embedded?'内嵌主动：':''}${esc(p.zh)}${p.special?' · 血脉':''}</span>`).join('')}</td></tr>`).join('')}</tbody></table></div></div>`;}
function r38GemChanges(s){if(s.readonly)return note('<b>06不是第五阶段之后的已验证升级：</b>只展示原件差异，不生成“照着再买这些就能转型”的采购指令。',true);if(!s.changes.length)return '<p class="small muted">01是本清单的起步基准；不把当前完整原件配置误当作刚进异界立刻全部具备的最低门槛。</p>';
 return `<div class="panel"><div class="table-scroll"><table class="gem-change-table"><thead><tr><th>宝石</th><th>上阶段 → 本阶段</th><th>本次要做什么</th></tr></thead><tbody>${s.changes.map(c=>`<tr><td><strong>${esc(skillName(c.id))}</strong></td><td>${c.before} → ${c.after} 颗</td><td>${c.delta>0?'额外准备 '+c.delta+' 颗；已有的继续使用':c.after===0?'本阶段原件不再使用，先保留旧宝石':'减少 '+(-c.delta)+' 颗的镶嵌；不是一定要卖掉'}</td></tr>`).join('')}</tbody></table></div></div><p class="caption">只比较数量变化，不代替上面的完整连法；同数量换了位置，也必须按新阶段重新镶嵌。</p>`;}
function gemsPage(){const s=D.gemGuide.stages[state.stage],kinds=D.gemGuide.kinds,info=D.gemGuide.info;const lineage=s.rows.filter(r=>info[r.id].kind==='lineage'),ice=s.rows.find(r=>info[r.id].en==='Ice Shot');
 let h=heading('人物与技能 / 宝石准备','这一阶段，需要哪些宝石？','按实际镶嵌位置汇总数量：先备当前要用的，再看后期新增。',true)+phaseNote(true)+r38GemTabs();
 h+=`<div class="gem-summary"><div><b>${s.gemTotal}</b><span>颗 · 原件完整配置</span></div><div><b>${s.types}</b><span>种 · 按准确阶别区分</span></div><div><b>${lineage.length}</b><span>种血脉辅助 · 本阶段</span></div><div><b>${ice?.qty||0}</b><span>颗冰霜射击 · 三处分别放</span></div></div>`;
 h+=note('<b>数量是“这一套里一共放多少”，不是每换阶段全部重买。</b>蜃影神射由升华给予，不计一颗宝石；两个元技能内嵌的冰霜射击仍各要准备一颗。');
 let main=sec('gem-now','01',s.readonly?'06原件宝石 · 只读对照':'本阶段完整准备清单',Object.keys(kinds).map(k=>r38GemGroup(s.rows,k)).join(''),'<p>中文为阅读对照；本体等级／品质没有原件依据时不填写假目标。</p>',true);
 main+=sec('gem-links','02','这些宝石具体连到哪里',r38GemChains(s)+`<div class="skill-setup-brief"><p><b>缺孔：</b>${esc(D.skillSetupNotes.links)}</p><p><b>武器组：</b>${esc(D.skillSetupNotes.weapon)}</p><p><b>特殊宝石：</b>替代方案不是无条件等效，缺关键组件先保留完整过渡配置。</p></div>`);
 main+=sec('gem-delta','03','相比上一阶段，哪些新增／哪些停用',r38GemChanges(s));
 const spirits=s.rows.filter(r=>info[r.id].spirit!==null);
 main+=sec('gem-spirit','04','精魂、等级和孔位别混在一起',`<div class="panel panel-inner"><p><b>未计品质、效率与特殊辅助的基础合计：${s.baseSpirit} 精魂。</b>这不是角色最终必须显示的精魂门槛。</p><p>${spirits.map(r=>esc(info[r.id].zh)+' '+info[r.id].spirit).join(' ＋ ')}</p>${lineage.some(r=>info[r.id].en==="Atziri's Communion")?'<p class="risk-inline">本阶段原件的风舞者连接阿兹里的圣礼，会转成生命预留。必须扣除相应精魂、核对生命预留，并同时计算品质／效率；不能直接把上面的基础合计当实装值。</p>':''}<p class="small muted">幻影射手、幽灵舞步等的品质或效率能改变实际预留。以上不含自行改配，也不自动判断技能是否真正启用。</p></div>`+expand('刻印、升级、品质、孔位：四个不同问题',D.gemGuide.notes.map(x=>`<p>${esc(x)}</p>`).join('')+`<p><b>先后顺序：</b>先能用主输出和基本防御／供蓝，再补孔和昂贵辅助。作者后期血脉辅助不要求Early提前全买。</p>${routeLink('learn/skill-check','无法启用时逐项检查','text-link')}`));
 main+=sec('gem-later','05','之后再准备，不提前混买',`<div class="panel panel-inner"><p>切换阶段即可查看对应全部数量。01–04原件没有血脉辅助；05出现五种，06只读另外记录欧罗什的信念。</p><div class="actions">${D.stages.map(x=>routeLink('gems',esc(x.label),'btn small'+(x.id===state.stage?' primary':''),{stage:x.id})).join('')}</div><div class="actions" style="margin-top:12px">${routeLink('special-gems','逐颗查看用途、获取与缺少时怎么办','btn',{stage:state.stage})}</div></div>`);
 main+=expand('数量、来源与验证范围',`<p>连接与数量：${esc(s.sourceFile)}；逐个读取主动、内嵌主动与辅助记录，未改连接。</p><p class="mono small">原件 SHA-256：${esc(s.sha256)}</p><p>普通宝石元数据与血脉辅助获取说明核对于 ${esc(D.gemGuide.checked)}。中文名称与国服客户端可能有差异；各行保留原名及具体数据出处。</p><p>清单勾稽和页面检查不是游戏实测；原件没有定义的宝石本体等级、品质、装备资源和收益不代填。</p>${safeLink(D.gemGuide.source,'Fubgun正文')}　${safeLink(D.gemGuide.ruleSource,'官方辅助系统说明')}　${safeLink(D.gemGuide.lineageSource,'血脉辅助数据')}`);
 return h+`<div class="content-with-toc"><div>${main}</div>${toc([['gem-now','01','准备清单'],['gem-links','02','完整连接'],['gem-delta','03','阶段变化'],['gem-spirit','04','精魂与等级'],['gem-later','05','后期再备']])}</div>`+footer();
}
function specialGemsPage(){const s=D.gemGuide.stages[state.stage],info=D.gemGuide.info,used=new Set(s.rows.filter(x=>x.qty).map(x=>x.id));
 let h=heading('人物与技能 / 特殊宝石','特殊宝石，单独列清楚','先分特殊获取，再分启用条件；“特殊”不等于所有阶段必备。',true)+phaseNote(true)+r38GemTabs(true);
 let main=sec('gem-lineages','01','六份原件涉及的血脉辅助',`<p class="gem-intro">01–04不需要提前凑这些。05原件使用前五种；第六种仅属于06只读快照。它们不是在普通未切割辅助菜单里找名字刻出来的。</p><div class="lineage-grid">${D.gemGuide.specialIds.map(id=>{const g=info[id],x=g.special,stages=Object.values(D.gemGuide.stages).filter(st=>st.counts[id]).map(st=>st.label);return `<article class="panel lineage-card ${used.has(id)?'lineage-current':''}" data-special-id="${esc(id)}"><div class="lineage-heading"><div><h3>${esc(g.zh)}</h3><div class="sub">${esc(g.en)}</div></div><span class="tag ${used.has(id)?'':'gray'}">${used.has(id)?(s.readonly?'本只读原件记录':'本阶段使用'):'本阶段不需要'}</span></div><p class="small muted">出现于：${esc(stages.join('、'))}</p><dl><dt>实际作用</dt><dd>${esc(x.effect)}</dd><dt>怎么获得</dt><dd>${esc(x.get)}</dd><dt>启用前提</dt><dd>${esc(x.condition)}</dd><dt>没有时怎么办</dt><dd>${esc(x.fallback)}</dd></dl><div class="lineage-bottom">${safeLink(x.source,'对应数据与掉落来源')}${routeLink('gems','看本阶段放在哪里','text-link',{stage:state.stage})}</div></article>`}).join('')}</div><p class="caption">来源为游戏数据条目，不承诺某次击杀必掉、固定价格或收益。可交易环境取得成品是替代获取方式，独狼环境按掉落准备；没有就先保留可用配置。</p>`,'',true);
 main+=sec('gem-conditions','02','不一定稀有，但要单独提醒',`<div class="panel"><div class="table-scroll"><table class="gem-condition-table"><thead><tr><th>对象</th><th>为什么容易弄错</th><th>正确准备</th></tr></thead><tbody>
 <tr><td><strong>元素军械 II</strong></td><td>名称看起来III更高，但III有不能施加元素异常状态的限制。</td><td>按原件保留II，不把它自动升级III。${safeLink('https://poe2db.tw/us/Elemental_Armament_III','III的限制')}</td></tr>
 <tr><td><strong>幻影射手</strong></td><td>精魂元技能，里面还要放主动技能；不是只插几个辅助。</td><td>准备1颗幻影射手＋1颗内嵌冰霜射击＋本阶段辅助；基础60精魂再计算效率。${safeLink('https://poe2db.tw/us/Mirage_Archer','技能数据')}</td></tr>
 <tr><td><strong>蜃影神射</strong></td><td>来自升华，不是需要在交易市场另买的宝石。</td><td>解锁对应升华；内嵌冰霜射击及辅助仍另备。${safeLink('https://poe2db.tw/us/Mirage_Deadeye','授予来源')}</td></tr>
 <tr><td><strong>魔力残片</strong></td><td>普通精魂技能宝石；特殊的是后期连接的两颗血脉辅助，不是它也必须专属掉落。</td><td>05起按精魂刻印准备，检查生成／拾取条件与资源，不当无条件回蓝。${safeLink('https://poe2db.tw/us/Mana_Remnants','技能数据')}</td></tr>
 <tr><td><strong>巨狼猛扑</strong></td><td>06只读的普通技能宝石，需要Talisman武器，并内嵌冰冻印记。</td><td>01–05不买、不照搬06变形配置；它不是武器免费授予的技能。${safeLink('https://poe2db.tw/us/Pounce','技能与武器要求')}</td></tr>
 <tr><td><strong>元素集中</strong></td><td>看到准备清单里有，不等于所有冰系技能都适合连接。</td><td>保持原件的狙击／寒冰之捷等位置，不随意装到需要冻结的主冰霜射击。${safeLink('https://poe2db.tw/us/Elemental_Focus','辅助限制')}</td></tr>
 </tbody></table></div></div>`);
 main+=sec('gem-avoid','03','缺特殊宝石时，先保住完整过渡配置',`<div class="panel panel-inner"><p><b>缺格鲁坎或拉其塔：</b>优先回看04原件整套技能连接与资源配置，不把单颗普通辅助包装成等价05。</p><p><b>缺阿兹里：</b>重新核对风舞者的精魂占用；没有替换成生命预留就不能沿用相同预算。</p><p><b>缺卡哈塔或达拉：</b>缺失的增益与等级／品质不计入恢复。保留已有供蓝方法，条件满足再逐项换。</p><p><b>欧罗什：</b>只读06记录，不加入01–05必买清单。</p><div class="actions">${routeLink('gems','04准备清单与原连接','btn',{stage:'e04'})}${routeLink('gems','05完整目标清单','btn',{stage:'e05'})}</div><p class="small muted" style="margin-top:12px">这些是本站过渡处理建议，不是作者承诺的同等伤害／恢复替代品。本页没有修改六份原始BD。</p></div>`);
 return h+`<div class="content-with-toc"><div>${main}</div>${toc([['gem-lineages','01','血脉辅助'],['gem-conditions','02','特殊条件'],['gem-avoid','03','缺少时处理']])}</div>`+footer();
}
function r38SearchEntries(){return [{title:'这一阶段需要哪些宝石：完整准备清单',text:'技能、精魂、辅助、数量、完整连法与阶段差异',route:'gems',params:{stage:state.stage},query:'宝石 准备 需要 哪些 清单 技能 辅助 数量 精魂 购买'}, {title:'特殊宝石与血脉辅助单独列表',text:'用途、获取、条件与过渡方案',route:'special-gems',params:{stage:state.stage},query:'特殊 宝石 辅助 血脉 掉落 首领 替代'},...Object.values(D.gemGuide.info).map(g=>({title:g.zh+' · 宝石清单',text:g.en+' / '+D.gemGuide.kinds[g.kind],route:g.kind==='lineage'?'special-gems':'gems',params:{stage:state.stage},query:g.get+' '+g.condition})),...Object.entries(D.essenceGuide.slots).map(([k,g])=>({title:g.name+' · 精华怎么选',text:'本部位效果、升黄分支、前提与停手',route:'item/'+(k==='rings'?'ring1':k),params:{stage:state.stage,route:g.route,step:'essence-choice'},query:'精华 '+g.options.map(id=>D.essenceGuide.catalog[id].zh).join(' ')}))];}
function r38AfterRender(){
 if(current.section!=='item'||!current.params?.get('step'))return;
 const key=r38Slot(current.slot),g=D.essenceGuide.slots[key];
 if(!g||current.params.get('route')!==g.route||phase().readonly)return;
 // A deliberate material/state selection should reveal its instructions, not jump back above the item target.
 const target=$('#item-craft .recipe-state-control');if(target)target.scrollIntoView({behavior:'instant',block:'start'});
}
